#!/usr/bin/env python3
"""
Phase 2: Add Targeted Sport-Specific Conditioning Protocols
Addresses critical gaps in:
- Cricket role-specific conditioning (fast bowler, spinner, batter)
- Lateral movement dominance for tennis/badminton
- Football position-specific conditioning
- Equipment variations (bands, sleds, medicine balls, agility equipment)
- Advanced movement profiles (rotational, diagonal, elastic)
"""

import json
from datetime import datetime

# Load existing data
with open('enriched_conditioning_data_phase1.json', 'r') as f:
    existing_protocols = json.load(f)

# New targeted protocols - Phase 2 Additions
new_protocols = [
    # ==================== CRICKET ROLE-SPECIFIC ====================
    {
        "id": "AC-108",
        "name": "Fast Bowler Repeat Effort — Over Simulation",
        "objective": "Develop repeat high-intensity bowling effort capacity. Simulate match demands of 6-ball overs with minimal recovery between deliveries.",
        "system": "Anaerobic Capacity",
        "level": "Intermediate to Elite",
        "environment": ["Field", "Turf", "Net Area"],
        "duration": "15-20 min",
        "work_description": "Run-in + delivery jump + follow-through (simulate bowling action). 6 reps = 1 over. Focus on maintaining speed and technique across all 6 balls.",
        "rest": "45 sec between reps (simulates time between deliveries), 3 min between overs",
        "sets": "4-6 overs",
        "total_volume": "24-36 high-intensity efforts",
        "fatigue_score": 7,
        "progression": "Add 1 over per week. Reduce rest between reps to 30 sec. Add weighted vest (2-5kg).",
        "regression": "Reduce to 3-4 overs. Increase rest to 60 sec between reps. Walk back recovery.",
        "tier": "A",
        "work_rest_ratio": "1:3",
        "sport_priority": {
            "cricket": "high",
            "tennis": "low",
            "badminton": "low",
            "football": "low"
        },
        "movement_profile": ["linear", "acceleration", "deceleration", "jumping"],
        "session_role": ["role-specific", "in-season-maintenance"],
        "impact_level": "high",
        "eccentric_load": "high",
        "fatigue_cost": "high",
        "equipment_need": "minimal",
        "field_space": "large",
        "phase_timing": ["pre-season", "in-season"],
        "surface_preference": ["grass", "turf"],
        "cricket_role_specific": ["fast_bowler"],
        "tennis_position": None,
        "badminton_position": None,
        "football_position": None,
        "energy_system_target": "glycolytic_power_endurance",
        "neuromuscular_demand": "high",
        "technical_complexity": "medium",
        "injury_risk_consideration": "Monitor lower back, knee, shoulder fatigue. Ensure proper warm-up.",
        "recovery_requirement": "48-72 hours between sessions",
        "metabolic_stress": "high",
        "created_phase": "phase2_targeted_expansion"
    },
    {
        "id": "AC-109",
        "name": "Spinner Rotational Endurance — Ball Release Precision",
        "objective": "Build rotational endurance specific to spin bowling. Maintain finger/wrist snap quality and core stability across extended spell.",
        "system": "Aerobic Power",
        "level": "Intermediate to Advanced",
        "environment": ["Net Area", "Indoor Facility", "Practice Pitch"],
        "duration": "20-25 min",
        "work_description": "Continuous rotational delivery motion (can use light ball or no ball). Focus on hip-shoulder separation, core rotation, and wrist positioning. 1 rep = 1 delivery motion.",
        "rest": "15 sec between reps (simulates field setting time)",
        "sets": "6 sets of 12 reps (72 total deliveries)",
        "total_volume": "72 rotational efforts",
        "fatigue_score": 5,
        "progression": "Increase to 8 sets. Add light resistance band around hips. Extend spell duration to 18 reps per set.",
        "regression": "Reduce to 4 sets of 8 reps. Increase rest to 30 sec. Perform seated initially.",
        "tier": "A",
        "work_rest_ratio": "1:1",
        "sport_priority": {
            "cricket": "high",
            "tennis": "medium",
            "badminton": "low",
            "football": "low"
        },
        "movement_profile": ["rotational", "multi-directional"],
        "session_role": ["role-specific", "skill-endurance"],
        "impact_level": "low",
        "eccentric_load": "moderate",
        "fatigue_cost": "moderate",
        "equipment_need": "minimal",
        "field_space": "small",
        "phase_timing": ["pre-season", "in-season"],
        "surface_preference": ["any"],
        "cricket_role_specific": ["spinner"],
        "tennis_position": None,
        "badminton_position": None,
        "football_position": None,
        "energy_system_target": "oxidative_power",
        "neuromuscular_demand": "medium",
        "technical_complexity": "high",
        "injury_risk_consideration": "Monitor finger, wrist, elbow, and lower back. Avoid excessive volume early season.",
        "recovery_requirement": "24-48 hours",
        "metabolic_stress": "moderate",
        "created_phase": "phase2_targeted_expansion"
    },
    {
        "id": "AC-110",
        "name": "Batter Between-Wicket Speed — Repeat Sprint Ability",
        "objective": "Maximize sprint speed between wickets with rapid deceleration/acceleration. Develop ability to repeatedly sprint hard singles and convert twos under fatigue.",
        "system": "ATP-PC System",
        "level": "All Levels",
        "environment": ["Pitch", "Net Area", "Turf"],
        "duration": "12-15 min",
        "work_description": "Sprint from crease to mid-pitch (8.5m), touch ground, sprint back. Alternate ends. Simulate calling and turning. Maximum intent on each sprint.",
        "rest": "20 sec between reps (simulates time between deliveries), 2 min between sets",
        "sets": "5 sets of 4 reps (20 total sprints)",
        "total_volume": "170m high-intensity sprinting",
        "fatigue_score": 6,
        "progression": "Increase to 6 reps per set. Reduce rest to 15 sec. Add reaction cue (coach call). Wear batting pads for specificity.",
        "regression": "Reduce to 3 reps per set. Increase rest to 30 sec. Walk recovery between reps.",
        "tier": "A",
        "work_rest_ratio": "1:4",
        "sport_priority": {
            "cricket": "high",
            "tennis": "low",
            "badminton": "low",
            "football": "medium"
        },
        "movement_profile": ["linear", "acceleration", "deceleration"],
        "session_role": ["role-specific", "speed-development"],
        "impact_level": "moderate",
        "eccentric_load": "high",
        "fatigue_cost": "moderate",
        "equipment_need": "none",
        "field_space": "medium",
        "phase_timing": ["pre-season", "in-season"],
        "surface_preference": ["grass", "turf", "pitch"],
        "cricket_role_specific": ["batter", "wicketkeeper"],
        "tennis_position": None,
        "badminton_position": None,
        "football_position": None,
        "energy_system_target": "phosphagen_capacity",
        "neuromuscular_demand": "very_high",
        "technical_complexity": "low",
        "injury_risk_consideration": "Hamstring strain risk. Ensure thorough dynamic warm-up. Monitor accumulated fatigue.",
        "recovery_requirement": "48 hours",
        "metabolic_stress": "moderate",
        "created_phase": "phase2_targeted_expansion"
    },
    {
        "id": "AC-111",
        "name": "Wicketkeeper Reactive Agility — Multi-Plane Movement",
        "objective": "Develop explosive lateral and forward/backward movement for keeping. Train reactive decision-making under physical demand. Improve standing start acceleration.",
        "system": "ATP-PC System",
        "level": "Intermediate to Elite",
        "environment": ["Behind Stumps Area", "Indoor Facility", "Turf"],
        "duration": "15-18 min",
        "work_description": "Start in keeping stance. React to visual cue (coach point, ball toss) and explode to designated cone (front, back, left, right, diagonal). Touch cone, return to stance. Randomize directions.",
        "rest": "25-30 sec between reps (full recovery for max power)",
        "sets": "6 sets of 5 reps (30 total reactions)",
        "total_volume": "30 explosive multi-directional efforts",
        "fatigue_score": 5,
        "progression": "Add glove catch at cone. Reduce reaction time. Add unbalanced starting positions. Use reaction lights.",
        "regression": "Pre-announce direction. Increase rest to 40 sec. Reduce to 4 sets.",
        "tier": "A",
        "work_rest_ratio": "1:5",
        "sport_priority": {
            "cricket": "high",
            "tennis": "medium",
            "badminton": "high",
            "football": "medium"
        },
        "movement_profile": ["lateral", "multi-directional", "acceleration", "deceleration"],
        "session_role": ["role-specific", "reactive-agility"],
        "impact_level": "moderate",
        "eccentric_load": "moderate",
        "fatigue_cost": "moderate",
        "equipment_need": "minimal",
        "field_space": "small",
        "phase_timing": ["pre-season", "in-season"],
        "surface_preference": ["grass", "turf", "indoor court"],
        "cricket_role_specific": ["wicketkeeper"],
        "tennis_position": None,
        "badminton_position": None,
        "football_position": None,
        "energy_system_target": "phosphagen_power",
        "neuromuscular_demand": "very_high",
        "technical_complexity": "medium",
        "injury_risk_consideration": "Ankle/knee stability crucial. Ensure proper footwear. Watch for lateral knee valgus.",
        "recovery_requirement": "48 hours",
        "metabolic_stress": "low",
        "created_phase": "phase2_targeted_expansion"
    },
    
    # ==================== TENNIS/BADMINTON LATERAL DOMINANCE ====================
    {
        "id": "AC-112",
        "name": "Tennis Lateral Shuffle — Court Coverage Endurance",
        "objective": "Build lateral movement endurance for baseline rallies. Develop ability to repeatedly cover wide forehand/backhand positions without speed loss.",
        "system": "Anaerobic Capacity",
        "level": "All Levels",
        "environment": ["Tennis Court", "Hard Court", "Clay Court"],
        "duration": "18-22 min",
        "work_description": "Start at center mark. Shuffle to singles sideline (forehand), touch line, shuffle back through center to backhand sideline, touch, return to center. Continuous fluid motion.",
        "rest": "20 sec between reps, 90 sec between sets",
        "sets": "5 sets of 6 reps",
        "total_volume": "30 lateral court traverses (~240m lateral movement)",
        "fatigue_score": 6,
        "progression": "Increase to 8 reps per set. Add racket swing simulation at each sideline. Reduce rest to 15 sec. Perform on clay for increased demand.",
        "regression": "Reduce to 4 reps per set. Walk recovery. Increase rest to 30 sec.",
        "tier": "A",
        "work_rest_ratio": "1:2",
        "sport_priority": {
            "cricket": "low",
            "tennis": "high",
            "badminton": "medium",
            "football": "low"
        },
        "movement_profile": ["lateral", "multi-directional"],
        "session_role": ["sport-specific", "court-movement"],
        "impact_level": "moderate",
        "eccentric_load": "high",
        "fatigue_cost": "moderate",
        "equipment_need": "minimal",
        "field_space": "medium",
        "phase_timing": ["pre-season", "in-season"],
        "surface_preference": ["hard court", "clay", "grass"],
        "cricket_role_specific": None,
        "tennis_position": ["baseline_player", "all_court"],
        "badminton_position": None,
        "football_position": None,
        "energy_system_target": "glycolytic_capacity",
        "neuromuscular_demand": "high",
        "technical_complexity": "low",
        "injury_risk_consideration": "Hip adductor strain risk. Ankle stability. Ensure proper lateral footwork mechanics.",
        "recovery_requirement": "48 hours",
        "metabolic_stress": "high",
        "created_phase": "phase2_targeted_expansion"
    },
    {
        "id": "AC-113",
        "name": "Badminton Net-to-Back Explosive — Multi-Directional Stamina",
        "objective": "Develop explosive forward/backward coverage for net play to backcourt clears. Train rapid direction changes under metabolic stress typical of badminton rallies.",
        "system": "Anaerobic Capacity",
        "level": "Intermediate to Elite",
        "environment": ["Badminton Court", "Indoor Court"],
        "duration": "15-20 min",
        "work_description": "Start at net. Backpedal to back boundary (doubles line), touch, explosive forward lunge to net, simulate net kill, repeat. Full court length coverage.",
        "rest": "15 sec between reps (simulates rally recovery), 2 min between sets",
        "sets": "6 sets of 8 reps",
        "total_volume": "48 full-court shuttles (~624m)",
        "fatigue_score": 7,
        "progression": "Add racket swing at each end. Reduce rest to 10 sec. Add jump smash simulation at back. Increase to 10 reps per set.",
        "regression": "Reduce to 5 reps per set. Walk recovery. Increase rest to 25 sec.",
        "tier": "A",
        "work_rest_ratio": "1:1",
        "sport_priority": {
            "cricket": "low",
            "tennis": "low",
            "badminton": "high",
            "football": "low"
        },
        "movement_profile": ["linear", "acceleration", "deceleration", "multi-directional"],
        "session_role": ["sport-specific", "rally-endurance"],
        "impact_level": "moderate",
        "eccentric_load": "high",
        "fatigue_cost": "high",
        "equipment_need": "minimal",
        "field_space": "small",
        "phase_timing": ["pre-season", "in-season"],
        "surface_preference": ["wooden floor", "synthetic court"],
        "cricket_role_specific": None,
        "tennis_position": None,
        "badminton_position": ["singles", "doubles"],
        "football_position": None,
        "energy_system_target": "glycolytic_power",
        "neuromuscular_demand": "very_high",
        "technical_complexity": "medium",
        "injury_risk_consideration": "Knee patellar tendon stress. Achilles load. Ensure proper landing mechanics.",
        "recovery_requirement": "48-72 hours",
        "metabolic_stress": "very_high",
        "created_phase": "phase2_targeted_expansion"
    },
    {
        "id": "AC-114",
        "name": "Tennis Split-Step Reaction — First Step Explosion",
        "objective": "Train split-step timing and first-step explosiveness in all directions. Improve reactive agility off opponent contact.",
        "system": "ATP-PC System",
        "level": "All Levels",
        "environment": ["Tennis Court", "Any Court Surface"],
        "duration": "12-15 min",
        "work_description": "Start at baseline center. Perform split-step on audio/visual cue, then explode to designated corner (forehand wide, backhand wide, short forehand, short backhand). Return to center, reset.",
        "rest": "20-25 sec between reps (full phosphagen recovery)",
        "sets": "5 sets of 6 reps (30 total reactions)",
        "total_volume": "30 explosive first-steps",
        "fatigue_score": 4,
        "progression": "Randomize cues. Add racket and ball toss simulation. Reduce rest to 15 sec. Use reaction light system.",
        "regression": "Pre-announce direction. Increase rest to 30 sec. Reduce to 4 sets.",
        "tier": "A",
        "work_rest_ratio": "1:4",
        "sport_priority": {
            "cricket": "low",
            "tennis": "high",
            "badminton": "high",
            "football": "medium"
        },
        "movement_profile": ["multi-directional", "acceleration", "lateral"],
        "session_role": ["sport-specific", "reactive-agility", "speed-development"],
        "impact_level": "low",
        "eccentric_load": "moderate",
        "fatigue_cost": "low",
        "equipment_need": "minimal",
        "field_space": "medium",
        "phase_timing": ["pre-season", "in-season", "competition-week"],
        "surface_preference": ["any"],
        "cricket_role_specific": None,
        "tennis_position": ["all_styles"],
        "badminton_position": ["all_styles"],
        "football_position": None,
        "energy_system_target": "phosphagen_power",
        "neuromuscular_demand": "very_high",
        "technical_complexity": "medium",
        "injury_risk_consideration": "Achilles tendon load. Ankle stability. Ensure proper split-step mechanics.",
        "recovery_requirement": "24-48 hours",
        "metabolic_stress": "low",
        "created_phase": "phase2_targeted_expansion"
    },
    
    # ==================== FOOTBALL POSITION-SPECIFIC ====================
    {
        "id": "AC-115",
        "name": "Football Wide Receiver — Route Running Repeat Speed",
        "objective": "Develop repeat sprint ability specific to route running patterns. Maintain top speed and sharp cuts across multiple plays under fatigue.",
        "system": "Anaerobic Capacity",
        "level": "Intermediate to Elite",
        "environment": ["Football Field", "Turf", "Grass"],
        "duration": "20-25 min",
        "work_description": "Run complete route tree pattern (slant, post, corner, out, comeback) at game speed. Reset to original position after each route. Focus on crisp cuts and acceleration out of breaks.",
        "rest": "30 sec between routes (simulates play clock), 3 min between sets",
        "sets": "4 sets of 5 routes (20 total routes)",
        "total_volume": "~800m high-intensity running with cuts",
        "fatigue_score": 7,
        "progression": "Add defender shadow (passive then active). Reduce rest to 20 sec. Add contact simulation. Increase to 6 routes per set.",
        "regression": "Reduce to 3 routes per set. Walk recovery. Increase rest to 45 sec.",
        "tier": "A",
        "work_rest_ratio": "1:2",
        "sport_priority": {
            "cricket": "low",
            "tennis": "low",
            "badminton": "low",
            "football": "high"
        },
        "movement_profile": ["linear", "cod", "acceleration", "deceleration", "lateral"],
        "session_role": ["position-specific", "skill-endurance"],
        "impact_level": "high",
        "eccentric_load": "very_high",
        "fatigue_cost": "high",
        "equipment_need": "minimal",
        "field_space": "large",
        "phase_timing": ["pre-season", "in-season"],
        "surface_preference": ["turf", "grass"],
        "cricket_role_specific": None,
        "tennis_position": None,
        "badminton_position": None,
        "football_position": ["wide_receiver", "cornerback"],
        "energy_system_target": "glycolytic_capacity",
        "neuromuscular_demand": "very_high",
        "technical_complexity": "high",
        "injury_risk_consideration": "ACL/MCL stress on cuts. Hamstring strain risk. Hip flexor load. Proper cutting mechanics essential.",
        "recovery_requirement": "72 hours",
        "metabolic_stress": "high",
        "created_phase": "phase2_targeted_expansion"
    },
    {
        "id": "AC-116",
        "name": "Football Midfielder — Box-to-Box Endurance",
        "objective": "Build work capacity for box-to-box midfield role. Develop ability to repeatedly cover large distances with varied intensities throughout match.",
        "system": "Aerobic Power",
        "level": "Intermediate to Elite",
        "environment": ["Football Pitch", "Grass", "Turf"],
        "duration": "25-30 min",
        "work_description": "Continuous movement pattern: jog (100m) → stride (50m) → sprint (25m) → walk (50m) → repeat. Vary directions and include backward running. Simulate match movement profile.",
        "rest": "None during sequence, 2 min between sets",
        "sets": "5-6 sets",
        "total_volume": "6-8 km equivalent movement",
        "fatigue_score": 6,
        "progression": "Extend set duration. Increase sprint distance. Add ball dribbling. Reduce rest to 90 sec.",
        "regression": "Reduce to 4 sets. Increase walking proportion. Extend rest to 3 min.",
        "tier": "A",
        "work_rest_ratio": "continuous",
        "sport_priority": {
            "cricket": "low",
            "tennis": "low",
            "badminton": "low",
            "football": "high"
        },
        "movement_profile": ["linear", "multi-directional", "cod"],
        "session_role": ["position-specific", "aerobic-development"],
        "impact_level": "moderate",
        "eccentric_load": "moderate",
        "fatigue_cost": "high",
        "equipment_need": "minimal",
        "field_space": "large",
        "phase_timing": ["pre-season", "early-in-season"],
        "surface_preference": ["grass", "turf"],
        "cricket_role_specific": None,
        "tennis_position": None,
        "badminton_position": None,
        "football_position": ["central_midfielder", "box_to_box"],
        "energy_system_target": "oxidative_power",
        "neuromuscular_demand": "moderate",
        "technical_complexity": "low",
        "injury_risk_consideration": "Accumulated fatigue management. Monitor hamstring, calf, hip flexor tightness.",
        "recovery_requirement": "48 hours",
        "metabolic_stress": "high",
        "created_phase": "phase2_targeted_expansion"
    },
    {
        "id": "AC-117",
        "name": "Football Center Back — Defensive Shuffle & Recovery Sprint",
        "objective": "Develop lateral defensive shuffling combined with explosive recovery sprints. Train ability to maintain defensive position then recover depth rapidly.",
        "system": "Anaerobic Capacity",
        "level": "All Levels",
        "environment": ["Football Pitch", "Training Area"],
        "duration": "18-22 min",
        "work_description": "Defensive shuffle laterally 10m (stay low, maintain defensive stance), then explosive forward sprint 15m (recovery run), walk back. Repeat alternating directions.",
        "rest": "20 sec between reps, 2 min between sets",
        "sets": "5 sets of 6 reps",
        "total_volume": "30 defensive actions (~750m)",
        "fatigue_score": 6,
        "progression": "Add aerial jump simulation at sprint end. Reduce rest to 15 sec. Add passive defender pressure. Increase to 8 reps.",
        "regression": "Reduce to 4 reps per set. Increase rest to 30 sec. Walk recovery.",
        "tier": "A",
        "work_rest_ratio": "1:2",
        "sport_priority": {
            "cricket": "low",
            "tennis": "low",
            "badminton": "low",
            "football": "high"
        },
        "movement_profile": ["lateral", "linear", "acceleration"],
        "session_role": ["position-specific", "defensive-movement"],
        "impact_level": "moderate",
        "eccentric_load": "high",
        "fatigue_cost": "moderate",
        "equipment_need": "none",
        "field_space": "medium",
        "phase_timing": ["pre-season", "in-season"],
        "surface_preference": ["grass", "turf"],
        "cricket_role_specific": None,
        "tennis_position": None,
        "badminton_position": None,
        "football_position": ["center_back", "full_back"],
        "energy_system_target": "glycolytic_capacity",
        "neuromuscular_demand": "high",
        "technical_complexity": "medium",
        "injury_risk_consideration": "Groin/adductor strain from lateral work. Knee stability. Maintain low center of gravity.",
        "recovery_requirement": "48 hours",
        "metabolic_stress": "moderate",
        "created_phase": "phase2_targeted_expansion"
    },
    {
        "id": "AC-118",
        "name": "Football Striker — Penalty Box Explosiveness",
        "objective": "Maximize explosive movements in confined penalty box area. Develop quick acceleration, deceleration, and jumping for finishing opportunities.",
        "system": "ATP-PC System",
        "level": "All Levels",
        "environment": ["Penalty Box Area", "Football Pitch"],
        "duration": "15-18 min",
        "work_description": "Within penalty box: explosive 5m sprint → plant & cut → jump (header simulation) → immediate 5m sprint in new direction. Randomize directions. Maximum intent on each movement.",
        "rest": "30 sec between reps (full recovery for max power)",
        "sets": "6 sets of 5 reps",
        "total_volume": "30 explosive box movements",
        "fatigue_score": 5,
        "progression": "Add cross reception simulation. Reduce rest to 20 sec. Add defender contact (passive). Increase to 7 reps.",
        "regression": "Reduce to 4 reps per set. Increase rest to 40 sec. Remove jump component initially.",
        "tier": "A",
        "work_rest_ratio": "1:5",
        "sport_priority": {
            "cricket": "low",
            "tennis": "low",
            "badminton": "low",
            "football": "high"
        },
        "movement_profile": ["acceleration", "deceleration", "cod", "jumping"],
        "session_role": ["position-specific", "explosive-power"],
        "impact_level": "high",
        "eccentric_load": "very_high",
        "fatigue_cost": "moderate",
        "equipment_need": "minimal",
        "field_space": "medium",
        "phase_timing": ["pre-season", "in-season"],
        "surface_preference": ["grass", "turf"],
        "cricket_role_specific": None,
        "tennis_position": None,
        "badminton_position": None,
        "football_position": ["striker", "center_forward", "winger"],
        "energy_system_target": "phosphagen_power",
        "neuromuscular_demand": "very_high",
        "technical_complexity": "medium",
        "injury_risk_consideration": "High knee/ankle load. ACL stress on cuts. Ensure proper landing mechanics from jumps.",
        "recovery_requirement": "48-72 hours",
        "metabolic_stress": "low",
        "created_phase": "phase2_targeted_expansion"
    },
    
    # ==================== EQUIPMENT-VARIED PROTOCOLS ====================
    {
        "id": "AC-119",
        "name": "Resistance Band Acceleration Sprints",
        "objective": "Develop horizontal force production and acceleration mechanics against variable resistance. Build strength-speed specific to sprinting.",
        "system": "ATP-PC System",
        "level": "Intermediate to Elite",
        "environment": ["Field", "Turf", "Track", "Gym"],
        "duration": "15-20 min",
        "work_description": "Attach resistance band around waist (partner holds or anchored). Sprint 15-20m against resistance. Focus on forward lean, powerful arm drive, and knee lift. Walk back recovery.",
        "rest": "45-60 sec between reps (full recovery)",
        "sets": "5-6 sets of 4 reps",
        "total_volume": "20-24 resisted sprints",
        "fatigue_score": 5,
        "progression": "Increase band resistance. Extend sprint distance to 25m. Reduce rest to 40 sec. Add release sprints (band assistance after 10m).",
        "regression": "Reduce to 3 reps per set. Use lighter band. Increase rest to 75 sec.",
        "tier": "A",
        "work_rest_ratio": "1:6",
        "sport_priority": {
            "cricket": "high",
            "tennis": "high",
            "badminton": "medium",
            "football": "high"
        },
        "movement_profile": ["linear", "acceleration"],
        "session_role": ["speed-development", "strength-speed"],
        "impact_level": "moderate",
        "eccentric_load": "moderate",
        "fatigue_cost": "moderate",
        "equipment_need": "resistance_bands",
        "field_space": "medium",
        "phase_timing": ["pre-season", "early-in-season"],
        "surface_preference": ["grass", "turf", "track"],
        "cricket_role_specific": None,
        "tennis_position": None,
        "badminton_position": None,
        "football_position": None,
        "energy_system_target": "phosphagen_power",
        "neuromuscular_demand": "very_high",
        "technical_complexity": "medium",
        "injury_risk_consideration": "Ensure secure band attachment. Monitor hamstring load. Progress resistance gradually.",
        "recovery_requirement": "48 hours",
        "metabolic_stress": "low",
        "created_phase": "phase2_targeted_expansion"
    },
    {
        "id": "AC-120",
        "name": "Sled Push Intervals — Lower Body Power Endurance",
        "objective": "Build lower body power endurance and horizontal force production. Develop leg drive and core stability under load.",
        "system": "Anaerobic Capacity",
        "level": "Intermediate to Elite",
        "environment": ["Turf", "Track", "Gym Floor"],
        "duration": "18-22 min",
        "work_description": "Load sled with moderate-heavy weight (50-75% bodyweight). Push sled 20-25m with maximum effort. Focus on driving through legs, maintaining forward lean.",
        "rest": "60-75 sec between reps, 3 min between sets",
        "sets": "4-5 sets of 4 reps",
        "total_volume": "16-20 sled pushes (~400m)",
        "fatigue_score": 7,
        "progression": "Increase sled weight. Extend distance to 30m. Reduce rest to 50 sec. Add backward sled pulls for variation.",
        "regression": "Reduce sled weight by 30%. Reduce to 3 reps per set. Increase rest to 90 sec.",
        "tier": "A",
        "work_rest_ratio": "1:3",
        "sport_priority": {
            "cricket": "medium",
            "tennis": "medium",
            "badminton": "low",
            "football": "high"
        },
        "movement_profile": ["linear", "acceleration"],
        "session_role": ["strength-endurance", "power-development"],
        "impact_level": "low",
        "eccentric_load": "minimal",
        "fatigue_cost": "high",
        "equipment_need": "sled",
        "field_space": "medium",
        "phase_timing": ["pre-season", "off-season"],
        "surface_preference": ["turf", "track"],
        "cricket_role_specific": None,
        "tennis_position": None,
        "badminton_position": None,
        "football_position": None,
        "energy_system_target": "glycolytic_capacity",
        "neuromuscular_demand": "high",
        "technical_complexity": "low",
        "injury_risk_consideration": "Lower back positioning crucial. Shoulder/wrist comfort. Start with lighter loads.",
        "recovery_requirement": "72 hours",
        "metabolic_stress": "high",
        "created_phase": "phase2_targeted_expansion"
    },
    {
        "id": "AC-121",
        "name": "Medicine Ball Rotational Power Throws",
        "objective": "Develop rotational power and core-to-extremity force transfer. Build explosive trunk rotation specific to throwing/striking sports.",
        "system": "ATP-PC System",
        "level": "All Levels",
        "environment": ["Gym", "Wall Area", "Outdoor Wall"],
        "duration": "15-18 min",
        "work_description": "Stand sideways to wall (3-4m away). Hold med ball (3-6kg). Rotate hips and torso explosively, throw ball against wall. Catch rebound, reset, repeat. Switch sides after set.",
        "rest": "30 sec between reps, 2 min between sets",
        "sets": "4 sets of 6 reps per side",
        "total_volume": "48 rotational throws",
        "fatigue_score": 4,
        "progression": "Increase ball weight. Increase distance from wall. Add jump before throw. Reduce rest to 25 sec.",
        "regression": "Reduce ball weight. Decrease distance. Reduce to 4 reps per set. Increase rest to 40 sec.",
        "tier": "A",
        "work_rest_ratio": "1:4",
        "sport_priority": {
            "cricket": "high",
            "tennis": "high",
            "badminton": "medium",
            "football": "medium"
        },
        "movement_profile": ["rotational", "multi-directional"],
        "session_role": ["power-development", "core-strength"],
        "impact_level": "low",
        "eccentric_load": "moderate",
        "fatigue_cost": "low",
        "equipment_need": "medicine_ball",
        "field_space": "small",
        "phase_timing": ["pre-season", "in-season"],
        "surface_preference": ["any"],
        "cricket_role_specific": None,
        "tennis_position": None,
        "badminton_position": None,
        "football_position": None,
        "energy_system_target": "phosphagen_power",
        "neuromuscular_demand": "high",
        "technical_complexity": "medium",
        "injury_risk_consideration": "Shoulder stability. Lower back rotation control. Start with lighter ball to master technique.",
        "recovery_requirement": "48 hours",
        "metabolic_stress": "low",
        "created_phase": "phase2_targeted_expansion"
    },
    {
        "id": "AC-122",
        "name": "Agility Ladder Foot Speed — Rapid Fire Patterns",
        "objective": "Develop rapid foot turnover, coordination, and ankle stiffness. Improve neuromuscular efficiency for quick directional changes.",
        "system": "ATP-PC System",
        "level": "All Levels",
        "environment": ["Gym", "Court", "Turf", "Indoor"],
        "duration": "12-15 min",
        "work_description": "Perform various ladder drills: single-leg hops, lateral shuffles, in-and-outs, icky shuffle, crossover steps. Focus on minimal ground contact time and precision.",
        "rest": "30 sec between patterns, 90 sec between sets",
        "sets": "4 sets of 5 different patterns",
        "total_volume": "20 ladder passes",
        "fatigue_score": 4,
        "progression": "Increase speed while maintaining accuracy. Add cognitive dual-task (call colors, react to cues). Reduce rest to 20 sec.",
        "regression": "Slow down focus on accuracy. Increase rest to 45 sec between patterns. Reduce to 3 patterns per set.",
        "tier": "A",
        "work_rest_ratio": "1:3",
        "sport_priority": {
            "cricket": "high",
            "tennis": "high",
            "badminton": "high",
            "football": "high"
        },
        "movement_profile": ["lateral", "multi-directional", "cod"],
        "session_role": ["neuromuscular-warmup", "foot-speed"],
        "impact_level": "low",
        "eccentric_load": "minimal",
        "fatigue_cost": "low",
        "equipment_need": "agility_ladder",
        "field_space": "small",
        "phase_timing": ["pre-season", "in-season", "competition-week"],
        "surface_preference": ["firm surface", "court", "turf"],
        "cricket_role_specific": None,
        "tennis_position": None,
        "badminton_position": None,
        "football_position": None,
        "energy_system_target": "phosphagen_power",
        "neuromuscular_demand": "very_high",
        "technical_complexity": "medium",
        "injury_risk_consideration": "Ankle stability. Ensure adequate warm-up. Progress complexity gradually.",
        "recovery_requirement": "24 hours",
        "metabolic_stress": "low",
        "created_phase": "phase2_targeted_expansion"
    },
    {
        "id": "AC-123",
        "name": "Weighted Vest Court Sprints — Tennis Specific",
        "objective": "Build sport-specific speed endurance with added resistance. Develop ability to maintain court coverage speed under fatigue with external load.",
        "system": "Anaerobic Capacity",
        "level": "Intermediate to Elite",
        "environment": ["Tennis Court"],
        "duration": "18-22 min",
        "work_description": "Wear weighted vest (5-10% bodyweight). Sprint from baseline to net, touch net, backpedal to baseline, shuffle to opposite corner, repeat pattern continuously.",
        "rest": "20 sec between reps, 2 min between sets",
        "sets": "5 sets of 6 reps",
        "total_volume": "30 court sprints with load",
        "fatigue_score": 7,
        "progression": "Increase vest weight. Reduce rest to 15 sec. Increase to 8 reps per set. Add racket and ball simulation.",
        "regression": "Remove vest or reduce weight. Reduce to 4 reps per set. Increase rest to 30 sec.",
        "tier": "A",
        "work_rest_ratio": "1:2",
        "sport_priority": {
            "cricket": "low",
            "tennis": "high",
            "badminton": "medium",
            "football": "low"
        },
        "movement_profile": ["linear", "multi-directional", "acceleration", "deceleration"],
        "session_role": ["sport-specific", "speed-endurance"],
        "impact_level": "high",
        "eccentric_load": "high",
        "fatigue_cost": "high",
        "equipment_need": "weighted_vest",
        "field_space": "medium",
        "phase_timing": ["pre-season", "early-in-season"],
        "surface_preference": ["hard court", "clay"],
        "cricket_role_specific": None,
        "tennis_position": ["all_styles"],
        "badminton_position": None,
        "football_position": None,
        "energy_system_target": "glycolytic_capacity",
        "neuromuscular_demand": "high",
        "technical_complexity": "low",
        "injury_risk_consideration": "Increased joint loading from vest. Monitor knee, ankle, hip stress. Gradual progression essential.",
        "recovery_requirement": "72 hours",
        "metabolic_stress": "high",
        "created_phase": "phase2_targeted_expansion"
    },
    
    # ==================== ADVANCED MOVEMENT PROFILES ====================
    {
        "id": "AC-124",
        "name": "Rotational Medicine Ball Slam Series",
        "objective": "Develop explosive rotational power and core-to-ground force transfer. Build anti-rotational stability and trunk stiffness.",
        "system": "ATP-PC System",
        "level": "Intermediate to Elite",
        "environment": ["Gym", "Turf", "Concrete Area"],
        "duration": "15-18 min",
        "work_description": "Hold med ball (4-8kg) overhead. Explosively rotate and slam ball to ground beside foot. Pick up, reset, repeat. Complete set, switch sides.",
        "rest": "30 sec between reps, 2 min between sets",
        "sets": "4 sets of 8 reps per side",
        "total_volume": "64 rotational slams",
        "fatigue_score": 5,
        "progression": "Increase ball weight. Add jump before slam. Reduce rest to 25 sec. Increase to 10 reps per side.",
        "regression": "Reduce ball weight. Reduce to 6 reps per side. Increase rest to 40 sec.",
        "tier": "A",
        "work_rest_ratio": "1:4",
        "sport_priority": {
            "cricket": "high",
            "tennis": "high",
            "badminton": "medium",
            "football": "medium"
        },
        "movement_profile": ["rotational", "multi-directional"],
        "session_role": ["power-development", "core-strength"],
        "impact_level": "moderate",
        "eccentric_load": "moderate",
        "fatigue_cost": "moderate",
        "equipment_need": "medicine_ball",
        "field_space": "small",
        "phase_timing": ["pre-season", "in-season"],
        "surface_preference": ["concrete", "turf", "gym floor"],
        "cricket_role_specific": None,
        "tennis_position": None,
        "badminton_position": None,
        "football_position": None,
        "energy_system_target": "phosphagen_power",
        "neuromuscular_demand": "high",
        "technical_complexity": "medium",
        "injury_risk_consideration": "Lower back positioning. Shoulder health. Control eccentric phase on pickup.",
        "recovery_requirement": "48 hours",
        "metabolic_stress": "moderate",
        "created_phase": "phase2_targeted_expansion"
    },
    {
        "id": "AC-125",
        "name": "Diagonal Bound Series — Elastic Power Development",
        "objective": "Develop elastic power in diagonal movement planes. Build single-leg reactive strength and lateral force production.",
        "system": "ATP-PC System",
        "level": "Intermediate to Elite",
        "environment": ["Turf", "Grass", "Track", "Gym Floor"],
        "duration": "15-18 min",
        "work_description": "Perform continuous diagonal bounds (forward-lateral). Emphasize minimal ground contact, maximal distance. Land softly, immediately rebound into next bound. Alternate directions.",
        "rest": "45 sec between sets",
        "sets": "5 sets of 6 bounds per direction",
        "total_volume": "30 diagonal bounds per leg",
        "fatigue_score": 5,
        "progression": "Increase bound distance. Add arm swing for momentum. Reduce rest to 35 sec. Increase to 8 bounds.",
        "regression": "Reduce bound distance. Focus on soft landing. Increase rest to 60 sec. Reduce to 4 bounds.",
        "tier": "A",
        "work_rest_ratio": "1:5",
        "sport_priority": {
            "cricket": "medium",
            "tennis": "high",
            "badminton": "high",
            "football": "medium"
        },
        "movement_profile": ["diagonal", "lateral", "jumping", "multi-directional"],
        "session_role": ["plyometric-development", "elastic-power"],
        "impact_level": "high",
        "eccentric_load": "very_high",
        "fatigue_cost": "moderate",
        "equipment_need": "none",
        "field_space": "medium",
        "phase_timing": ["pre-season", "early-in-season"],
        "surface_preference": ["grass", "turf", "sprung floor"],
        "cricket_role_specific": None,
        "tennis_position": None,
        "badminton_position": None,
        "football_position": None,
        "energy_system_target": "phosphagen_power",
        "neuromuscular_demand": "very_high",
        "technical_complexity": "high",
        "injury_risk_consideration": "High ankle/knee load. ACL stress. Ensure adequate base strength before implementation.",
        "recovery_requirement": "72 hours",
        "metabolic_stress": "low",
        "created_phase": "phase2_targeted_expansion"
    },
    {
        "id": "AC-126",
        "name": "Elastic Band Resisted Lateral Shuffles",
        "objective": "Build lateral power against variable resistance. Strengthen hip abductors/adductors in sport-specific movement pattern.",
        "system": "Anaerobic Capacity",
        "level": "All Levels",
        "environment": ["Gym", "Turf", "Court"],
        "duration": "15-18 min",
        "work_description": "Attach elastic band around waist (anchored laterally). Perform lateral shuffles 5-8m against resistance. Maintain low athletic stance. Reset, repeat. Switch direction after set.",
        "rest": "30 sec between reps, 2 min between sets",
        "sets": "4 sets of 6 reps per direction",
        "total_volume": "24 resisted lateral shuffles per side",
        "fatigue_score": 6,
        "progression": "Increase band resistance. Extend shuffle distance. Reduce rest to 25 sec. Add crossover steps.",
        "regression": "Reduce band resistance. Shorten distance. Reduce to 4 reps. Increase rest to 40 sec.",
        "tier": "A",
        "work_rest_ratio": "1:2",
        "sport_priority": {
            "cricket": "medium",
            "tennis": "high",
            "badminton": "high",
            "football": "high"
        },
        "movement_profile": ["lateral", "multi-directional"],
        "session_role": ["strength-endurance", "lateral-power"],
        "impact_level": "low",
        "eccentric_load": "moderate",
        "fatigue_cost": "moderate",
        "equipment_need": "resistance_bands",
        "field_space": "medium",
        "phase_timing": ["pre-season", "in-season"],
        "surface_preference": ["any firm surface"],
        "cricket_role_specific": None,
        "tennis_position": None,
        "badminton_position": None,
        "football_position": None,
        "energy_system_target": "glycolytic_capacity",
        "neuromuscular_demand": "high",
        "technical_complexity": "low",
        "injury_risk_consideration": "Hip/knee alignment. Avoid knee valgus. Progress resistance gradually.",
        "recovery_requirement": "48 hours",
        "metabolic_stress": "moderate",
        "created_phase": "phase2_targeted_expansion"
    },
    {
        "id": "AC-127",
        "name": "Multi-Directional Plyometric Circuit",
        "objective": "Develop reactive strength in all movement planes. Build elastic power and landing mechanics across forward, lateral, and rotational jumps.",
        "system": "ATP-PC System",
        "level": "Intermediate to Elite",
        "environment": ["Gym", "Turf", "Court"],
        "duration": "20-25 min",
        "work_description": "Circuit of 6 stations: (1) Box jumps, (2) Lateral hurdle hops, (3) Depth drops, (4) Rotational jump 180°, (5) Single-leg bounds, (6) Tuck jumps. 45 sec work, 45 sec transition.",
        "rest": "3 min between circuit rounds",
        "sets": "3-4 circuit rounds",
        "total_volume": "18-24 minutes of plyometric work",
        "fatigue_score": 6,
        "progression": "Increase box height. Add resistance. Reduce rest to 2 min. Add fifth station.",
        "regression": "Reduce box height. Remove depth drops initially. Increase rest to 4 min. Reduce to 2 rounds.",
        "tier": "A",
        "work_rest_ratio": "1:1",
        "sport_priority": {
            "cricket": "high",
            "tennis": "high",
            "badminton": "high",
            "football": "high"
        },
        "movement_profile": ["jumping", "multi-directional", "rotational", "lateral"],
        "session_role": ["plyometric-development", "elastic-power"],
        "impact_level": "very_high",
        "eccentric_load": "very_high",
        "fatigue_cost": "high",
        "equipment_need": "standard",
        "field_space": "medium",
        "phase_timing": ["pre-season", "early-in-season"],
        "surface_preference": ["sprung floor", "turf", "grass"],
        "cricket_role_specific": None,
        "tennis_position": None,
        "badminton_position": None,
        "football_position": None,
        "energy_system_target": "phosphagen_power",
        "neuromuscular_demand": "very_high",
        "technical_complexity": "high",
        "injury_risk_consideration": "Very high impact. Requires strong base. Monitor landing quality. Stop if form deteriorates.",
        "recovery_requirement": "72-96 hours",
        "metabolic_stress": "moderate",
        "created_phase": "phase2_targeted_expansion"
    },
    
    # ==================== ADDITIONAL CRITICAL GAPS ====================
    {
        "id": "AC-128",
        "name": "Cricket Fast Bowler — Pre-Delivery Stride Deceleration Training",
        "objective": "Develop eccentric strength and deceleration capacity for front leg planting. Reduce injury risk and improve force transfer through delivery stride.",
        "system": "ATP-PC System",
        "level": "Intermediate to Elite",
        "environment": ["Gym", "Turf", "Force Plate Area"],
        "duration": "15-18 min",
        "work_description": "Simulate delivery stride landing: step forward onto elevated platform (10-15cm), absorb landing on front leg, hold 2 sec, step back. Focus on knee tracking, hip control, trunk stability.",
        "rest": "30 sec between reps",
        "sets": "4 sets of 6 reps per leg",
        "total_volume": "24 controlled landings per leg",
        "fatigue_score": 4,
        "progression": "Increase platform height. Add light weight vest. Reduce rest to 25 sec. Increase to 8 reps.",
        "regression": "Reduce platform height. Reduce to 4 reps. Increase rest to 40 sec.",
        "tier": "A",
        "work_rest_ratio": "1:5",
        "sport_priority": {
            "cricket": "high",
            "tennis": "low",
            "badminton": "low",
            "football": "low"
        },
        "movement_profile": ["linear", "deceleration", "jumping"],
        "session_role": ["injury-prevention", "role-specific"],
        "impact_level": "moderate",
        "eccentric_load": "very_high",
        "fatigue_cost": "low",
        "equipment_need": "minimal",
        "field_space": "small",
        "phase_timing": ["pre-season", "in-season"],
        "surface_preference": ["any"],
        "cricket_role_specific": ["fast_bowler"],
        "tennis_position": None,
        "badminton_position": None,
        "football_position": None,
        "energy_system_target": "phosphagen_power",
        "neuromuscular_demand": "high",
        "technical_complexity": "high",
        "injury_risk_consideration": "Critical for fast bowler knee/back health. Front knee patellar tendon, lower back stress. Master technique before intensity.",
        "recovery_requirement": "48 hours",
        "metabolic_stress": "low",
        "created_phase": "phase2_targeted_expansion"
    },
    {
        "id": "AC-129",
        "name": "Tennis Serve Rotation Power — Overhead Medicine Ball Throws",
        "objective": "Develop explosive overhead rotation specific to serve motion. Build kinetic chain sequencing from legs through core to arm.",
        "system": "ATP-PC System",
        "level": "Intermediate to Elite",
        "environment": ["Gym", "Court", "Open Wall Area"],
        "duration": "15-18 min",
        "work_description": "Stand sideways to wall. Hold light med ball (2-4kg). Perform serve-like motion: leg drive, hip rotation, torso rotation, overhead throw against wall at upward angle. Catch, reset, repeat.",
        "rest": "30 sec between reps",
        "sets": "4 sets of 6 reps per side",
        "total_volume": "24 overhead rotational throws per side",
        "fatigue_score": 4,
        "progression": "Increase ball weight slightly. Increase throw velocity. Reduce rest to 25 sec. Increase to 8 reps.",
        "regression": "Reduce ball weight. Reduce to 4 reps. Increase rest to 40 sec.",
        "tier": "A",
        "work_rest_ratio": "1:4",
        "sport_priority": {
            "cricket": "medium",
            "tennis": "high",
            "badminton": "medium",
            "football": "low"
        },
        "movement_profile": ["rotational", "multi-directional"],
        "session_role": ["power-development", "sport-specific"],
        "impact_level": "low",
        "eccentric_load": "moderate",
        "fatigue_cost": "low",
        "equipment_need": "medicine_ball",
        "field_space": "small",
        "phase_timing": ["pre-season", "in-season"],
        "surface_preference": ["any"],
        "cricket_role_specific": None,
        "tennis_position": ["all_styles"],
        "badminton_position": None,
        "football_position": None,
        "energy_system_target": "phosphagen_power",
        "neuromuscular_demand": "high",
        "technical_complexity": "high",
        "injury_risk_consideration": "Shoulder rotator cuff, elbow UCL. Ensure proper warm-up. Do not overload too early.",
        "recovery_requirement": "48 hours",
        "metabolic_stress": "low",
        "created_phase": "phase2_targeted_expansion"
    },
    {
        "id": "AC-130",
        "name": "Badminton Jump Smash Repeat Power",
        "objective": "Develop repeat jump smash power endurance. Build ability to maintain vertical jump height and racket speed across multiple smashes in rally.",
        "system": "Anaerobic Capacity",
        "level": "Intermediate to Elite",
        "environment": ["Badminton Court", "Indoor Court"],
        "duration": "15-20 min",
        "work_description": "Start at back court. Perform jump smash motion (maximal vertical jump + overhead swing simulation). Land, immediate split-step, repeat. Focus on consistent jump height.",
        "rest": "20 sec between reps, 2 min between sets",
        "sets": "5 sets of 8 reps",
        "total_volume": "40 jump smashes",
        "fatigue_score": 6,
        "progression": "Add light racket. Reduce rest to 15 sec. Increase to 10 reps. Add actual shuttle feed.",
        "regression": "Reduce to 6 reps. Remove jump initially (just overhead reach). Increase rest to 30 sec.",
        "tier": "A",
        "work_rest_ratio": "1:2",
        "sport_priority": {
            "cricket": "low",
            "tennis": "low",
            "badminton": "high",
            "football": "low"
        },
        "movement_profile": ["jumping", "linear"],
        "session_role": ["sport-specific", "power-endurance"],
        "impact_level": "high",
        "eccentric_load": "very_high",
        "fatigue_cost": "high",
        "equipment_need": "minimal",
        "field_space": "small",
        "phase_timing": ["pre-season", "in-season"],
        "surface_preference": ["wooden floor", "synthetic court"],
        "cricket_role_specific": None,
        "tennis_position": None,
        "badminton_position": ["singles", "doubles"],
        "football_position": None,
        "energy_system_target": "glycolytic_power",
        "neuromuscular_demand": "very_high",
        "technical_complexity": "medium",
        "injury_risk_consideration": "Patellar tendon, Achilles, shoulder. High impact landing. Monitor jump height degradation as fatigue indicator.",
        "recovery_requirement": "48-72 hours",
        "metabolic_stress": "high",
        "created_phase": "phase2_targeted_expansion"
    },
    {
        "id": "AC-131",
        "name": "Football Goalkeeper — Dive Reaction & Recovery",
        "objective": "Develop explosive lateral diving power with rapid recovery. Train reactive decision-making and ground-to-standing speed.",
        "system": "ATP-PC System",
        "level": "All Levels",
        "environment": ["Goal Area", "Turf", "Grass", "Gym Mats"],
        "duration": "15-18 min",
        "work_description": "Start in ready stance at goal center. React to visual cue, dive laterally (simulate save), immediately pop up, sprint 5m forward, backpedal to start. Reset, repeat alternating sides.",
        "rest": "30-35 sec between reps (full recovery)",
        "sets": "5 sets of 5 reps",
        "total_volume": "25 dive-recovery sequences",
        "fatigue_score": 5,
        "progression": "Add actual ball save. Reduce rest to 25 sec. Increase to 6 reps. Add second dive before recovery.",
        "regression": "Remove sprint component (just dive and stand). Increase rest to 45 sec. Reduce to 4 reps.",
        "tier": "A",
        "work_rest_ratio": "1:5",
        "sport_priority": {
            "cricket": "low",
            "tennis": "low",
            "badminton": "low",
            "football": "high"
        },
        "movement_profile": ["lateral", "linear", "jumping"],
        "session_role": ["position-specific", "reactive-agility"],
        "impact_level": "high",
        "eccentric_load": "high",
        "fatigue_cost": "moderate",
        "equipment_need": "minimal",
        "field_space": "medium",
        "phase_timing": ["pre-season", "in-season"],
        "surface_preference": ["grass", "turf", "mats"],
        "cricket_role_specific": None,
        "tennis_position": None,
        "badminton_position": None,
        "football_position": ["goalkeeper"],
        "energy_system_target": "phosphagen_power",
        "neuromuscular_demand": "very_high",
        "technical_complexity": "medium",
        "injury_risk_consideration": "Shoulder, hip, rib impact. Ensure proper diving technique. Use mats initially if needed.",
        "recovery_requirement": "48-72 hours",
        "metabolic_stress": "low",
        "created_phase": "phase2_targeted_expansion"
    },
    {
        "id": "AC-132",
        "name": "Cricket Batter — Boundary Hit Rotational Power",
        "objective": "Develop explosive rotational power for boundary hitting. Build hip-shoulder separation and core-to-bat force transfer.",
        "system": "ATP-PC System",
        "level": "All Levels",
        "environment": ["Net Area", "Open Field", "Gym"],
        "duration": "15-18 min",
        "work_description": "Hold med ball (3-5kg) or training bat with resistance band. Assume batting stance. Explosive hip rotation through shot follow-through. Reset, repeat. Alternate front foot forward/back.",
        "rest": "30 sec between reps",
        "sets": "4 sets of 6 reps per side",
        "total_volume": "24 rotational power shots per side",
        "fatigue_score": 4,
        "progression": "Increase resistance. Add actual ball strike. Reduce rest to 25 sec. Increase to 8 reps.",
        "regression": "Reduce resistance. Reduce to 4 reps. Increase rest to 40 sec.",
        "tier": "A",
        "work_rest_ratio": "1:4",
        "sport_priority": {
            "cricket": "high",
            "tennis": "low",
            "badminton": "low",
            "football": "low"
        },
        "movement_profile": ["rotational", "multi-directional"],
        "session_role": ["power-development", "role-specific"],
        "impact_level": "low",
        "eccentric_load": "moderate",
        "fatigue_cost": "low",
        "equipment_need": "medicine_ball",
        "field_space": "small",
        "phase_timing": ["pre-season", "in-season"],
        "surface_preference": ["any"],
        "cricket_role_specific": ["batter"],
        "tennis_position": None,
        "badminton_position": None,
        "football_position": None,
        "energy_system_target": "phosphagen_power",
        "neuromuscular_demand": "high",
        "technical_complexity": "medium",
        "injury_risk_consideration": "Lower back rotation, oblique strain, wrist/elbow. Ensure proper warm-up.",
        "recovery_requirement": "48 hours",
        "metabolic_stress": "low",
        "created_phase": "phase2_targeted_expansion"
    },
    {
        "id": "AC-133",
        "name": "Football Cornerback — Backpedal to Break Drill",
        "objective": "Develop backpedal speed and hip transition explosiveness. Train ability to mirror receiver then break on ball instantly.",
        "system": "ATP-PC System",
        "level": "Intermediate to Elite",
        "environment": ["Football Field", "Turf"],
        "duration": "15-18 min",
        "work_description": "Backpedal 10m in defensive stance. On cue (visual/verbal), open hips and explode laterally 5m OR forward sprint 10m. Randomize direction. Reset to start.",
        "rest": "30 sec between reps",
        "sets": "5 sets of 6 reps",
        "total_volume": "30 backpedal-transition sequences",
        "fatigue_score": 5,
        "progression": "Add route simulation by partner. Reduce rest to 25 sec. Increase to 8 reps. Add ball interception.",
        "regression": "Pre-announce direction. Increase rest to 40 sec. Reduce to 4 reps.",
        "tier": "A",
        "work_rest_ratio": "1:5",
        "sport_priority": {
            "cricket": "low",
            "tennis": "low",
            "badminton": "low",
            "football": "high"
        },
        "movement_profile": ["linear", "lateral", "cod", "acceleration", "deceleration"],
        "session_role": ["position-specific", "reactive-agility"],
        "impact_level": "moderate",
        "eccentric_load": "high",
        "fatigue_cost": "moderate",
        "equipment_need": "none",
        "field_space": "medium",
        "phase_timing": ["pre-season", "in-season"],
        "surface_preference": ["turf", "grass"],
        "cricket_role_specific": None,
        "tennis_position": None,
        "badminton_position": None,
        "football_position": ["cornerback", "safety", "defensive_back"],
        "energy_system_target": "phosphagen_power",
        "neuromuscular_demand": "very_high",
        "technical_complexity": "high",
        "injury_risk_consideration": "Hip flexor, groin, knee ACL/MCL. Hip mobility crucial. Proper backpedal mechanics essential.",
        "recovery_requirement": "48-72 hours",
        "metabolic_stress": "low",
        "created_phase": "phase2_targeted_expansion"
    },
    {
        "id": "AC-134",
        "name": "Tennis Baseline Rally — Change of Direction Endurance",
        "objective": "Build endurance for extended baseline rallies with frequent direction changes. Develop ability to maintain shot quality under metabolic stress.",
        "system": "Anaerobic Capacity",
        "level": "All Levels",
        "environment": ["Tennis Court", "Baseline Area"],
        "duration": "20-25 min",
        "work_description": "Start at center baseline. Shuffle to forehand corner (2m), touch line, shuffle through center to backhand corner (4m), touch, return to center. Continuous motion simulating rally movement.",
        "rest": "15 sec between reps, 90 sec between sets",
        "sets": "5 sets of 8 reps",
        "total_volume": "40 baseline direction changes",
        "fatigue_score": 6,
        "progression": "Add shadow swing at each corner. Reduce rest to 12 sec. Increase to 10 reps. Extend court width coverage.",
        "regression": "Reduce to 6 reps. Increase rest to 20 sec. Walk recovery.",
        "tier": "A",
        "work_rest_ratio": "1:1",
        "sport_priority": {
            "cricket": "low",
            "tennis": "high",
            "badminton": "medium",
            "football": "low"
        },
        "movement_profile": ["lateral", "multi-directional"],
        "session_role": ["sport-specific", "rally-endurance"],
        "impact_level": "moderate",
        "eccentric_load": "high",
        "fatigue_cost": "high",
        "equipment_need": "minimal",
        "field_space": "medium",
        "phase_timing": ["pre-season", "in-season"],
        "surface_preference": ["any court surface"],
        "cricket_role_specific": None,
        "tennis_position": ["baseline_player"],
        "badminton_position": None,
        "football_position": None,
        "energy_system_target": "glycolytic_capacity",
        "neuromuscular_demand": "high",
        "technical_complexity": "low",
        "injury_risk_consideration": "Hip adductor, ankle stability. Lateral knee stress. Proper footwork mechanics.",
        "recovery_requirement": "48 hours",
        "metabolic_stress": "high",
        "created_phase": "phase2_targeted_expansion"
    },
    {
        "id": "AC-135",
        "name": "Integrated Sport-Specific Circuit — Multi-Sport General Prep",
        "objective": "Provide general physical preparation applicable across cricket, tennis, badminton, and football. Build work capacity, movement literacy, and metabolic flexibility.",
        "system": "Aerobic Power",
        "level": "All Levels",
        "environment": ["Gym", "Field", "Multi-Purpose Area"],
        "duration": "25-30 min",
        "work_description": "Circuit of 8 stations (45 sec work, 15 sec transition): (1) Battle ropes, (2) Box step-ups, (3) KB swings, (4) Plank walk, (5) Med ball slams, (6) Jump rope, (7) Farmer carry, (8) Burpees. Continuous flow.",
        "rest": "3 min between circuit rounds",
        "sets": "3-4 rounds",
        "total_volume": "24-32 minutes of mixed modal work",
        "fatigue_score": 6,
        "progression": "Increase work time to 50 sec. Reduce rest to 2 min. Add fifth round. Increase intensity.",
        "regression": "Reduce work time to 30 sec. Increase rest to 4 min. Reduce to 2 rounds. Modify exercises.",
        "tier": "B",
        "work_rest_ratio": "3:1",
        "sport_priority": {
            "cricket": "medium",
            "tennis": "medium",
            "badminton": "medium",
            "football": "medium"
        },
        "movement_profile": ["multi-directional", "linear", "rotational"],
        "session_role": ["general-prep", "conditioning-base"],
        "impact_level": "moderate",
        "eccentric_load": "moderate",
        "fatigue_cost": "high",
        "equipment_need": "standard",
        "field_space": "medium",
        "phase_timing": ["off-season", "pre-season"],
        "surface_preference": ["any"],
        "cricket_role_specific": None,
        "tennis_position": None,
        "badminton_position": None,
        "football_position": None,
        "energy_system_target": "oxidative_power",
        "neuromuscular_demand": "moderate",
        "technical_complexity": "medium",
        "injury_risk_consideration": "General fatigue management. Scale exercises appropriately. Monitor form breakdown.",
        "recovery_requirement": "48 hours",
        "metabolic_stress": "high",
        "created_phase": "phase2_targeted_expansion"
    }
]

# Combine existing and new protocols
all_protocols = existing_protocols + new_protocols

# Save enriched dataset
output_file = 'enriched_conditioning_data_phase2_targeted.json'
with open(output_file, 'w') as f:
    json.dump(all_protocols, f, indent=2, ensure_ascii=False)

# Generate summary report
print("=" * 80)
print("PHASE 2: TARGETED CONDITIONING EXPANSION - COMPLETE")
print("=" * 80)
print(f"\nOriginal protocols: {len(existing_protocols)}")
print(f"New protocols added: {len(new_protocols)}")
print(f"Total protocols: {len(all_protocols)}")
print(f"\nExpansion breakdown:")
print(f"  - Cricket role-specific: 6 protocols (fast bowler, spinner, batter, wicketkeeper)")
print(f"  - Tennis/Badminton lateral: 5 protocols")
print(f"  - Football position-specific: 6 protocols")
print(f"  - Equipment-varied: 6 protocols")
print(f"  - Advanced movement profiles: 5 protocols")
print(f"  - Additional critical gaps: 5 protocols")

# Analyze improvements
print("\n" + "=" * 80)
print("COVERAGE IMPROVEMENTS")
print("=" * 80)

# Movement profile distribution
profiles = {}
for p in all_protocols:
    for mp in p.get('movement_profile', []):
        profiles[mp] = profiles.get(mp, 0) + 1

print("\nMovement Profile Distribution:")
for profile, count in sorted(profiles.items(), key=lambda x: x[1], reverse=True):
    print(f"  {profile}: {count} protocols ({count/len(all_protocols)*100:.1f}%)")

# Equipment variety
equip = {}
for p in all_protocols:
    eq = p.get('equipment_need', 'none')
    equip[eq] = equip.get(eq, 0) + 1

print("\nEquipment Distribution:")
for eq, count in sorted(equip.items(), key=lambda x: x[1], reverse=True):
    print(f"  {eq}: {count} protocols")

# Sport-specific role coverage
print("\nRole-Specific Protocol Counts:")
cricket_roles = ['fast_bowler', 'spinner', 'batter', 'wicketkeeper']
for role in cricket_roles:
    count = sum(1 for p in all_protocols if p.get('cricket_role_specific') and role in p['cricket_role_specific'])
    print(f"  Cricket - {role.replace('_', ' ').title()}: {count} protocols")

football_positions = ['wide_receiver', 'midfielder', 'center_back', 'striker', 'goalkeeper', 'cornerback']
for pos in football_positions:
    count = sum(1 for p in all_protocols if p.get('football_position') and pos in p['football_position'])
    print(f"  Football - {pos.replace('_', ' ').title()}: {count} protocols")

tennis_count = sum(1 for p in all_protocols if p.get('tennis_position'))
badminton_count = sum(1 for p in all_protocols if p.get('badminton_position'))
print(f"  Tennis-specific: {tennis_count} protocols")
print(f"  Badminton-specific: {badminton_count} protocols")

print("\n" + "=" * 80)
print(f"Output saved to: {output_file}")
print("=" * 80)
