import json

# Load existing exercises
with open('forge_web/src/data/exercises.json', 'r') as f:
    exercises = json.load(f)

# Count by category before
print("Before adding:")
cats_before = {}
for e in exercises:
    cat = e['category']
    cats_before[cat] = cats_before.get(cat, 0) + 1

for cat in ['DLKD', 'DLHD', 'SLKD', 'SLHD']:
    print(f"  {cat}: {cats_before.get(cat, 0)} exercises")

# New exercises to add (33 total)
new_exercises = [
    # DLKD - Add 6 exercises (14 -> 20)
    {"id": "DLKD-015", "name": "Front Squat", "category": "DLKD", "subcategory": "STR", "movement_pattern": "DLKD", "equipment": "Barbell, Rack", "difficulty": "Advanced", "source_organization": "NSCA", "description": "", "coaching_cues": ["Elbows high, chest proud throughout movement", "Core braced, torso upright", "Knees track over toes", "Depth to at least parallel"], "common_errors": ["Elbows dropping during descent", "Excessive forward lean", "Knee valgus", "Heels lifting off ground"], "contraindications": ["Limited shoulder mobility", "Wrist injuries", "Acute knee pathology"], "regressions": ["Goblet Squat", "Box Squat"], "progressions": ["Overhead Squat", "Tempo Front Squat"], "equipment_alternatives": ["Safety squat bar", "Cambered bar", "Dumbbells"], "is_pain_safe": False, "created_at": "2024-01-01T00:00:00Z"},
    {"id": "DLKD-016", "name": "Overhead Squat", "category": "DLKD", "subcategory": "STR", "movement_pattern": "DLKD", "equipment": "Barbell, Rack", "difficulty": "Elite", "source_organization": "USAW", "description": "", "coaching_cues": ["Arms locked out, bar over mid-foot", "Shoulders active and stable", "Chest tall, core braced", "Full depth with control"], "common_errors": ["Bar drifting forward", "Elbows bending", "Limited ankle dorsiflexion", "Thoracic spine rounding"], "contraindications": ["Shoulder instability", "Limited thoracic mobility", "Wrist injuries"], "regressions": ["Front Squat", "PVC Pipe OHS"], "progressions": ["Snatch Balance", "Tempo OHS"], "equipment_alternatives": ["Dumbbells", "Kettlebell", "Band"], "is_pain_safe": False, "created_at": "2024-01-01T00:00:00Z"},
    {"id": "DLKD-017", "name": "Belt Squat", "category": "DLKD", "subcategory": "STR", "movement_pattern": "DLKD", "equipment": "Belt Squat Machine", "difficulty": "Intermediate", "source_organization": "Westside", "description": "", "coaching_cues": ["Keep torso upright, no leaning", "Push through full foot", "Control the descent", "Full range of motion"], "common_errors": ["Leaning forward excessively", "Partial ROM", "Knees caving inward"], "contraindications": ["Hip impingement", "Knee instability"], "regressions": ["Bodyweight Squat", "Box Squat"], "progressions": ["Paused Belt Squat", "Heavy Belt Squat"], "equipment_alternatives": ["Band belt squat", "DB held between legs"], "is_pain_safe": True, "created_at": "2024-01-01T00:00:00Z"},
    {"id": "DLKD-018", "name": "Zercher Squat", "category": "DLKD", "subcategory": "STR", "movement_pattern": "DLKD", "equipment": "Barbell, Rack", "difficulty": "Advanced", "source_organization": "Strongman Corp", "description": "", "coaching_cues": ["Bar in elbow creases, hands clasped", "Core tight, chest up", "Sit back slightly", "Drive through midfoot"], "common_errors": ["Bar rolling down arms", "Excessive forward lean", "Rounding upper back"], "contraindications": ["Elbow injuries", "Lower back issues"], "regressions": ["Goblet Squat", "Front Squat"], "progressions": ["Zercher Good Morning", "Walking Zercher"], "equipment_alternatives": ["Safety squat bar", "Cambered bar"], "is_pain_safe": False, "created_at": "2024-01-01T00:00:00Z"},
    {"id": "DLKD-019", "name": "Anderson Squat", "category": "DLKD", "subcategory": "STR", "movement_pattern": "DLKD", "equipment": "Barbell, Rack", "difficulty": "Advanced", "source_organization": "Westside", "description": "", "coaching_cues": ["Start from dead stop at bottom", "Stay tight in the hole", "Drive up explosively", "Maintain upright torso"], "common_errors": ["Losing tension at bottom", "Shooting hips up first", "Incomplete depth"], "contraindications": ["Acute knee injuries", "Hip impingement"], "regressions": ["Box Squat", "Paused Squat"], "progressions": ["Heavy Anderson Squat", "Band Anderson Squat"], "equipment_alternatives": ["Safety squat bar", "Trap bar"], "is_pain_safe": False, "created_at": "2024-01-01T00:00:00Z"},
    {"id": "DLKD-020", "name": "Spanish Squat", "category": "DLKD", "subcategory": "STAB", "movement_pattern": "DLKD", "equipment": "Band, Anchor Point", "difficulty": "Intermediate", "source_organization": "UEFA Medical", "description": "", "coaching_cues": ["Band behind knees, anchored", "Shins vertical throughout", "Sit back, keep heels down", "Quad dominant movement"], "common_errors": ["Knees drifting forward", "Heels lifting", "Excessive forward lean"], "contraindications": ["Patellar tendinopathy (acute)", "Knee instability"], "regressions": ["Wall Sit", "Bodyweight Squat"], "progressions": ["Weighted Spanish Squat", "Single-Leg Spanish Squat"], "equipment_alternatives": ["Squat wedge", "Slant board"], "is_pain_safe": True, "created_at": "2024-01-01T00:00:00Z"},
    # DLHD - Add 6 exercises (19 -> 25)
    {"id": "DLHD-020", "name": "Good Morning", "category": "DLHD", "subcategory": "STR", "movement_pattern": "DLHD", "equipment": "Barbell, Rack", "difficulty": "Advanced", "source_organization": "NSCA", "description": "", "coaching_cues": ["Soft knees, hinge at hips", "Bar stays over mid-foot", "Neutral spine throughout", "Feel stretch in hamstrings"], "common_errors": ["Rounding lower back", "Bending knees too much", "Bar drifting forward", "Not hitting full stretch"], "contraindications": ["Lower back injuries", "Hamstring strains (acute)"], "regressions": ["Bodyweight Hip Hinge", "45° Back Extension"], "progressions": ["Weighted Good Morning", "Single-Leg Good Morning"], "equipment_alternatives": ["Safety squat bar", "Band resistance"], "is_pain_safe": False, "created_at": "2024-01-01T00:00:00Z"},
    {"id": "DLHD-021", "name": "Pull-Through", "category": "DLHD", "subcategory": "PWR", "movement_pattern": "DLHD", "equipment": "Kettlebell, Band", "difficulty": "Intermediate", "source_organization": "EXOS", "description": "", "coaching_cues": ["Hinge back, reach between legs", "Snap hips forward explosively", "Stand tall at top", "Control the return"], "common_errors": ["Squatting instead of hinging", "Using arms to pull", "Hyperextending at top", "Rounding back"], "contraindications": ["Lower back issues", "Hip impingement"], "regressions": ["KB Deadlift", "Hip Hinge Drill"], "progressions": ["Heavy Pull-Through", "Band Pull-Through"], "equipment_alternatives": ["DB", "Medicine ball", "Cable"], "is_pain_safe": False, "created_at": "2024-01-01T00:00:00Z"},
    {"id": "DLHD-022", "name": "Seated Good Morning", "category": "DLHD", "subcategory": "STR", "movement_pattern": "DLHD", "equipment": "Barbell, Bench", "difficulty": "Advanced", "source_organization": "Westside", "description": "", "coaching_cues": ["Sit tall on bench edge", "Hinge forward with control", "Keep chest up", "Return to upright position"], "common_errors": ["Rounding spine", "Slouching at start", "Limited ROM", "Using momentum"], "contraindications": ["Lower back injuries", "Hip mobility restrictions"], "regressions": ["Bodyweight Seated Hinge", "45° Back Extension"], "progressions": ["Band Seated Good Morning", "Heavy Seated GM"], "equipment_alternatives": ["DB on chest", "Band around neck"], "is_pain_safe": False, "created_at": "2024-01-01T00:00:00Z"},
    {"id": "DLHD-023", "name": "Reverse Hyperextension", "category": "DLHD", "subcategory": "STR", "movement_pattern": "DLHD", "equipment": "Reverse Hyper Machine", "difficulty": "Intermediate", "source_organization": "Westside", "description": "", "coaching_cues": ["Lie face down, grip handles", "Lift legs with hip extension", "Squeeze glutes at top", "Lower with control"], "common_errors": ["Using lower back instead of hips", "Swinging legs", "Incomplete ROM", "Arching lower back"], "contraindications": ["Acute lower back pain", "Hip injuries"], "regressions": ["Prone Hip Extension", "Glute Bridge"], "progressions": ["Weighted Reverse Hyper", "Band Reverse Hyper"], "equipment_alternatives": ["Stability ball", "Bench (manual resistance)"], "is_pain_safe": True, "created_at": "2024-01-01T00:00:00Z"},
    {"id": "DLHD-024", "name": "Cable Pull-Through", "category": "DLHD", "subcategory": "PWR", "movement_pattern": "DLHD", "equipment": "Cable Machine, Rope", "difficulty": "Intermediate", "source_organization": "EXOS", "description": "", "coaching_cues": ["Face away from machine", "Hinge back, rope between legs", "Explosive hip snap", "Stand tall, squeeze glutes"], "common_errors": ["Pulling with arms", "Squatting motion", "Not hinging back enough", "Hyperextending lumbar"], "contraindications": ["Lower back issues", "Hip impingement"], "regressions": ["Bodyweight Hip Hinge", "KB Deadlift"], "progressions": ["Heavy Cable Pull-Through", "Single-Leg Variation"], "equipment_alternatives": ["Band", "Kettlebell"], "is_pain_safe": False, "created_at": "2024-01-01T00:00:00Z"},
    {"id": "DLHD-025", "name": "Jefferson Curl", "category": "DLHD", "subcategory": "MOB", "movement_pattern": "DLHD", "equipment": "DB/KB, Box", "difficulty": "Advanced", "source_organization": "ALTIS", "description": "", "coaching_cues": ["Stand on elevated surface", "Tuck chin, roll down vertebrae by vertebrae", "Light weight, slow tempo", "Roll back up with control"], "common_errors": ["Using too much weight", "Moving too fast", "Not articulating spine", "Holding breath"], "contraindications": ["Acute disc issues", "Severe osteoporosis"], "regressions": ["Bodyweight Jefferson Curl", "Cat-Cow Stretch"], "progressions": ["Weighted Jefferson Curl", "Tempo Variations"], "equipment_alternatives": ["Barbell", "Landmine"], "is_pain_safe": False, "created_at": "2024-01-01T00:00:00Z"},
    # SLKD - Add 9 exercises (16 -> 25)
    {"id": "SLKD-017", "name": "Curtsy Lunge", "category": "SLKD", "subcategory": "STR", "movement_pattern": "SLKD", "equipment": "DB/Bodyweight", "difficulty": "Intermediate", "source_organization": "NSCA", "description": "", "coaching_cues": ["Step back and across", "Lower until thigh is parallel", "Keep front knee tracking over toe", "Push back to start"], "common_errors": ["Knee collapsing inward", "Leaning too far forward", "Incomplete depth", "Foot placement too narrow"], "contraindications": ["Knee instability", "Hip impingement"], "regressions": ["Stationary Lunge", "Assisted Split Squat"], "progressions": ["Weighted Curtsy Lunge", "Jump Curtsy"], "equipment_alternatives": ["Barbell", "KB", "Band"], "is_pain_safe": False, "created_at": "2024-01-01T00:00:00Z"},
    {"id": "SLKD-018", "name": "Cossack Squat", "category": "SLKD", "subcategory": "MOB", "movement_pattern": "SLKD", "equipment": "Bodyweight/KB", "difficulty": "Advanced", "source_organization": "StrongFirst", "description": "", "coaching_cues": ["Wide stance, shift to one side", "Bend one knee, keep other leg straight", "Heel stays down on working leg", "Alternate sides smoothly"], "common_errors": ["Heel lifting off ground", "Rounding back", "Limited depth", "Knee valgus"], "contraindications": ["Adductor strains", "Knee injuries"], "regressions": ["Side Lunge", "Goblet Cossack"], "progressions": ["Weighted Cossack", "Pistol Progression"], "equipment_alternatives": ["Band assistance", "TRX"], "is_pain_safe": False, "created_at": "2024-01-01T00:00:00Z"},
    {"id": "SLKD-019", "name": "Skater Squat", "category": "SLKD", "subcategory": "STR", "movement_pattern": "SLKD", "equipment": "Bodyweight/Bench", "difficulty": "Advanced", "source_organization": "Gymnastics", "description": "", "coaching_cues": ["Stand on one leg, other foot on bench behind", "Lower into lunge position", "Keep torso upright", "Drive through front heel"], "common_errors": ["Front knee caving in", "Leaning too far forward", "Back knee hitting ground hard", "Incomplete ROM"], "contraindications": ["Knee instability", "Ankle mobility issues"], "regressions": ["Split Squat", "Assisted Skater"], "progressions": ["Weighted Skater", "Elevated Skater"], "equipment_alternatives": ["DB", "KB", "Band"], "is_pain_safe": False, "created_at": "2024-01-01T00:00:00Z"},
    {"id": "SLKD-020", "name": "Peterson Step-Up", "category": "SLKD", "subcategory": "REHAB", "movement_pattern": "SLKD", "equipment": "Low Box, Band", "difficulty": "Beginner", "source_organization": "UEFA Medical", "description": "", "coaching_cues": ["Light band pulling knee inward", "Step up focusing on knee tracking", "Control the descent", "Feel VMO activation"], "common_errors": ["Knee valgus", "Pushing off back foot", "Too much height", "Rushing the movement"], "contraindications": ["Acute knee injury"], "regressions": ["Mini Squat", "Wall Sit"], "progressions": ["Higher Box", "Unweighted Step-Up"], "equipment_alternatives": ["Band only", "No equipment"], "is_pain_safe": True, "created_at": "2024-01-01T00:00:00Z"},
    {"id": "SLKD-021", "name": "Forward Lunge", "category": "SLKD", "subcategory": "STR", "movement_pattern": "SLKD", "equipment": "DB/Barbell", "difficulty": "Intermediate", "source_organization": "NSCA", "description": "", "coaching_cues": ["Step forward with control", "Lower until both knees at 90°", "Keep torso upright", "Push off front foot to return"], "common_errors": ["Stepping too short", "Front knee past toes excessively", "Back knee slamming ground", "Leaning forward"], "contraindications": ["Knee injuries", "Balance issues"], "regressions": ["Split Squat", "Assisted Lunge"], "progressions": ["Walking Lunge", "Jump Lunge"], "equipment_alternatives": ["KB", "Barbell", "Bodyweight"], "is_pain_safe": False, "created_at": "2024-01-01T00:00:00Z"},
    {"id": "SLKD-022", "name": "Shrimp Squat", "category": "SLKD", "subcategory": "STR", "movement_pattern": "SLKD", "equipment": "Bodyweight", "difficulty": "Elite", "source_organization": "Gymnastics", "description": "", "coaching_cues": ["Hold back foot with opposite hand", "Lower on standing leg", "Touch knee to ground lightly", "Drive back up"], "common_errors": ["Losing balance", "Knee valgus", "Incomplete depth", "Relying on arm pull"], "contraindications": ["Knee instability", "Poor balance"], "regressions": ["Pistol Squat", "Assisted Shrimp"], "progressions": ["Weighted Shrimp", "Free Shrimp (no hand)"], "equipment_alternatives": ["TRX assistance", "Wall touch"], "is_pain_safe": False, "created_at": "2024-01-01T00:00:00Z"},
    {"id": "SLKD-023", "name": "Clock Lunge", "category": "SLKD", "subcategory": "STAB", "movement_pattern": "SLKD", "equipment": "Bodyweight/DB", "difficulty": "Advanced", "source_organization": "EXOS", "description": "", "coaching_cues": ["Imagine clock face on ground", "Lunge in multiple directions", "Maintain single-leg stability", "Control each rep"], "common_errors": ["Losing balance between reps", "Inconsistent step length", "Knee tracking issues", "Rushing through positions"], "contraindications": ["Ankle instability", "Knee injuries"], "regressions": ["Split Squat", "Single-Leg Balance"], "progressions": ["Weighted Clock Lunge", "Reactive Clock Lunge"], "equipment_alternatives": ["KB", "Band", "Medicine ball"], "is_pain_safe": False, "created_at": "2024-01-01T00:00:00Z"},
    {"id": "SLKD-024", "name": "Plyo Step-Up", "category": "SLKD", "subcategory": "PWR", "movement_pattern": "SLKD", "equipment": "Box, DB", "difficulty": "Advanced", "source_organization": "NSCA", "description": "", "coaching_cues": ["Explosive drive through front leg", "Leave box briefly at top", "Land softly back on box", "Maintain control throughout"], "common_errors": ["Pushing off ground with back foot", "Landing too hard", "Box too high", "Knee valgus on landing"], "contraindications": ["Knee injuries", "Achilles issues"], "regressions": ["Regular Step-Up", "Low Box Step-Up"], "progressions": ["Higher Box", "Weighted Plyo Step-Up"], "equipment_alternatives": ["Bench", "Platform"], "is_pain_safe": False, "created_at": "2024-01-01T00:00:00Z"},
    {"id": "SLKD-025", "name": "Rear Foot Elevated Split Squat (KB)", "category": "SLKD", "subcategory": "STR", "movement_pattern": "SLKD", "equipment": "KB, Bench", "difficulty": "Intermediate", "source_organization": "StrongFirst", "description": "", "coaching_cues": ["Back foot on bench, front foot forward", "Lower until back knee nearly touches", "Keep torso upright", "Drive through front heel"], "common_errors": ["Front foot too close", "Leaning forward excessively", "Back knee slamming down", "Front knee caving in"], "contraindications": ["Knee instability", "Hip flexor strain"], "regressions": ["Split Squat", "Assisted BSS"], "progressions": ["Double KB BSS", "Elevated BSS"], "equipment_alternatives": ["DB", "Barbell", "Band"], "is_pain_safe": False, "created_at": "2024-01-01T00:00:00Z"},
    # SLHD - Add 12 exercises (13 -> 25)
    {"id": "SLHD-014", "name": "Single-Leg Hip Thrust (Bodyweight)", "category": "SLHD", "subcategory": "STR", "movement_pattern": "SLHD", "equipment": "Bench", "difficulty": "Intermediate", "source_organization": "NSCA", "description": "", "coaching_cues": ["Upper back on bench, one foot on ground", "Drive through planted foot", "Squeeze glute at top", "Lower with control"], "common_errors": ["Hyperextending lower back", "Not hitting full extension", "Neck craning", "Hips sagging"], "contraindications": ["Lower back issues", "Hip injuries"], "regressions": ["Double-Leg Glute Bridge", "Single-Leg Glute Bridge"], "progressions": ["Weighted SL Hip Thrust", "Elevated SL Hip Thrust"], "equipment_alternatives": ["Floor", "Stability ball"], "is_pain_safe": False, "created_at": "2024-01-01T00:00:00Z"},
    {"id": "SLHD-015", "name": "Single-Leg Back Extension", "category": "SLHD", "subcategory": "STR", "movement_pattern": "SLHD", "equipment": "Hyperextension Bench", "difficulty": "Advanced", "source_organization": "StrongFirst", "description": "", "coaching_cues": ["One foot on platform, other leg extended", "Hinge at hips, lower torso", "Squeeze glute to return", "Keep working leg straight"], "common_errors": ["Using lower back instead of hip", "Rounding spine", "Incomplete ROM", "Working leg bending"], "contraindications": ["Lower back injuries", "Hip impingement"], "regressions": ["Double-Leg Back Extension", "45° Back Extension"], "progressions": ["Weighted SL Back Extension", "Band Resistance"], "equipment_alternatives": ["Roman chair", "Stability ball"], "is_pain_safe": False, "created_at": "2024-01-01T00:00:00Z"},
    {"id": "SLHD-016", "name": "Single-Leg Kettlebell Deadlift", "category": "SLHD", "subcategory": "STR", "movement_pattern": "SLHD", "equipment": "Kettlebell", "difficulty": "Intermediate", "source_organization": "StrongFirst", "description": "", "coaching_cues": ["Stand on one leg, KB in opposite hand", "Hinge at hip, KB travels down leg", "Keep hips square", "Return to standing"], "common_errors": ["Hips rotating open", "Rounding back", "Losing balance", "Knee bending too much"], "contraindications": ["Lower back issues", "Balance disorders"], "regressions": ["Split Stance RDL", "Two-Leg KB RDL"], "progressions": ["Heavy SL RDL", "Double KB SL RDL"], "equipment_alternatives": ["DB", "Barbell (one hand)"], "is_pain_safe": False, "created_at": "2024-01-01T00:00:00Z"},
    {"id": "SLHD-017", "name": "Single-Leg Glute Bridge (Band)", "category": "SLHD", "subcategory": "ACT", "movement_pattern": "SLHD", "equipment": "Band, Floor", "difficulty": "Beginner", "source_organization": "UEFA Medical", "description": "", "coaching_cues": ["Band above knees for abduction cue", "One foot on ground, other extended", "Drive through heel", "Squeeze glute hard at top"], "common_errors": ["Knee valgus despite band", "Hip hiking", "Lower back arching", "Not full extension"], "contraindications": ["Acute hip/knee injury"], "regressions": ["Double-Leg Glute Bridge", "Isometric Hold"], "progressions": ["Single-Leg Bridge (no band)", "Elevated SL Bridge"], "equipment_alternatives": ["Mini-band", "No band"], "is_pain_safe": True, "created_at": "2024-01-01T00:00:00Z"},
    {"id": "SLHD-018", "name": "Single-Leg Romanian Deadlift (Barbell)", "category": "SLHD", "subcategory": "STR", "movement_pattern": "SLHD", "equipment": "Barbell", "difficulty": "Elite", "source_organization": "Westside", "description": "", "coaching_cues": ["Bar in both hands, stand on one leg", "Hinge back, bar close to body", "Feel hamstring stretch", "Drive hips forward to return"], "common_errors": ["Bar drifting away", "Hips opening up", "Rounding thoracic spine", "Standing leg bending"], "contraindications": ["Lower back injuries", "Severe hamstring issues"], "regressions": ["SL RDL (DB)", "Split Stance RDL"], "progressions": ["Heavy Barbell SL RDL", "Deficit SL RDL"], "equipment_alternatives": ["Trap bar", "Axle bar"], "is_pain_safe": False, "created_at": "2024-01-01T00:00:00Z"},
    {"id": "SLHD-019", "name": "Single-Leg Cable Pull-Through", "category": "SLHD", "subcategory": "PWR", "movement_pattern": "SLHD", "equipment": "Cable Machine", "difficulty": "Advanced", "source_organization": "EXOS", "description": "", "coaching_cues": ["Stand on one leg, cable between legs", "Hinge back on single leg", "Explosive hip extension", "Control the eccentric"], "common_errors": ["Losing balance", "Using arm to pull", "Hips rotating", "Incomplete hinge"], "contraindications": ["Ankle instability", "Hip injuries"], "regressions": ["Two-Leg Cable Pull-Through", "Split Stance Variation"], "progressions": ["Heavier Load", "Unstable Surface"], "equipment_alternatives": ["Band", "KB"], "is_pain_safe": False, "created_at": "2024-01-01T00:00:00Z"},
    {"id": "SLHD-020", "name": "Single-Leg Swiss Ball Hamstring Curl", "category": "SLHD", "subcategory": "STR", "movement_pattern": "SLHD", "equipment": "Stability Ball", "difficulty": "Advanced", "source_organization": "EXOS", "description": "", "coaching_cues": ["One foot on ball, hips lifted", "Curl ball toward glutes", "Keep hips elevated throughout", "Extend with control"], "common_errors": ["Hips dropping", "Ball rolling off", "Using lower back", "Incomplete curl"], "contraindications": ["Lower back issues", "Hamstring strains (acute)"], "regressions": ["Double-Leg Ball Curl", "Slider Curl"], "progressions": ["Single-Leg Eccentric", "Weighted Variation"], "equipment_alternatives": ["Sliders", "Nordic setup"], "is_pain_safe": False, "created_at": "2024-01-01T00:00:00Z"},
    {"id": "SLHD-021", "name": "Single-Leg 45° Back Extension", "category": "SLHD", "subcategory": "STR", "movement_pattern": "SLHD", "equipment": "Hyperextension Bench", "difficulty": "Intermediate", "source_organization": "NSCA", "description": "", "coaching_cues": ["One foot on platform, other leg back", "Lower torso with control", "Extend using glutes and hamstrings", "Keep non-working leg straight"], "common_errors": ["Using lower back exclusively", "Working leg bending", "Incomplete ROM", "Jerky movement"], "contraindications": ["Lower back injuries"], "regressions": ["Double-Leg 45° Extension", "Isometric Hold"], "progressions": ["Weighted SL Extension", "Band Resistance"], "equipment_alternatives": ["Roman chair", "Floor prone extension"], "is_pain_safe": False, "created_at": "2024-01-01T00:00:00Z"},
    {"id": "SLHD-022", "name": "Single-Leg Trap Bar Deadlift", "category": "SLHD", "subcategory": "STR", "movement_pattern": "SLHD", "equipment": "Trap Bar", "difficulty": "Advanced", "source_organization": "StrongFirst", "description": "", "coaching_cues": ["Stand on one leg in trap bar", "Hinge back, grip handles", "Drive through planted foot", "Stand tall, squeeze glute"], "common_errors": ["Losing balance", "Hips rotating", "Rounding back", "Not full lockout"], "contraindications": ["Lower back issues", "Knee instability"], "regressions": ["Split Stance Trap Bar DL", "Two-Leg Trap Bar DL"], "progressions": ["Heavy SL Trap Bar", "Deficit Variation"], "equipment_alternatives": ["DB", "KB"], "is_pain_safe": False, "created_at": "2024-01-01T00:00:00Z"},
    {"id": "SLHD-023", "name": "Single-Leg Glute Bridge (Iso Hold)", "category": "SLHD", "subcategory": "STAB", "movement_pattern": "SLHD", "equipment": "Floor/Bench", "difficulty": "Beginner", "source_organization": "McGill", "description": "", "coaching_cues": ["Lift into bridge position on one leg", "Hold top position", "Breathe steadily", "Maintain hip height"], "common_errors": ["Hips sagging", "Holding breath", "Hip rotation", "Neck craning"], "contraindications": ["Acute lower back pain"], "regressions": ["Double-Leg Bridge Hold", "Shorter Duration"], "progressions": ["Longer Holds", "Unstable Surface"], "equipment_alternatives": ["Stability ball", "Bosu"], "is_pain_safe": True, "created_at": "2024-01-01T00:00:00Z"},
    {"id": "SLHD-024", "name": "Single-Leg Hip Hinge (Band)", "category": "SLHD", "subcategory": "ACT", "movement_pattern": "SLHD", "equipment": "Band, Anchor", "difficulty": "Beginner", "source_organization": "EXOS", "description": "", "coaching_cues": ["Band at hip level for resistance", "Hinge back on one leg", "Feel hamstring and glute engagement", "Return to standing"], "common_errors": ["Knee bending excessively", "Losing balance", "Band pulling off-center", "Rounding back"], "contraindications": ["Acute hamstring strain"], "regressions": ["Two-Leg Band Hinge", "Bodyweight Hinge"], "progressions": ["Heavier Band", "SL RDL"], "equipment_alternatives": ["Cable", "No band"], "is_pain_safe": True, "created_at": "2024-01-01T00:00:00Z"},
    {"id": "SLHD-025", "name": "Single-Leg Prone Hip Extension", "category": "SLHD", "subcategory": "ACT", "movement_pattern": "SLHD", "equipment": "Floor/Band", "difficulty": "Beginner", "source_organization": "NSCA", "description": "", "coaching_cues": ["Lie face down, one leg bent", "Lift thigh off ground", "Squeeze glute at top", "Lower with control"], "common_errors": ["Using lower back", "Hip external rotation", "Incomplete lift", "Holding breath"], "contraindications": ["Lower back issues", "Hip injuries"], "regressions": ["Double-Leg Prone Extension", "Isometric Hold"], "progressions": ["Band Resistance", "Ankle Weight"], "equipment_alternatives": ["Cable", "Ankle weight"], "is_pain_safe": True, "created_at": "2024-01-01T00:00:00Z"},
]

# Add new exercises
exercises.extend(new_exercises)

# Save updated file
with open('forge_web/src/data/exercises.json', 'w') as f:
    json.dump(exercises, f, indent=2)

print(f"\nAdded {len(new_exercises)} new exercises")
print("\nNew totals:")
cats_after = {}
for e in exercises:
    cat = e['category']
    cats_after[cat] = cats_after.get(cat, 0) + 1

for cat in ['DLKD', 'DLHD', 'SLKD', 'SLHD']:
    print(f"  {cat}: {cats_after.get(cat, 0)} exercises (was {cats_before.get(cat, 0)})")
