#!/usr/bin/env python3
"""
Phase 3 Part 2: Add Assessment & Testing + Skill-Integrated Conditioning
Completes the ecosystem expansion
"""

import json

# Load part 1
with open('complete_conditioning_library_phase3_part1.json', 'r') as f:
    protocols = json.load(f)

print(f"Loaded {len(protocols)} protocols from part 1")

# Assessment & Testing protocols (12)
assessment_protocols = [
    {"id": "ASM-001", "name": "Yo-Yo Intermittent Recovery Test Level 1",
     "objective": "Assess aerobic capacity and repeated high-intensity effort ability.",
     "system": "Assessment", "level": "All Levels", "environment": ["Indoor Court", "Turf"],
     "duration": "10-20 min", "work_description": "20m shuttle runs with audio beeps. 10sec recovery between shuttles.",
     "rest": "10sec active", "sets": "Until failure", "total_volume": "Variable",
     "fatigue_score": 10, "tier": "A", "work_rest_ratio": "variable",
     "sport_priority": {"cricket": "high", "tennis": "medium", "badminton": "high", "football": "very_high"},
     "movement_profile": ["linear", "shuttle", "intermittent"],
     "session_role": ["assessment", "benchmarking", "aerobic-capacity"],
     "impact_level": "moderate", "eccentric_load": "moderate", "fatigue_cost": "very_high",
     "equipment_need": "audio_beep_cones", "field_space": "20m_runway",
     "phase_timing": ["pre-season", "mid-season", "post-season"],
     "category": "assessment_testing", "testing_protocol": True, "created_phase": "phase3_ecosystem"},
    
    {"id": "ASM-002", "name": "Counter Movement Jump (CMJ) — Vertical Power",
     "objective": "Assess lower body explosive power and neuromuscular function.",
     "system": "Assessment", "level": "All Levels", "environment": ["Gym", "Lab"],
     "duration": "10-15 min", "work_description": "Maximal vertical jump from countermovement. Record height/power.",
     "rest": "60 sec", "sets": "3-5 attempts", "total_volume": "3-5 jumps",
     "fatigue_score": 6, "tier": "A", "work_rest_ratio": "1:3",
     "sport_priority": {"cricket": "high", "tennis": "high", "badminton": "very_high", "football": "high"},
     "movement_profile": ["jumping", "explosive", "vertical"],
     "session_role": ["assessment", "power-testing", "readiness-monitoring"],
     "impact_level": "moderate", "eccentric_load": "moderate", "fatigue_cost": "moderate",
     "equipment_need": "force_plate_or_jump_mat", "field_space": "minimal",
     "phase_timing": ["weekly", "pre-season", "monitoring"],
     "category": "assessment_testing", "testing_protocol": True, "created_phase": "phase3_ecosystem"},
    
    {"id": "ASM-003", "name": "Pro Agility Shuttle (5-10-5) — Change of Direction",
     "objective": "Assess lateral quickness, acceleration, deceleration, COD ability.",
     "system": "Assessment", "level": "All Levels", "environment": ["Field", "Court"],
     "duration": "10-15 min", "work_description": "5yd right, 10yd left, 5yd back through center. Record time.",
     "rest": "60-90 sec", "sets": "3-5 attempts", "total_volume": "3-5 shuttles",
     "fatigue_score": 7, "tier": "A", "work_rest_ratio": "1:4",
     "sport_priority": {"cricket": "medium", "tennis": "high", "badminton": "high", "football": "very_high"},
     "movement_profile": ["lateral", "change-of-direction", "acceleration"],
     "session_role": ["assessment", "agility-testing", "cod-ability"],
     "impact_level": "moderate", "eccentric_load": "high", "fatigue_cost": "moderate",
     "equipment_need": "cones_stopwatch", "field_space": "5yd_markers",
     "phase_timing": ["pre-season", "mid-season"],
     "category": "assessment_testing", "testing_protocol": True, "created_phase": "phase3_ecosystem"},
    
    {"id": "ASM-004", "name": "Isometric Mid-Thigh Pull (IMTP) — Maximal Strength",
     "objective": "Assess maximal force production and rate of force development.",
     "system": "Assessment", "level": "Intermediate to Elite", "environment": ["Lab", "Gym"],
     "duration": "15-20 min", "work_description": "Pull maximally on fixed bar at mid-thigh for 3-5sec.",
     "rest": "2-3 min", "sets": "3-5 attempts", "total_volume": "3-5 pulls",
     "fatigue_score": 8, "tier": "A", "work_rest_ratio": "1:10",
     "sport_priority": {"cricket": "high", "tennis": "medium", "badminton": "medium", "football": "very_high"},
     "movement_profile": ["isometric", "pulling", "maximal-effort"],
     "session_role": ["assessment", "strength-testing", "force-production"],
     "impact_level": "low", "eccentric_load": "none", "fatigue_cost": "high",
     "equipment_need": "force_plates_fixed_bar", "field_space": "lab_space",
     "phase_timing": ["pre-season", "mid-season", "post-season"],
     "category": "assessment_testing", "testing_protocol": True, "created_phase": "phase3_ecosystem"},
    
    {"id": "ASM-005", "name": "Repeat Sprint Ability (RSA) Test",
     "objective": "Assess ability to maintain sprint performance across repeated efforts.",
     "system": "Assessment", "level": "All Levels", "environment": ["Field", "Track"],
     "duration": "15-20 min", "work_description": "6-10 maximal sprints (20-40m) with 20-30sec recovery.",
     "rest": "20-30 sec", "sets": "6-10 sprints", "total_volume": "120-400m",
     "fatigue_score": 9, "tier": "A", "work_rest_ratio": "1:1",
     "sport_priority": {"cricket": "high", "tennis": "high", "badminton": "very_high", "football": "very_high"},
     "movement_profile": ["linear", "sprinting", "repeat-effort"],
     "session_role": ["assessment", "anaerobic-capacity", "fatigue-resistance"],
     "impact_level": "moderate", "eccentric_load": "high", "fatigue_cost": "very_high",
     "equipment_need": "cones_timing_gates", "field_space": "20-40m_straight",
     "phase_timing": ["pre-season", "mid-season"],
     "category": "assessment_testing", "testing_protocol": True, "created_phase": "phase3_ecosystem"},
    
    {"id": "ASM-006", "name": "Overhead Squat Assessment — Movement Quality",
     "objective": "Screen movement quality, identify mobility limitations.",
     "system": "Assessment", "level": "All Levels", "environment": ["Gym", "Clinic"],
     "duration": "10-15 min", "work_description": "PVC pipe overhead, perform squat. Observe knee tracking, trunk lean, depth.",
     "rest": "30 sec", "sets": "3-5 reps", "total_volume": "3-5 squats",
     "fatigue_score": 2, "tier": "A", "work_rest_ratio": "N/A",
     "sport_priority": {"cricket": "high", "tennis": "high", "badminton": "high", "football": "high"},
     "movement_profile": ["squat", "overhead", "screening"],
     "session_role": ["assessment", "movement-screen", "mobility-identification"],
     "impact_level": "low", "eccentric_load": "low", "fatigue_cost": "minimal",
     "equipment_need": "pvc_pipe", "field_space": "minimal",
     "phase_timing": ["pre-season", "initial-assessment"],
     "category": "assessment_testing", "testing_protocol": True, "created_phase": "phase3_ecosystem"},
    
    {"id": "ASM-007", "name": "Star Excursion Balance Test (SEBT) — Dynamic Balance",
     "objective": "Assess dynamic balance, proprioception, and lower extremity stability.",
     "system": "Assessment", "level": "All Levels", "environment": ["Clinic", "Gym"],
     "duration": "15-20 min", "work_description": "Single-leg stance, reach in 8 directions. Measure reach distance.",
     "rest": "30 sec", "sets": "3 reps/dir/leg", "total_volume": "24 reaches",
     "fatigue_score": 4, "tier": "A", "work_rest_ratio": "1:2",
     "sport_priority": {"cricket": "high", "tennis": "high", "badminton": "high", "football": "high"},
     "movement_profile": ["balance", "single-leg", "multi-directional"],
     "session_role": ["assessment", "balance-testing", "injury-risk-screening"],
     "impact_level": "low", "eccentric_load": "low", "fatigue_cost": "moderate",
     "equipment_need": "tape_measure_lines", "field_space": "3m_circle",
     "phase_timing": ["pre-season", "post-injury", "periodic"],
     "category": "assessment_testing", "testing_protocol": True, "created_phase": "phase3_ecosystem"},
    
    {"id": "ASM-008", "name": "Medicine Ball Rotational Throw — Power Assessment",
     "objective": "Assess rotational power output relevant to cricket, tennis, badminton.",
     "system": "Assessment", "level": "All Levels", "environment": ["Gym", "Field"],
     "duration": "10-15 min", "work_description": "Side stance, throw medicine ball rotationally against wall. Measure distance.",
     "rest": "60 sec", "sets": "3-5 throws/side", "total_volume": "6-10 throws",
     "fatigue_score": 5, "tier": "A", "work_rest_ratio": "1:3",
     "sport_priority": {"cricket": "very_high", "tennis": "very_high", "badminton": "high", "football": "medium"},
     "movement_profile": ["rotational", "explosive", "power"],
     "session_role": ["assessment", "rotational-power", "sport-specific"],
     "impact_level": "low", "eccentric_load": "low", "fatigue_cost": "moderate",
     "equipment_need": "medicine_ball_wall", "field_space": "large",
     "phase_timing": ["pre-season", "mid-season"],
     "category": "assessment_testing", "testing_protocol": True, "created_phase": "phase3_ecosystem"},
    
    {"id": "ASM-009", "name": "Beep Test (VO2max) — Aerobic Capacity",
     "objective": "Estimate VO2max and aerobic endurance capacity.",
     "system": "Assessment", "level": "All Levels", "environment": ["Field", "Track", "Court"],
     "duration": "10-20 min", "work_description": "20m shuttles with progressively faster beeps. Continue until exhaustion.",
     "rest": "None between shuttles", "sets": "Until failure", "total_volume": "Variable",
     "fatigue_score": 10, "tier": "A", "work_rest_ratio": "continuous",
     "sport_priority": {"cricket": "medium", "tennis": "high", "badminton": "high", "football": "very_high"},
     "movement_profile": ["linear", "shuttle", "progressive"],
     "session_role": ["assessment", "vo2max", "aerobic-capacity"],
     "impact_level": "moderate", "eccentric_load": "moderate", "fatigue_cost": "very_high",
     "equipment_need": "audio_beep_cones", "field_space": "20m_runway",
     "phase_timing": ["pre-season", "post-season"],
     "category": "assessment_testing", "testing_protocol": True, "created_phase": "phase3_ecosystem"},
    
    {"id": "ASM-010", "name": "Handgrip Dynamometry — Grip Strength",
     "objective": "Assess grip strength relevant to batting, racket sports, throwing.",
     "system": "Assessment", "level": "All Levels", "environment": ["Gym", "Clinic"],
     "duration": "5-10 min", "work_description": "Maximal grip squeeze on dynamometer. Record kg/lbs.",
     "rest": "30 sec", "sets": "3 attempts/hand", "total_volume": "6 grips",
     "fatigue_score": 3, "tier": "A", "work_rest_ratio": "1:2",
     "sport_priority": {"cricket": "very_high", "tennis": "very_high", "badminton": "very_high", "football": "low"},
     "movement_profile": ["isometric", "grip", "forearm"],
     "session_role": ["assessment", "grip-strength", "sport-specific"],
     "impact_level": "none", "eccentric_load": "none", "fatigue_cost": "low",
     "equipment_need": "dynamometer", "field_space": "minimal",
     "phase_timing": ["pre-season", "mid-season", "post-injury"],
     "category": "assessment_testing", "testing_protocol": True, "created_phase": "phase3_ecosystem"},
    
    {"id": "ASM-011", "name": "T-Test Agility — Multi-Directional Speed",
     "objective": "Assess agility with forward, lateral, and backward running.",
     "system": "Assessment", "level": "All Levels", "environment": ["Field", "Court"],
     "duration": "10-15 min", "work_description": "Forward 10yd, shuffle left 5yd, shuffle right 10yd, shuffle left 5yd, backpedal 10yd.",
     "rest": "60-90 sec", "sets": "3-5 attempts", "total_volume": "3-5 runs",
     "fatigue_score": 7, "tier": "A", "work_rest_ratio": "1:4",
     "sport_priority": {"cricket": "high", "tennis": "high", "badminton": "high", "football": "very_high"},
     "movement_profile": ["multi-directional", "agility", "change-of-direction"],
     "session_role": ["assessment", "agility-testing", "sport-specific"],
     "impact_level": "moderate", "eccentric_load": "high", "fatigue_cost": "moderate",
     "equipment_need": "cones_stopwatch", "field_space": "10x10yd_grid",
     "phase_timing": ["pre-season", "mid-season"],
     "category": "assessment_testing", "testing_protocol": True, "created_phase": "phase3_ecosystem"},
    
    {"id": "ASM-012", "name": "Functional Movement Screen (FMS) — Movement Quality Battery",
     "objective": "Comprehensive movement quality screening across 7 fundamental patterns.",
     "system": "Assessment", "level": "All Levels", "environment": ["Clinic", "Gym"],
     "duration": "20-30 min", "work_description": "7 tests: Deep squat, hurdle step, inline lunge, shoulder mobility, ASLR, trunk stability push-up, rotary stability.",
     "rest": "Between tests", "sets": "1 screen", "total_volume": "7 movement patterns",
     "fatigue_score": 3, "tier": "A", "work_rest_ratio": "N/A",
     "sport_priority": {"cricket": "high", "tennis": "high", "badminton": "high", "football": "high"},
     "movement_profile": ["comprehensive", "screening", "fundamental"],
     "session_role": ["assessment", "movement-screen", "injury-risk"],
     "impact_level": "low", "eccentric_load": "low", "fatigue_cost": "low",
     "equipment_need": "fms_kit", "field_space": "mat_space",
     "phase_timing": ["pre-season", "initial-assessment", "periodic"],
     "category": "assessment_testing", "testing_protocol": True, "created_phase": "phase3_ecosystem"},
]

# Skill-Integrated Conditioning (15 protocols)
skill_integrated = [
    {"id": "SKL-001", "name": "Cricket Batting Intervals — Shot Selection Under Fatigue",
     "objective": "Develop ability to execute skill decisions while metabolically fatigued.",
     "system": "Anaerobic Capacity", "level": "Intermediate to Elite",
     "environment": ["Nets", "Practice Pitch"], "duration": "20-25 min",
     "work_description": "Between-wicket sprint x2, immediately face 3-4 balls. Repeat. Focus on shot selection despite fatigue.",
     "rest": "60 sec between sets", "sets": "6-8 sets", "total_volume": "18-24 balls faced",
     "fatigue_score": 7, "tier": "A", "work_rest_ratio": "1:2",
     "sport_priority": {"cricket": "very_high", "tennis": "low", "badminton": "low", "football": "low"},
     "movement_profile": ["sprinting", "batting", "decision-making"],
     "session_role": ["skill-conditioning", "cricket-specific", "pressure-training"],
     "impact_level": "moderate", "eccentric_load": "moderate", "fatigue_cost": "high",
     "equipment_need": "bat_balls_bowling_machine", "field_space": "nets",
     "phase_timing": ["pre-season", "in-season"],
     "category": "skill_integrated", "cricket_role_specific": ["batter"], "created_phase": "phase3_ecosystem"},
    
    {"id": "SKL-002", "name": "Cricket Bowling Spell Simulation — Match Demand Replication",
     "objective": "Replicate match bowling demands with skill execution under cumulative fatigue.",
     "system": "Anaerobic Capacity", "level": "Intermediate to Elite",
     "environment": ["Practice Pitch", "Nets"], "duration": "25-30 min",
     "work_description": "Bowl 6-ball over (max effort), walk back, bowl again. 4-6 overs total. Monitor speed/accuracy.",
     "rest": "3 min between overs", "sets": "4-6 overs", "total_volume": "24-36 deliveries",
     "fatigue_score": 8, "tier": "A", "work_rest_ratio": "1:3",
     "sport_priority": {"cricket": "very_high", "tennis": "low", "badminton": "low", "football": "low"},
     "movement_profile": ["bowling", "repeat-effort", "skill-endurance"],
     "session_role": ["skill-conditioning", "cricket-specific", "bowler-preparation"],
     "impact_level": "high", "eccentric_load": "high", "fatigue_cost": "very_high",
     "equipment_need": "ball_stumps", "field_space": "pitch",
     "phase_timing": ["pre-season", "in-season"],
     "category": "skill_integrated", "cricket_role_specific": ["fast_bowler", "spinner"], "created_phase": "phase3_ecosystem"},
    
    {"id": "SKL-003", "name": "Cricket Fielding Repeats — High-Intensity Ground Fielding",
     "objective": "Develop repeat diving/stopping ability with quick release accuracy.",
     "system": "Anaerobic Capacity", "level": "All Levels",
     "environment": ["Field", "Practice Area"], "duration": "15-20 min",
     "work_description": "Sprint to ball, dive/stop, quick return throw. Coach feeds to different positions rapidly.",
     "rest": "30 sec between reps", "sets": "8-10 reps", "total_volume": "8-10 fielding efforts",
     "fatigue_score": 7, "tier": "A", "work_rest_ratio": "1:2",
     "sport_priority": {"cricket": "very_high", "tennis": "low", "badminton": "low", "football": "low"},
     "movement_profile": ["diving", "throwing", "multi-directional"],
     "session_role": ["skill-conditioning", "cricket-specific", "fielding-preparation"],
     "impact_level": "high", "eccentric_load": "high", "fatigue_cost": "high",
     "equipment_need": "balls_gloves", "field_space": "field_area",
     "phase_timing": ["pre-season", "in-season"],
     "category": "skill_integrated", "cricket_role_specific": ["all_fielders"], "created_phase": "phase3_ecosystem"},
    
    {"id": "SKL-004", "name": "Cricket Between-Wicket Sprint Conversion — Call Reaction",
     "objective": "Train rapid decision-making and sprint execution for converting singles to twos.",
     "system": "ATP-PC System", "level": "All Levels",
     "environment": ["Pitch", "Nets"], "duration": "12-15 min",
     "work_description": "Start at crease, react to coach call, sprint to opposite end, touch ground, return. Random calls.",
     "rest": "25 sec", "sets": "8-10 reps", "total_volume": "8-10 sprints",
     "fatigue_score": 6, "tier": "A", "work_rest_ratio": "1:4",
     "sport_priority": {"cricket": "very_high", "tennis": "low", "badminton": "low", "football": "low"},
     "movement_profile": ["sprinting", "reaction", "deceleration"],
     "session_role": ["skill-conditioning", "cricket-specific", "running-between-wickets"],
     "impact_level": "moderate", "eccentric_load": "high", "fatigue_cost": "moderate",
     "equipment_need": "bat_optional", "field_space": "pitch",
     "phase_timing": ["pre-season", "in-season"],
     "category": "skill_integrated", "cricket_role_specific": ["batter"], "created_phase": "phase3_ecosystem"},
    
    {"id": "SKL-005", "name": "Tennis Cross-Court Rally Endurance — Stroke Consistency Under Fatigue",
     "objective": "Maintain stroke accuracy and depth while metabolically stressed.",
     "system": "Anaerobic Capacity", "level": "Intermediate to Elite",
     "environment": ["Tennis Court"], "duration": "15-20 min",
     "work_description": "Coach feeds balls rapidly to forehand/backhand. Player must hit 5-8 consecutive cross-court shots. Minimal rest.",
     "rest": "20 sec between sequences", "sets": "8-10 sequences", "total_volume": "40-80 shots",
     "fatigue_score": 7, "tier": "A", "work_rest_ratio": "1:1",
     "sport_priority": {"cricket": "low", "tennis": "very_high", "badminton": "medium", "football": "low"},
     "movement_profile": ["lateral", "stroke-production", "endurance"],
     "session_role": ["skill-conditioning", "tennis-specific", "rally-endurance"],
     "impact_level": "moderate", "eccentric_load": "moderate", "fatigue_cost": "high",
     "equipment_need": "racket_balls_ball_machine", "field_space": "court",
     "phase_timing": ["pre-season", "in-season"],
     "category": "skill_integrated", "tennis_position": ["all_players"], "created_phase": "phase3_ecosystem"},
    
    {"id": "SKL-006", "name": "Tennis Serve Accuracy Under Fatigue — Match Point Simulation",
     "objective": "Maintain serve accuracy and power when fatigued (like 5th set).",
     "system": "Anaerobic Capacity", "level": "Intermediate to Elite",
     "environment": ["Tennis Court"], "duration": "15-20 min",
     "work_description": "Perform court sprints, then immediately serve to designated targets. Track accuracy %.",
     "rest": "45 sec between serves", "sets": "10-12 serves", "total_volume": "10-12 fatigued serves",
     "fatigue_score": 8, "tier": "A", "work_rest_ratio": "1:2",
     "sport_priority": {"cricket": "low", "tennis": "very_high", "badminton": "low", "football": "low"},
     "movement_profile": ["serving", "sprinting", "precision"],
     "session_role": ["skill-conditioning", "tennis-specific", "pressure-serving"],
     "impact_level": "moderate", "eccentric_load": "moderate", "fatigue_cost": "high",
     "equipment_need": "racket_balls_targets", "field_space": "court",
     "phase_timing": ["pre-season", "in-season"],
     "category": "skill_integrated", "tennis_position": ["all_players"], "created_phase": "phase3_ecosystem"},
    
    {"id": "SKL-007", "name": "Tennis Defensive Scramble — Recovery Positioning",
     "objective": "Train ability to recover court position after being pulled wide, then defend next shot.",
     "system": "Anaerobic Capacity", "level": "Intermediate to Elite",
     "environment": ["Tennis Court"], "duration": "15-18 min",
     "work_description": "Coach hits wide, player scrambles to retrieve, recovers to center, prepares for next ball. Repeat sequence.",
     "rest": "30 sec between sequences", "sets": "8-10 sequences", "total_volume": "16-20 retrieval efforts",
     "fatigue_score": 7, "tier": "A", "work_rest_ratio": "1:2",
     "sport_priority": {"cricket": "low", "tennis": "very_high", "badminton": "high", "football": "low"},
     "movement_profile": ["lateral", "recovery", "defensive"],
     "session_role": ["skill-conditioning", "tennis-specific", "defensive-endurance"],
     "impact_level": "moderate", "eccentric_load": "high", "fatigue_cost": "high",
     "equipment_need": "racket_balls", "field_space": "court",
     "phase_timing": ["pre-season", "in-season"],
     "category": "skill_integrated", "tennis_position": ["baseline_player", "all_court"], "created_phase": "phase3_ecosystem"},
    
    {"id": "SKL-008", "name": "Badminton Shadow Footwork — Pattern Endurance",
     "objective": "Build endurance for specific footwork patterns used in matches.",
     "system": "Anaerobic Capacity", "level": "All Levels",
     "environment": ["Badminton Court"], "duration": "15-20 min",
     "work_description": "Shadow play through 6-corner footwork pattern. Add swing simulation. Maximum speed.",
     "rest": "20 sec", "sets": "8-10 patterns", "total_volume": "48-60 corner touches",
     "fatigue_score": 7, "tier": "A", "work_rest_ratio": "1:1",
     "sport_priority": {"cricket": "low", "tennis": "medium", "badminton": "very_high", "football": "low"},
     "movement_profile": ["footwork", "multi-directional", "shadow-play"],
     "session_role": ["skill-conditioning", "badminton-specific", "footwork-endurance"],
     "impact_level": "low", "eccentric_load": "moderate", "fatigue_cost": "high",
     "equipment_need": "racket_optional", "field_space": "court",
     "phase_timing": ["pre-season", "in-season"],
     "category": "skill_integrated", "badminton_position": ["singles", "doubles"], "created_phase": "phase3_ecosystem"},
    
    {"id": "SKL-009", "name": "Badminton Jump Smash Repeat — Explosive Endurance",
     "objective": "Maintain jump smash power and accuracy across multiple repetitions.",
     "system": "ATP-PC System", "level": "Intermediate to Elite",
     "environment": ["Badminton Court"], "duration": "12-15 min",
     "work_description": "High clear to backcourt, move back, jump smash, recover. Coach feeds repeatedly.",
     "rest": "25 sec", "sets": "8-10 smashes", "total_volume": "8-10 jump smashes",
     "fatigue_score": 7, "tier": "A", "work_rest_ratio": "1:3",
     "sport_priority": {"cricket": "low", "tennis": "low", "badminton": "very_high", "football": "low"},
     "movement_profile": ["jumping", "smashing", "overhead"],
     "session_role": ["skill-conditioning", "badminton-specific", "power-endurance"],
     "impact_level": "high", "eccentric_load": "high", "fatigue_cost": "high",
     "equipment_need": "racket_shuttles", "field_space": "court",
     "phase_timing": ["pre-season", "in-season"],
     "category": "skill_integrated", "badminton_position": ["singles", "doubles"], "created_phase": "phase3_ecosystem"},
    
    {"id": "SKL-010", "name": "Badminton Net Kill Reaction — Reflex Endurance",
     "objective": "Maintain quick net kill reactions despite accumulated fatigue.",
     "system": "ATP-PC System", "level": "Intermediate to Elite",
     "environment": ["Badminton Court"], "duration": "10-12 min",
     "work_description": "Rapid-fire net shots from coach. Player must kill downward. Focus on reaction time.",
     "rest": "20 sec", "sets": "6-8 sequences of 5 shots", "total_volume": "30-40 net kills",
     "fatigue_score": 6, "tier": "A", "work_rest_ratio": "1:2",
     "sport_priority": {"cricket": "low", "tennis": "low", "badminton": "very_high", "football": "low"},
     "movement_profile": ["reaction", "net-play", "reflexes"],
     "session_role": ["skill-conditioning", "badminton-specific", "net-dominance"],
     "impact_level": "low", "eccentric_load": "low", "fatigue_cost": "moderate",
     "equipment_need": "racket_shuttles", "field_space": "court",
     "phase_timing": ["pre-season", "in-season"],
     "category": "skill_integrated", "badminton_position": ["doubles", "singles"], "created_phase": "phase3_ecosystem"},
    
    {"id": "SKL-011", "name": "Football Small-Sided Game — Position-Specific Conditioning",
     "objective": "Develop sport-specific conditioning through constrained small-sided games.",
     "system": "Anaerobic Capacity", "level": "All Levels",
     "environment": ["Field", "Turf"], "duration": "20-25 min",
     "work_description": "4v4 or 5v5 game with constraints (e.g., 2-touch max, pressing triggers). High intensity.",
     "rest": "2 min between bouts", "sets": "4-5 bouts of 3-4 min", "total_volume": "12-20 min playing time",
     "fatigue_score": 8, "tier": "A", "work_rest_ratio": "1:1",
     "sport_priority": {"cricket": "low", "tennis": "low", "badminton": "low", "football": "very_high"},
     "movement_profile": ["multi-directional", "game-specific", "intermittent"],
     "session_role": ["skill-conditioning", "football-specific", "tactical-endurance"],
     "impact_level": "moderate-high", "eccentric_load": "high", "fatigue_cost": "very_high",
     "equipment_need": "balls_cones_vests", "field_space": "small_pitch",
     "phase_timing": ["pre-season", "in-season"],
     "category": "skill_integrated", "football_position": ["all_positions"], "created_phase": "phase3_ecosystem"},
    
    {"id": "SKL-012", "name": "Football Position-Specific Route Running — Repeat Speed",
     "objective": "Maintain route-running precision and speed across repeated efforts.",
     "system": "ATP-PC System", "level": "Intermediate to Elite",
     "environment": ["Field", "Turf"], "duration": "15-20 min",
     "work_description": "Run precise routes (slant, out, post, corner) at game speed. Catch, reset, repeat.",
     "rest": "30-40 sec", "sets": "8-10 routes", "total_volume": "8-10 full-speed routes",
     "fatigue_score": 7, "tier": "A", "work_rest_ratio": "1:3",
     "sport_priority": {"cricket": "low", "tennis": "low", "badminton": "low", "football": "very_high"},
     "movement_profile": ["route-running", "sprinting", "cutting"],
     "session_role": ["skill-conditioning", "football-specific", "receiver-preparation"],
     "impact_level": "moderate", "eccentric_load": "high", "fatigue_cost": "high",
     "equipment_need": "football_cones", "field_space": "field_area",
     "phase_timing": ["pre-season", "in-season"],
     "category": "skill_integrated", "football_position": ["wide_receiver", "tight_end"], "created_phase": "phase3_ecosystem"},
    
    {"id": "SKL-013", "name": "Football Goalkeeper Dive Reaction — Repeat Explosiveness",
     "objective": "Maintain explosive diving reaction speed across multiple saves.",
     "system": "ATP-PC System", "level": "Intermediate to Elite",
     "environment": ["Goal Area", "Field"], "duration": "12-15 min",
     "work_description": "Coach shoots to various corners. GK dives explosively, recovers quickly for next shot.",
     "rest": "25-30 sec", "sets": "8-10 shots", "total_volume": "8-10 dives",
     "fatigue_score": 7, "tier": "A", "work_rest_ratio": "1:3",
     "sport_priority": {"cricket": "low", "tennis": "low", "badminton": "low", "football": "very_high"},
     "movement_profile": ["diving", "reaction", "explosive"],
     "session_role": ["skill-conditioning", "football-specific", "goalkeeper-preparation"],
     "impact_level": "high", "eccentric_load": "high", "fatigue_cost": "high",
     "equipment_need": "balls_goal", "field_space": "goal_area",
     "phase_timing": ["pre-season", "in-season"],
     "category": "skill_integrated", "football_position": ["goalkeeper"], "created_phase": "phase3_ecosystem"},
    
    {"id": "SKL-014", "name": "Football Box-to-Box Transition — Endurance with Ball",
     "objective": "Develop ability to transition box-to-box while maintaining technical quality.",
     "system": "Anaerobic Capacity", "level": "Intermediate to Elite",
     "environment": ["Field", "Turf"], "duration": "18-22 min",
     "work_description": "Start at one box, receive pass, dribble/carry to opposite box, shoot/pass. Jog back, repeat.",
     "rest": "45 sec", "sets": "6-8 transitions", "total_volume": "6-8 full-pitch efforts",
     "fatigue_score": 8, "tier": "A", "work_rest_ratio": "1:2",
     "sport_priority": {"cricket": "low", "tennis": "low", "badminton": "low", "football": "very_high"},
     "movement_profile": ["running", "ball-handling", "transition"],
     "session_role": ["skill-conditioning", "football-specific", "midfielder-preparation"],
     "impact_level": "moderate", "eccentric_load": "moderate", "fatigue_cost": "very_high",
     "equipment_need": "balls_goals_cones", "field_space": "full_pitch",
     "phase_timing": ["pre-season", "in-season"],
     "category": "skill_integrated", "football_position": ["midfielder"], "created_phase": "phase3_ecosystem"},
    
    {"id": "SKL-015", "name": "Multi-Sport Reactive Agility — Universal Decision Making",
     "objective": "Develop reactive agility and decision-making applicable across all target sports.",
     "system": "ATP-PC System", "level": "All Levels",
     "environment": ["Court", "Field"], "duration": "15-18 min",
     "work_description": "React to visual cues (lights, coach signals) with sport-specific movement patterns. Randomize responses.",
     "rest": "25 sec", "sets": "10-12 reactions", "total_volume": "10-12 reactive efforts",
     "fatigue_score": 6, "tier": "A", "work_rest_ratio": "1:3",
     "sport_priority": {"cricket": "high", "tennis": "high", "badminton": "high", "football": "high"},
     "movement_profile": ["reactive", "multi-directional", "decision-making"],
     "session_role": ["skill-conditioning", "universal", "reactive-agility"],
     "impact_level": "moderate", "eccentric_load": "moderate", "fatigue_cost": "moderate",
     "equipment_need": "reaction_lights_cones", "field_space": "court_or_field",
     "phase_timing": ["pre-season", "in-season", "year-round"],
     "category": "skill_integrated", "created_phase": "phase3_ecosystem"},
]

# Combine all
all_protocols = protocols + assessment_protocols + skill_integrated

# Save final complete library
with open('complete_conditioning_library_phase3_ecosystem.json', 'w') as f:
    json.dump(all_protocols, f, indent=2)

print(f"\n{'='*80}")
print(f"PHASE 3 COMPLETE: Complete Athlete Ecosystem")
print(f"{'='*80}")
print(f"Total protocols: {len(all_protocols)}")
print(f"  - Original conditioning: 135")
print(f"  - Recovery & Regeneration: 18")
print(f"  - Injury Prevention: 18")
print(f"  - Assessment & Testing: 12")
print(f"  - Skill-Integrated: 15")
print(f"\nSaved to: complete_conditioning_library_phase3_ecosystem.json")

# Category breakdown
categories = {}
for p in all_protocols:
    cat = p.get('category', 'conditioning')
    categories[cat] = categories.get(cat, 0) + 1

print(f"\nCategory Distribution:")
for cat, count in sorted(categories.items()):
    pct = (count / len(all_protocols)) * 100
    print(f"  {cat}: {count} ({pct:.1f}%)")
