#!/usr/bin/env python3
"""
Phase 3: Complete Athlete Ecosystem Expansion
Adds four critical missing categories:
1. Recovery & Regeneration (18 protocols)
2. Injury Prevention (18 protocols)  
3. Assessment & Testing (12 protocols)
4. Skill-Integrated Conditioning (15 protocols)

Total: 63 new protocols, expanding library from 135 to 198 protocols
"""

import json
from datetime import datetime

# Load existing data
with open('enriched_conditioning_data_phase2_targeted.json', 'r') as f:
    existing_protocols = json.load(f)

print(f"Loaded {len(existing_protocols)} existing protocols")
print("=" * 80)

# Phase 3 additions - all 63 protocols
phase3_protocols = [
    # ==================== RECOVERY & REGENERATION (18 protocols) ====================
    {
        "id": "REC-001", "name": "Active Recovery Walk — Low Intensity Steady State",
        "objective": "Promote blood flow and metabolic waste clearance without adding fatigue.",
        "system": "Aerobic Base", "level": "All Levels",
        "environment": ["Outdoor", "Treadmill", "Track"], "duration": "20-30 min",
        "work_description": "Brisk walk at conversational pace (RPE 2-3/10). Zone 1 heart rate.",
        "rest": "Continuous", "sets": "1", "total_volume": "20-30 minutes",
        "fatigue_score": 1, "tier": "A", "work_rest_ratio": "N/A",
        "sport_priority": {"cricket": "high", "tennis": "high", "badminton": "high", "football": "high"},
        "movement_profile": ["linear", "low-impact"],
        "session_role": ["recovery", "active-rest", "between-sessions"],
        "impact_level": "very_low", "eccentric_load": "minimal", "fatigue_cost": "negative",
        "equipment_need": "none", "field_space": "minimal",
        "phase_timing": ["in-season", "post-competition", "deload-week"],
        "category": "recovery_regeneration", "created_phase": "phase3_ecosystem"
    },
    {
        "id": "REC-002", "name": "Contrast Water Therapy — Hot/Cold Immersion",
        "objective": "Enhance circulation through vasodilation/vasoconstriction cycles.",
        "system": "Recovery Modality", "level": "All Levels",
        "environment": ["Pool", "Spa Facility"], "duration": "15-20 min",
        "work_description": "Alternate cold (10-15°C, 1min) and hot (38-40°C, 2min) water. 5-7 cycles.",
        "rest": "30 sec transition", "sets": "5-7 cycles", "total_volume": "15-20 min",
        "fatigue_score": 0, "tier": "A", "work_rest_ratio": "1:2",
        "sport_priority": {"cricket": "high", "tennis": "high", "badminton": "medium", "football": "high"},
        "movement_profile": ["static", "passive"],
        "session_role": ["recovery", "post-competition", "soreness-management"],
        "impact_level": "none", "eccentric_load": "none", "fatigue_cost": "negative",
        "equipment_need": "pool_spa", "field_space": "facility",
        "phase_timing": ["in-season", "post-competition"],
        "category": "recovery_regeneration", "created_phase": "phase3_ecosystem"
    },
    {
        "id": "REC-003", "name": "Foam Rolling Sequence — Lower Body Release",
        "objective": "Release myofascial tension in calves, hamstrings, quads, IT band, glutes.",
        "system": "Mobility/Recovery", "level": "All Levels",
        "environment": ["Indoor", "Gym", "Home"], "duration": "12-15 min",
        "work_description": "Roll each muscle group 60-90 sec. Pause on tender spots 20-30 sec.",
        "rest": "15 sec between groups", "sets": "1 circuit", "total_volume": "6-8 muscle groups",
        "fatigue_score": 1, "tier": "A", "work_rest_ratio": "continuous",
        "sport_priority": {"cricket": "high", "tennis": "high", "badminton": "high", "football": "high"},
        "movement_profile": ["myofascial", "static-pressure"],
        "session_role": ["recovery", "warmup-prep", "cooldown"],
        "impact_level": "low", "eccentric_load": "none", "fatigue_cost": "minimal",
        "equipment_need": "foam_roller", "field_space": "mat_space",
        "phase_timing": ["year-round", "daily"],
        "category": "recovery_regeneration", "created_phase": "phase3_ecosystem"
    },
    {
        "id": "REC-004", "name": "Yoga Flow — Vinyasa Recovery Sequence",
        "objective": "Restore mobility, reduce stress, enhance breath control.",
        "system": "Mobility/Recovery", "level": "All Levels",
        "environment": ["Indoor", "Studio", "Quiet Space"], "duration": "20-30 min",
        "work_description": "Sun salutations, downward dog, warrior sequences, pigeon pose, twists.",
        "rest": "Child's pose as needed", "sets": "3-5 rounds", "total_volume": "15-20 poses",
        "fatigue_score": 2, "tier": "A", "work_rest_ratio": "flow-based",
        "sport_priority": {"cricket": "high", "tennis": "high", "badminton": "high", "football": "medium"},
        "movement_profile": ["multi-planar", "mobility", "balance"],
        "session_role": ["recovery", "mobility", "stress-reduction"],
        "impact_level": "very_low", "eccentric_load": "minimal", "fatigue_cost": "negative",
        "equipment_need": "yoga_mat", "field_space": "mat_space",
        "phase_timing": ["year-round", "in-season", "deload-week"],
        "category": "recovery_regeneration", "created_phase": "phase3_ecosystem"
    },
    {
        "id": "REC-005", "name": "Compression Boots — Pneumatic Compression Therapy",
        "objective": "Enhance venous return and lymphatic drainage. Reduce swelling.",
        "system": "Recovery Modality", "level": "All Levels",
        "environment": ["Recovery Center", "Home"], "duration": "20-30 min",
        "work_description": "Pneumatic compression boots, 60-80 mmHg pressure. Seated/lying.",
        "rest": "Continuous", "sets": "1", "total_volume": "20-30 min",
        "fatigue_score": 0, "tier": "A", "work_rest_ratio": "N/A",
        "sport_priority": {"cricket": "medium", "tennis": "high", "badminton": "medium", "football": "high"},
        "movement_profile": ["passive", "static"],
        "session_role": ["recovery", "post-competition", "travel-day"],
        "impact_level": "none", "eccentric_load": "none", "fatigue_cost": "negative",
        "equipment_need": "compression_boots", "field_space": "chair_space",
        "phase_timing": ["in-season", "post-competition"],
        "category": "recovery_regeneration", "created_phase": "phase3_ecosystem"
    },
    {
        "id": "REC-006", "name": "Diaphragmatic Breathing — Parasympathetic Activation",
        "objective": "Activate vagal tone and parasympathetic nervous system.",
        "system": "Recovery/Neurological", "level": "All Levels",
        "environment": ["Any Quiet Space"], "duration": "5-10 min",
        "work_description": "Inhale 4 counts, exhale 6-8 counts. Belly breathing focus.",
        "rest": "Continuous", "sets": "1", "total_volume": "30-50 breath cycles",
        "fatigue_score": 0, "tier": "A", "work_rest_ratio": "4:6",
        "sport_priority": {"cricket": "high", "tennis": "high", "badminton": "high", "football": "high"},
        "movement_profile": ["respiratory", "static"],
        "session_role": ["recovery", "pre-sleep", "stress-management"],
        "impact_level": "none", "eccentric_load": "none", "fatigue_cost": "negative",
        "equipment_need": "none", "field_space": "minimal",
        "phase_timing": ["year-round", "daily"],
        "category": "recovery_regeneration", "created_phase": "phase3_ecosystem"
    },
    {
        "id": "REC-007", "name": "Cold Plunge — Cryotherapy Immersion",
        "objective": "Reduce inflammation and muscle damage through vasoconstriction.",
        "system": "Recovery Modality", "level": "Intermediate to Elite",
        "environment": ["Cold Plunge Pool", "Ice Bath"], "duration": "5-10 min",
        "work_description": "Full body immersion (8-12°C). Controlled breathing. Build tolerance.",
        "rest": "N/A", "sets": "1", "total_volume": "5-10 min",
        "fatigue_score": 0, "tier": "A", "work_rest_ratio": "N/A",
        "sport_priority": {"cricket": "medium", "tennis": "high", "badminton": "medium", "football": "high"},
        "movement_profile": ["passive", "static"],
        "session_role": ["recovery", "post-competition", "inflammation-reduction"],
        "impact_level": "none", "eccentric_load": "none", "fatigue_cost": "minimal",
        "equipment_need": "cold_plunge", "field_space": "facility",
        "phase_timing": ["in-season", "post-competition"],
        "category": "recovery_regeneration", "created_phase": "phase3_ecosystem"
    },
    {
        "id": "REC-008", "name": "Heat Therapy — Sauna Session",
        "objective": "Promote heat shock protein production, enhance circulation.",
        "system": "Recovery Modality", "level": "All Levels",
        "environment": ["Sauna", "Steam Room"], "duration": "15-20 min",
        "work_description": "Traditional sauna (70-90°C) or infrared (50-60°C). Hydrate well.",
        "rest": "Cool down post-session", "sets": "1-2 rounds", "total_volume": "15-30 min",
        "fatigue_score": 1, "tier": "A", "work_rest_ratio": "N/A",
        "sport_priority": {"cricket": "medium", "tennis": "medium", "badminton": "medium", "football": "medium"},
        "movement_profile": ["passive", "static"],
        "session_role": ["recovery", "relaxation", "cardiovascular-health"],
        "impact_level": "none", "eccentric_load": "none", "fatigue_cost": "minimal",
        "equipment_need": "sauna", "field_space": "facility",
        "phase_timing": ["year-round", "off-season", "deload-week"],
        "category": "recovery_regeneration", "created_phase": "phase3_ecosystem"
    },
    {
        "id": "REC-009", "name": "Massage Gun — Percussive Therapy",
        "objective": "Release muscle tension and trigger points through percussive stimulation.",
        "system": "Recovery/Mobility", "level": "All Levels",
        "environment": ["Any Location"], "duration": "10-15 min",
        "work_description": "Apply to major muscle groups 60-90 sec each. Appropriate attachments.",
        "rest": "10 sec between groups", "sets": "1 circuit", "total_volume": "6-10 muscle groups",
        "fatigue_score": 1, "tier": "B", "work_rest_ratio": "continuous",
        "sport_priority": {"cricket": "high", "tennis": "high", "badminton": "high", "football": "high"},
        "movement_profile": ["percussive", "myofascial"],
        "session_role": ["recovery", "pre-activation", "soreness-management"],
        "impact_level": "low", "eccentric_load": "none", "fatigue_cost": "minimal",
        "equipment_need": "massage_gun", "field_space": "minimal",
        "phase_timing": ["year-round", "daily"],
        "category": "recovery_regeneration", "created_phase": "phase3_ecosystem"
    },
    {
        "id": "REC-010", "name": "Sleep Optimization Protocol — Circadian Rhythm Alignment",
        "objective": "Maximize sleep quality for optimal recovery hormone production.",
        "system": "Recovery/Lifestyle", "level": "All Levels",
        "environment": ["Bedroom"], "duration": "8-9 hours nightly",
        "work_description": "Consistent sleep/wake times. Dark, cool room (18-20°C). No screens 90min before bed.",
        "rest": "N/A", "sets": "Daily", "total_volume": "8-9 hours",
        "fatigue_score": -2, "tier": "A", "work_rest_ratio": "N/A",
        "sport_priority": {"cricket": "high", "tennis": "high", "badminton": "high", "football": "high"},
        "movement_profile": ["lifestyle", "passive"],
        "session_role": ["recovery", "foundational", "hormonal-optimization"],
        "impact_level": "none", "eccentric_load": "none", "fatigue_cost": "negative",
        "equipment_need": "sleep_environment", "field_space": "bedroom",
        "phase_timing": ["year-round", "daily"],
        "category": "recovery_regeneration", "created_phase": "phase3_ecosystem"
    },
    {
        "id": "REC-011", "name": "Pool Recovery — Aquatic Active Recovery",
        "objective": "Low-impact movement with buoyancy and hydrostatic pressure.",
        "system": "Aerobic Base", "level": "All Levels",
        "environment": ["Pool"], "duration": "20-30 min",
        "work_description": "Light swimming, water walking, aqua jogging. RPE 2-3/10.",
        "rest": "As needed", "sets": "Continuous", "total_volume": "20-30 min",
        "fatigue_score": 1, "tier": "A", "work_rest_ratio": "flexible",
        "sport_priority": {"cricket": "medium", "tennis": "high", "badminton": "medium", "football": "high"},
        "movement_profile": ["multi-directional", "low-impact", "buoyant"],
        "session_role": ["recovery", "active-rest", "injury-rehabilitation"],
        "impact_level": "none", "eccentric_load": "minimal", "fatigue_cost": "negative",
        "equipment_need": "pool", "field_space": "pool",
        "phase_timing": ["in-season", "post-competition", "injury-return"],
        "category": "recovery_regeneration", "created_phase": "phase3_ecosystem"
    },
    {
        "id": "REC-012", "name": "Dynamic Mobility Circuit — Joint Preparation Flow",
        "objective": "Restore full ROM across all major joints through movement.",
        "system": "Mobility", "level": "All Levels",
        "environment": ["Indoor", "Gym", "Home"], "duration": "10-15 min",
        "work_description": "Ankle circles, knee hugs, hip CARs, thoracic rotations, shoulder dislocates, cat-cow.",
        "rest": "Minimal", "sets": "1-2 circuits", "total_volume": "8-10 exercises",
        "fatigue_score": 1, "tier": "A", "work_rest_ratio": "circuit-style",
        "sport_priority": {"cricket": "high", "tennis": "high", "badminton": "high", "football": "high"},
        "movement_profile": ["multi-planar", "mobility", "dynamic"],
        "session_role": ["recovery", "warmup-prep", "mobility"],
        "impact_level": "very_low", "eccentric_load": "minimal", "fatigue_cost": "minimal",
        "equipment_need": "minimal", "field_space": "mat_space",
        "phase_timing": ["year-round", "daily"],
        "category": "recovery_regeneration", "created_phase": "phase3_ecosystem"
    },
    {
        "id": "REC-013", "name": "Meditation — Mindfulness Practice",
        "objective": "Reduce psychological stress, improve focus, enhance emotional regulation.",
        "system": "Recovery/Neurological", "level": "All Levels",
        "environment": ["Quiet Space"], "duration": "10-20 min",
        "work_description": "Seated meditation: breath awareness, body scan, or guided visualization.",
        "rest": "N/A", "sets": "1", "total_volume": "10-20 min",
        "fatigue_score": -1, "tier": "A", "work_rest_ratio": "N/A",
        "sport_priority": {"cricket": "high", "tennis": "high", "badminton": "medium", "football": "medium"},
        "movement_profile": ["static", "mental"],
        "session_role": ["recovery", "stress-reduction", "focus-enhancement"],
        "impact_level": "none", "eccentric_load": "none", "fatigue_cost": "negative",
        "equipment_need": "none", "field_space": "minimal",
        "phase_timing": ["year-round", "daily"],
        "category": "recovery_regeneration", "created_phase": "phase3_ecosystem"
    },
    {
        "id": "REC-014", "name": "Hydration Protocol — Electrolyte Repletion",
        "objective": "Restore fluid balance and electrolyte levels post-exercise.",
        "system": "Recovery/Nutritional", "level": "All Levels",
        "environment": ["Any"], "duration": "Ongoing throughout day",
        "work_description": "500-750ml water with electrolytes post-training. Continue throughout day.",
        "rest": "N/A", "sets": "Continuous", "total_volume": "3-4 liters daily",
        "fatigue_score": -1, "tier": "A", "work_rest_ratio": "N/A",
        "sport_priority": {"cricket": "high", "tennis": "high", "badminton": "high", "football": "high"},
        "movement_profile": ["nutritional", "lifestyle"],
        "session_role": ["recovery", "foundational", "performance-support"],
        "impact_level": "none", "eccentric_load": "none", "fatigue_cost": "negative",
        "equipment_need": "water_electrolytes", "field_space": "N/A",
        "phase_timing": ["year-round", "daily"],
        "category": "recovery_regeneration", "created_phase": "phase3_ecosystem"
    },
    {
        "id": "REC-015", "name": "PNF Stretching — Proprioceptive Neuromuscular Facilitation",
        "objective": "Improve flexibility through contract-relax technique.",
        "system": "Mobility", "level": "Intermediate to Advanced",
        "environment": ["Indoor", "Gym", "Therapy Room"], "duration": "15-20 min",
        "work_description": "Passive stretch 10sec, isometric contraction 6sec, relax, deeper stretch 30sec.",
        "rest": "30 sec between muscles", "sets": "2-3 cycles per muscle",
        "total_volume": "4-6 muscle groups", "fatigue_score": 2, "tier": "A",
        "work_rest_ratio": "10:6:30",
        "sport_priority": {"cricket": "high", "tennis": "high", "badminton": "high", "football": "high"},
        "movement_profile": ["stretching", "isometric"],
        "session_role": ["recovery", "flexibility", "mobility"],
        "impact_level": "low", "eccentric_load": "none", "fatigue_cost": "low",
        "equipment_need": "strap_or_partner", "field_space": "mat_space",
        "phase_timing": ["year-round", "post-training"],
        "category": "recovery_regeneration", "created_phase": "phase3_ecosystem"
    },
    {
        "id": "REC-016", "name": "Red Light Therapy — Photobiomodulation",
        "objective": "Enhance mitochondrial function and ATP production. Reduce inflammation.",
        "system": "Recovery Modality", "level": "All Levels",
        "environment": ["Recovery Center", "Clinic"], "duration": "10-20 min",
        "work_description": "Expose to red/NIR light (660nm, 850nm). Distance 6-12 inches.",
        "rest": "N/A", "sets": "1", "total_volume": "10-20 min",
        "fatigue_score": 0, "tier": "B", "work_rest_ratio": "N/A",
        "sport_priority": {"cricket": "medium", "tennis": "medium", "badminton": "medium", "football": "medium"},
        "movement_profile": ["passive", "static"],
        "session_role": ["recovery", "tissue-repair", "inflammation-reduction"],
        "impact_level": "none", "eccentric_load": "none", "fatigue_cost": "negative",
        "equipment_need": "red_light_device", "field_space": "minimal",
        "phase_timing": ["in-season", "post-injury", "high-load-blocks"],
        "category": "recovery_regeneration", "created_phase": "phase3_ecosystem"
    },
    {
        "id": "REC-017", "name": "Nutritional Timing — Post-Training Anabolic Window",
        "objective": "Maximize glycogen replenishment and muscle protein synthesis.",
        "system": "Recovery/Nutritional", "level": "All Levels",
        "environment": ["Any"], "duration": "Within 2 hours post-training",
        "work_description": "20-40g protein + 40-80g carbs within 30-60 min post-training.",
        "rest": "N/A", "sets": "1 meal/snack", "total_volume": "per session",
        "fatigue_score": -1, "tier": "A", "work_rest_ratio": "N/A",
        "sport_priority": {"cricket": "high", "tennis": "high", "badminton": "high", "football": "high"},
        "movement_profile": ["nutritional", "lifestyle"],
        "session_role": ["recovery", "muscle-repair", "glycogen-repletion"],
        "impact_level": "none", "eccentric_load": "none", "fatigue_cost": "negative",
        "equipment_need": "food_supplements", "field_space": "N/A",
        "phase_timing": ["year-round", "post-training"],
        "category": "recovery_regeneration", "created_phase": "phase3_ecosystem"
    },
    {
        "id": "REC-018", "name": "Complete Rest Day — Passive Recovery",
        "objective": "Allow full systemic recovery. Enable supercompensation.",
        "system": "Recovery/Lifestyle", "level": "All Levels",
        "environment": ["Any"], "duration": "Full day",
        "work_description": "No structured training. Light activity only. Focus on sleep, nutrition, hydration.",
        "rest": "All day", "sets": "1 day", "total_volume": "24 hours",
        "fatigue_score": -2, "tier": "A", "work_rest_ratio": "N/A",
        "sport_priority": {"cricket": "high", "tennis": "high", "badminton": "high", "football": "high"},
        "movement_profile": ["passive", "lifestyle"],
        "session_role": ["recovery", "deload", "supercompensation"],
        "impact_level": "none", "eccentric_load": "none", "fatigue_cost": "negative",
        "equipment_need": "none", "field_space": "N/A",
        "phase_timing": ["weekly", "deload-week", "post-competition"],
        "category": "recovery_regeneration", "created_phase": "phase3_ecosystem"
    },
    
    # ==================== INJURY PREVENTION (18 protocols) ====================
    {
        "id": "INJ-001", "name": "Nordic Hamstring Curl — Eccentric Strength",
        "objective": "Build eccentric hamstring strength to prevent strains.",
        "system": "Strength", "level": "Intermediate to Elite",
        "environment": ["Gym", "Field", "Indoor"], "duration": "10-12 min",
        "work_description": "Kneel, ankles secured. Slowly lower torso forward resisting gravity. Use hands to catch.",
        "rest": "60-90 sec", "sets": "3x5-8", "total_volume": "15-24 reps",
        "fatigue_score": 5, "tier": "A", "work_rest_ratio": "1:3",
        "sport_priority": {"cricket": "high", "tennis": "medium", "badminton": "medium", "football": "very_high"},
        "movement_profile": ["hip-hinge", "eccentric-dominant", "knee-flexion"],
        "session_role": ["injury-prevention", "strength", "hamstring-health"],
        "impact_level": "low", "eccentric_load": "very_high", "fatigue_cost": "moderate",
        "equipment_need": "partner_or_machine", "field_space": "mat_space",
        "phase_timing": ["year-round", "pre-season"],
        "category": "injury_prevention", "evidence_base": "50-70% hamstring strain reduction",
        "created_phase": "phase3_ecosystem"
    },
    {
        "id": "INJ-002", "name": "Copenhagen Plank — Adductor Strengthening",
        "objective": "Strengthen hip adductors to prevent groin strains.",
        "system": "Strength/Stability", "level": "Intermediate to Advanced",
        "environment": ["Gym", "Indoor"], "duration": "8-10 min",
        "work_description": "Side plank, top foot elevated. Hold position, hips lifted.",
        "rest": "60 sec", "sets": "3x20-40sec/side", "total_volume": "3-4 min holds",
        "fatigue_score": 4, "tier": "A", "work_rest_ratio": "1:2",
        "sport_priority": {"cricket": "medium", "tennis": "high", "badminton": "high", "football": "very_high"},
        "movement_profile": ["lateral", "isometric", "core-stability"],
        "session_role": ["injury-prevention", "groin-health", "stability"],
        "impact_level": "none", "eccentric_load": "low", "fatigue_cost": "moderate",
        "equipment_need": "bench_or_box", "field_space": "mat_space",
        "phase_timing": ["year-round", "pre-season"],
        "category": "injury_prevention", "evidence_base": "Strong adductor injury reduction",
        "created_phase": "phase3_ecosystem"
    },
    {
        "id": "INJ-003", "name": "Single-Leg Balance — Ankle Stability",
        "objective": "Improve proprioception and ankle stability to prevent sprains.",
        "system": "Stability/Proprioception", "level": "All Levels",
        "environment": ["Any"], "duration": "6-8 min",
        "work_description": "Stand on one leg 30-60 sec. Progress: eyes closed, unstable surface.",
        "rest": "30 sec", "sets": "3x/leg", "total_volume": "6-9 min",
        "fatigue_score": 2, "tier": "A", "work_rest_ratio": "1:1",
        "sport_priority": {"cricket": "high", "tennis": "high", "badminton": "high", "football": "high"},
        "movement_profile": ["balance", "proprioceptive", "single-leg"],
        "session_role": ["injury-prevention", "ankle-health", "proprioception"],
        "impact_level": "none", "eccentric_load": "minimal", "fatigue_cost": "low",
        "equipment_need": "optional_unstable_surface", "field_space": "minimal",
        "phase_timing": ["year-round", "daily"],
        "category": "injury_prevention", "evidence_base": "Strong ankle sprain prevention",
        "created_phase": "phase3_ecosystem"
    },
    {
        "id": "INJ-004", "name": "Rotator Cuff Strengthening — External Rotation",
        "objective": "Strengthen rotator cuff for shoulder health in overhead athletes.",
        "system": "Strength", "level": "All Levels",
        "environment": ["Gym", "Home"], "duration": "8-10 min",
        "work_description": "Elbow 90°, tucked. Rotate forearm upward with band/cable. Slow controlled.",
        "rest": "45 sec", "sets": "3x12-15/arm", "total_volume": "36-45 reps/arm",
        "fatigue_score": 3, "tier": "A", "work_rest_ratio": "1:2",
        "sport_priority": {"cricket": "very_high", "tennis": "very_high", "badminton": "very_high", "football": "medium"},
        "movement_profile": ["shoulder-rotation", "isolation", "scapular-health"],
        "session_role": ["injury-prevention", "shoulder-health", "overhead-athlete"],
        "impact_level": "none", "eccentric_load": "low", "fatigue_cost": "low",
        "equipment_need": "resistance_band_or_cable", "field_space": "minimal",
        "phase_timing": ["year-round", "2-3x weekly"],
        "category": "injury_prevention", "evidence_base": "Strong shoulder injury reduction",
        "created_phase": "phase3_ecosystem"
    },
    {
        "id": "INJ-005", "name": "ACL Prevention Program — Landing Mechanics",
        "objective": "Teach proper landing mechanics to reduce ACL injury risk.",
        "system": "Neuromuscular Training", "level": "All Levels",
        "environment": ["Gym", "Field", "Court"], "duration": "12-15 min",
        "work_description": "Drop jump from box. Land softly, knees bent, chest up, knees over toes.",
        "rest": "45-60 sec", "sets": "3x8-10", "total_volume": "24-30 landings",
        "fatigue_score": 4, "tier": "A", "work_rest_ratio": "1:4",
        "sport_priority": {"cricket": "medium", "tennis": "high", "badminton": "high", "football": "very_high"},
        "movement_profile": ["jumping", "landing", "deceleration"],
        "session_role": ["injury-prevention", "acl-health", "landing-mechanics"],
        "impact_level": "moderate", "eccentric_load": "high", "fatigue_cost": "moderate",
        "equipment_need": "box_or_platform", "field_space": "medium",
        "phase_timing": ["pre-season", "in-season", "year-round"],
        "category": "injury_prevention", "evidence_base": "50-80% ACL injury reduction",
        "created_phase": "phase3_ecosystem"
    },
    {
        "id": "INJ-006", "name": "Glute Medius Activation — Clamshells & Band Walks",
        "objective": "Activate glute medius to prevent knee valgus and improve hip stability.",
        "system": "Activation/Strength", "level": "All Levels",
        "environment": ["Gym", "Home", "Field"], "duration": "8-10 min",
        "work_description": "Clamshells + lateral band walks. Maintain tension throughout.",
        "rest": "45 sec", "sets": "3x15-20 + 10-15 steps/dir",
        "total_volume": "45-60 clamshells, 20-30 steps/dir",
        "fatigue_score": 3, "tier": "A", "work_rest_ratio": "1:2",
        "sport_priority": {"cricket": "high", "tennis": "high", "badminton": "high", "football": "high"},
        "movement_profile": ["hip-abduction", "activation", "lateral"],
        "session_role": ["injury-prevention", "activation", "hip-health"],
        "impact_level": "none", "eccentric_load": "low", "fatigue_cost": "low",
        "equipment_need": "resistance_band", "field_space": "mat_space",
        "phase_timing": ["year-round", "pre-workout"],
        "category": "injury_prevention", "evidence_base": "Strong knee injury prevention",
        "created_phase": "phase3_ecosystem"
    },
    {
        "id": "INJ-007", "name": "Wrist & Elbow Tendon Care — Grip Strengthening",
        "objective": "Prevent tennis/golfer's elbow and wrist tendinopathies.",
        "system": "Strength", "level": "All Levels",
        "environment": ["Gym", "Home"], "duration": "8-10 min",
        "work_description": "Wrist curls, pronation/supination, rice bucket digs, finger extensions.",
        "rest": "30 sec", "sets": "2-3x15-20", "total_volume": "8-12 min",
        "fatigue_score": 2, "tier": "A", "work_rest_ratio": "1:1",
        "sport_priority": {"cricket": "very_high", "tennis": "very_high", "badminton": "very_high", "football": "low"},
        "movement_profile": ["wrist-flexion-extension", "forearm-rotation", "grip"],
        "session_role": ["injury-prevention", "tendon-health", "overhead-athlete"],
        "impact_level": "none", "eccentric_load": "moderate", "fatigue_cost": "low",
        "equipment_need": "light_dumbbells_rice_bands", "field_space": "minimal",
        "phase_timing": ["year-round", "2-3x weekly"],
        "category": "injury_prevention", "evidence_base": "Moderate elbow/wrist injury reduction",
        "created_phase": "phase3_ecosystem"
    },
    {
        "id": "INJ-008", "name": "Core Anti-Rotation — Pallof Press",
        "objective": "Develop anti-rotational core strength to protect spine.",
        "system": "Core Stability", "level": "All Levels",
        "environment": ["Gym", "Home"], "duration": "8-10 min",
        "work_description": "Stand perpendicular to anchor. Press arms out, resist rotation. Hold 2-3 sec.",
        "rest": "45 sec", "sets": "3x10-12/side", "total_volume": "30-36 reps",
        "fatigue_score": 3, "tier": "A", "work_rest_ratio": "1:2",
        "sport_priority": {"cricket": "very_high", "tennis": "very_high", "badminton": "high", "football": "high"},
        "movement_profile": ["anti-rotation", "core-stability", "isometric"],
        "session_role": ["injury-prevention", "core-health", "spine-protection"],
        "impact_level": "none", "eccentric_load": "low", "fatigue_cost": "moderate",
        "equipment_need": "resistance_band_or_cable", "field_space": "small",
        "phase_timing": ["year-round", "2-3x weekly"],
        "category": "injury_prevention", "evidence_base": "Strong lower back injury prevention",
        "created_phase": "phase3_ecosystem"
    },
    {
        "id": "INJ-009", "name": "Achilles & Patellar Tendon Loading — Isometric Holds",
        "objective": "Build tendon resilience through isometric loading.",
        "system": "Tendon Health", "level": "All Levels",
        "environment": ["Gym", "Home", "Field"], "duration": "10-12 min",
        "work_description": "Spanish squat hold 30-45sec + single-leg calf raise hold 30-45sec.",
        "rest": "90 sec", "sets": "3-4 holds/exercise", "total_volume": "6-8 min holds",
        "fatigue_score": 4, "tier": "A", "work_rest_ratio": "1:3",
        "sport_priority": {"cricket": "high", "tennis": "high", "badminton": "very_high", "football": "high"},
        "movement_profile": ["isometric", "tendon-loading", "single-leg"],
        "session_role": ["injury-prevention", "tendon-health", "plyometric-prep"],
        "impact_level": "low", "eccentric_load": "moderate", "fatigue_cost": "moderate",
        "equipment_need": "band_wall", "field_space": "small",
        "phase_timing": ["year-round", "pre-plyometric"],
        "category": "injury_prevention", "evidence_base": "Strong tendinopathy prevention",
        "created_phase": "phase3_ecosystem"
    },
    {
        "id": "INJ-010", "name": "Hip Flexor Mobility — Couch Stretch",
        "objective": "Release tight hip flexors from prolonged sitting.",
        "system": "Mobility", "level": "All Levels",
        "environment": ["Gym", "Home"], "duration": "6-8 min",
        "work_description": "Kneel against wall/couch, posterior pelvic tilt, squeeze glute. Hold 2-3 min/side.",
        "rest": "Switch sides", "sets": "2-3 holds/side", "total_volume": "4-6 min/side",
        "fatigue_score": 2, "tier": "A", "work_rest_ratio": "N/A",
        "sport_priority": {"cricket": "high", "tennis": "high", "badminton": "high", "football": "high"},
        "movement_profile": ["hip-extension", "mobility", "stretching"],
        "session_role": ["injury-prevention", "mobility", "desk-athlete"],
        "impact_level": "none", "eccentric_load": "none", "fatigue_cost": "minimal",
        "equipment_need": "wall_or_couch", "field_space": "small",
        "phase_timing": ["year-round", "daily"],
        "category": "injury_prevention", "evidence_base": "Moderate hip health evidence",
        "created_phase": "phase3_ecosystem"
    },
    {
        "id": "INJ-011", "name": "Scapular Stabilization — YTWL Series",
        "objective": "Strengthen scapular stabilizers for shoulder health.",
        "system": "Strength/Stability", "level": "All Levels",
        "environment": ["Gym", "Home"], "duration": "10-12 min",
        "work_description": "Prone/standing: form Y, T, W, L with arms. Squeeze shoulder blades.",
        "rest": "30 sec", "sets": "2-3x10-12/letter", "total_volume": "40-48 reps/letter",
        "fatigue_score": 3, "tier": "A", "work_rest_ratio": "1:1",
        "sport_priority": {"cricket": "very_high", "tennis": "very_high", "badminton": "very_high", "football": "medium"},
        "movement_profile": ["scapular-retraction", "shoulder-health", "posture"],
        "session_role": ["injury-prevention", "shoulder-health", "posture-correction"],
        "impact_level": "none", "eccentric_load": "low", "fatigue_cost": "low",
        "equipment_need": "light_dumbbells_or_bands", "field_space": "small",
        "phase_timing": ["year-round", "2-3x weekly"],
        "category": "injury_prevention", "evidence_base": "Moderate-strong shoulder health",
        "created_phase": "phase3_ecosystem"
    },
    {
        "id": "INJ-012", "name": "Neck Strengthening — Isometric Holds",
        "objective": "Strengthen neck musculature to reduce concussion risk.",
        "system": "Strength", "level": "All Levels",
        "environment": ["Gym", "Home", "Field"], "duration": "6-8 min",
        "work_description": "Manual resistance in 4 directions: flexion, extension, lateral flexion. Hold 10-15sec.",
        "rest": "30 sec", "sets": "2-3/dir", "total_volume": "8-12 min",
        "fatigue_score": 3, "tier": "B", "work_rest_ratio": "1:2",
        "sport_priority": {"cricket": "low", "tennis": "low", "badminton": "low", "football": "very_high"},
        "movement_profile": ["isometric", "cervical-strength"],
        "session_role": ["injury-prevention", "concussion-reduction", "contact-sport"],
        "impact_level": "none", "eccentric_load": "none", "fatigue_cost": "low",
        "equipment_need": "manual_resistance", "field_space": "minimal",
        "phase_timing": ["year-round", "pre-season", "contact-sports"],
        "category": "injury_prevention", "evidence_base": "Emerging concussion reduction",
        "created_phase": "phase3_ecosystem"
    },
    {
        "id": "INJ-013", "name": "Adductor Strengthening — Progressive Squeeze",
        "objective": "Build adductor strength progressively to prevent groin strains.",
        "system": "Strength", "level": "All Levels",
        "environment": ["Gym", "Home"], "duration": "8-10 min",
        "work_description": "Supine, ball between knees. Squeeze progressively: 25%, 50%, 75%, 100% effort.",
        "rest": "30 sec", "sets": "3-4 series", "total_volume": "12-16 min",
        "fatigue_score": 3, "tier": "A", "work_rest_ratio": "progressive",
        "sport_priority": {"cricket": "medium", "tennis": "high", "badminton": "high", "football": "very_high"},
        "movement_profile": ["hip-adduction", "isometric", "progressive-overload"],
        "session_role": ["injury-prevention", "groin-health", "adductor-strength"],
        "impact_level": "none", "eccentric_load": "none", "fatigue_cost": "low",
        "equipment_need": "ball_or_bolster", "field_space": "mat_space",
        "phase_timing": ["year-round", "pre-season"],
        "category": "injury_prevention", "evidence_base": "Strong groin injury prevention",
        "created_phase": "phase3_ecosystem"
    },
    {
        "id": "INJ-014", "name": "Thoracic Spine Rotation — Open Book",
        "objective": "Improve thoracic rotation mobility. Prevent compensatory lumbar rotation.",
        "system": "Mobility", "level": "All Levels",
        "environment": ["Home", "Gym"], "duration": "6-8 min",
        "work_description": "Side-lying, knees bent 90°. Rotate top arm open, follow with eyes. 10-12 reps/side.",
        "rest": "30 sec", "sets": "2-3/side", "total_volume": "20-36 reps",
        "fatigue_score": 1, "tier": "A", "work_rest_ratio": "1:1",
        "sport_priority": {"cricket": "high", "tennis": "high", "badminton": "high", "football": "medium"},
        "movement_profile": ["thoracic-rotation", "mobility", "spinal-health"],
        "session_role": ["injury-prevention", "mobility", "rotational-health"],
        "impact_level": "none", "eccentric_load": "none", "fatigue_cost": "minimal",
        "equipment_need": "none", "field_space": "mat_space",
        "phase_timing": ["year-round", "daily"],
        "category": "injury_prevention", "evidence_base": "Moderate thoracic mobility evidence",
        "created_phase": "phase3_ecosystem"
    },
    {
        "id": "INJ-015", "name": "Foot Intrinsic Strengthening — Towel Scrunches",
        "objective": "Strengthen intrinsic foot muscles. Prevent plantar fasciitis.",
        "system": "Strength", "level": "All Levels",
        "environment": ["Home", "Gym"], "duration": "6-8 min",
        "work_description": "Towel scrunches with toes + short foot exercise (doming).",
        "rest": "30 sec", "sets": "3x15-20 + 10-15 holds",
        "total_volume": "45-60 scrunches, 30-45 doming",
        "fatigue_score": 2, "tier": "B", "work_rest_ratio": "1:1",
        "sport_priority": {"cricket": "high", "tennis": "high", "badminton": "high", "football": "high"},
        "movement_profile": ["foot-intrinsic", "arch-support", "barefoot"],
        "session_role": ["injury-prevention", "foot-health", "plantar-fasciitis-prevention"],
        "impact_level": "none", "eccentric_load": "none", "fatigue_cost": "minimal",
        "equipment_need": "towel_marbles", "field_space": "minimal",
        "phase_timing": ["year-round", "daily"],
        "category": "injury_prevention", "evidence_base": "Emerging plantar fasciitis prevention",
        "created_phase": "phase3_ecosystem"
    },
    {
        "id": "INJ-016", "name": "Hamstring Bridge — Glute-Ham Integration",
        "objective": "Integrate glute and hamstring function. Prevent hamstring strains.",
        "system": "Strength", "level": "All Levels",
        "environment": ["Gym", "Home"], "duration": "8-10 min",
        "work_description": "Supine, drive hips up squeezing glutes. Progress to single-leg. Hold 2-3 sec.",
        "rest": "45 sec", "sets": "3x12-15 (double), 8-10 (single)",
        "total_volume": "36-45 double, 24-30 single",
        "fatigue_score": 4, "tier": "A", "work_rest_ratio": "1:2",
        "sport_priority": {"cricket": "high", "tennis": "high", "badminton": "high", "football": "very_high"},
        "movement_profile": ["hip-extension", "glute-activation", "posterior-chain"],
        "session_role": ["injury-prevention", "hamstring-health", "glute-activation"],
        "impact_level": "low", "eccentric_load": "moderate", "fatigue_cost": "moderate",
        "equipment_need": "optional_ball", "field_space": "mat_space",
        "phase_timing": ["year-round", "pre-season"],
        "category": "injury_prevention", "evidence_base": "Strong hamstring injury prevention",
        "created_phase": "phase3_ecosystem"
    },
    {
        "id": "INJ-017", "name": "Shoulder CARs — Controlled Articular Rotations",
        "objective": "Maintain shoulder joint health through full ROM exploration.",
        "system": "Mobility", "level": "All Levels",
        "environment": ["Any"], "duration": "6-8 min",
        "work_description": "Largest possible arm circles, slow controlled. Keep torso still. 5-8 reps/dir/arm.",
        "rest": "30 sec", "sets": "2/dir", "total_volume": "20-32 rotations",
        "fatigue_score": 1, "tier": "A", "work_rest_ratio": "continuous",
        "sport_priority": {"cricket": "very_high", "tennis": "very_high", "badminton": "very_high", "football": "medium"},
        "movement_profile": ["shoulder-rotation", "joint-health", "mobility"],
        "session_role": ["injury-prevention", "joint-health", "warmup-prep"],
        "impact_level": "none", "eccentric_load": "none", "fatigue_cost": "minimal",
        "equipment_need": "none", "field_space": "minimal",
        "phase_timing": ["year-round", "daily"],
        "category": "injury_prevention", "evidence_base": "Emerging joint health evidence",
        "created_phase": "phase3_ecosystem"
    },
    {
        "id": "INJ-018", "name": "Comprehensive Dynamic Warm-up — FIFA 11+ Adapted",
        "objective": "Complete warm-up protocol proven to reduce injuries 30-50%.",
        "system": "Warm-up", "level": "All Levels",
        "environment": ["Field", "Court"], "duration": "15-20 min",
        "work_description": "Running exercises, strength/balance, jumping/plyometrics circuit.",
        "rest": "Minimal", "sets": "1 circuit", "total_volume": "15-20 min",
        "fatigue_score": 3, "tier": "A", "work_rest_ratio": "circuit",
        "sport_priority": {"cricket": "high", "tennis": "high", "badminton": "high", "football": "very_high"},
        "movement_profile": ["comprehensive", "dynamic", "multi-planar"],
        "session_role": ["injury-prevention", "warmup", "preparation"],
        "impact_level": "low-moderate", "eccentric_load": "low", "fatigue_cost": "low",
        "equipment_need": "minimal", "field_space": "medium",
        "phase_timing": ["year-round", "pre-training", "pre-competition"],
        "category": "injury_prevention", "evidence_base": "Very strong - 30-50% injury reduction",
        "created_phase": "phase3_ecosystem"
    },
]

# Save intermediate result
with open('complete_conditioning_library_phase3_part1.json', 'w') as f:
    json.dump(existing_protocols + phase3_protocols, f, indent=2)

print(f"Part 1 complete: {len(existing_protocols) + len(phase3_protocols)} protocols")
print("Saved to complete_conditioning_library_phase3_part1.json")
