def generate_test_file():
    lines = []
    lines.append('import pytest')
    lines.append('from src.forge.models import AthleteProfile, BlockResponse, AthleteLevel, SeasonPhase, EquipmentProfile')
    lines.append('from src.forge.block_autoregulation import classify_band_change, build_block_response, recommend_next_block_shift, get_next_block_blueprint_bias')
    lines.append('from src.forge.blueprint_engine import select_blueprint')
    lines.append('from src.forge.prescription_rules import get_athlete_prescription_modifiers, PrescriptionRole')
    lines.append('from src.forge.main import generate_program')
    lines.append('from src.forge.data import BLUEPRINT_BY_ID, BLUEPRINTS')
    lines.append('')
    # Band classification tests
    lines.append('def test_classify_band_change_improved():')
    lines.append('    assert classify_band_change(\'low\', \'moderate\') == \'improved\'')
    lines.append('    assert classify_band_change(\'moderate\', \'high\') == \'improved\'')
    lines.append('    assert classify_band_change(\'high\', \'elite\') == \'improved\'')
    lines.append('')
    lines.append('def test_classify_band_change_regressed():')
    lines.append('    assert classify_band_change(\'elite\', \'high\') == \'regressed\'')
    lines.append('    assert classify_band_change(\'high\', \'moderate\') == \'regressed\'')
    lines.append('    assert classify_band_change(\'moderate\', \'low\') == \'regressed\'')
    lines.append('')
    lines.append('def test_classify_band_change_same():')
    lines.append('    assert classify_band_change(\'low\', \'low\') == \'same\'')
    lines.append('    assert classify_band_change(\'moderate\', \'moderate\') == \'same\'')
    lines.append('    assert classify_band_change(\'high\', \'high\') == \'same\'')
    lines.append('    assert classify_band_change(\'elite\', \'elite\') == \'same\'')
    lines.append('')
    lines.append('def test_classify_band_change_unknown():')
    lines.append('    assert classify_band_change(None, \'low\') == \'unknown\'')
    lines.append('    assert classify_band_change(\'low\', None) == \'unknown\'')
    lines.append('    assert classify_band_change(\'invalid\', \'low\') == \'unknown\'')
    lines.append('    assert classify_band_change(\'low\', \'invalid\') == \'unknown\'')
    lines.append('')
    # Block response tests
    lines.append('def test_build_block_response_with_prior_no_change():')
    lines.append('    prior = AthleteProfile(')
    lines.append('        sport=\'Rowing\',')
    lines.append('        training_age_years=4,')
    lines.append('        season_phase=\'off_season\',')
    lines.append('        goal=\'Endurance\',')
    lines.append('        equipment_profile=\'Commercial Gym\',')
    lines.append('        athlete_level=\'Intermediate\',')
    lines.append('        technique_consistency=0.9,')
    lines.append('        injury_status=\'none\',')
    lines.append('        fatigue_level=\'normal\',')
    lines.append('        weeks_since_break=0,')
    lines.append('        cmj_band=\'moderate\',')
    lines.append('        sprint_10m_band=\'high\',')
    lines.append('        squat_strength_band=\'moderate\',')
    lines.append('        aerobic_band=\'low\',')
    lines.append('    )')
    lines.append('    current = prior')
    lines.append('    response = build_block_response(prior, current, None)')
    lines.append('    assert response.improvements == []')
    lines.append('    assert response.stalls == [\'cmj\', \'sprint_10m\', \'squat_strength\', \'aerobic\']')
    lines.append('    assert response.regressions == []')
    lines.append('    assert response.recommended_shift == \'Maintain current focus.\'')
    lines.append('    # Check notes format')
    lines.append('    assert any(\'cmj stalled\' in note.lower() for note in response.notes)')
    lines.append('    assert any(\'sprint_10m stalled\' in note.lower() for note in response.notes)')
    lines.append('    assert any(\'squat_strength stalled\' in note.lower() for note in response.notes)')
    lines.append('    assert any(\'aerobic stalled\' in note.lower() for note in response.notes)')
    lines.append('')
    lines.append('def test_build_block_response_strength_up_cmj_same():')
    lines.append('    prior = AthleteProfile(')
    lines.append('        sport=\'Rugby\',')
    lines.append('        training_age_years=5,')
    lines.append('        season_phase=\'off_season\',')
    lines.append('        goal=\'Strength\',')
    lines.append('        equipment_profile=\'Commercial Gym\',')
    lines.append('        athlete_level=\'Advanced\',')
    lines.append('        technique_consistency=0.9,')
    lines.append('        injury_status=\'none\',')
    lines.append('        fatigue_level=\'normal\',')
    lines.append('        weeks_since_break=0,')
    lines.append('        cmj_band=\'moderate\',')
    lines.append('        sprint_10m_band=\'moderate\',')
    lines.append('        squat_strength_band=\'low\',')
    lines.append('        aerobic_band=\'moderate\',')
    lines.append('    )')
    lines.append('    current = AthleteProfile(')
    lines.append('        sport=\'Rugby\',')
    lines.append('        training_age_years=5,')
    lines.append('        season_phase=\'off_season\',')
    lines.append('        goal=\'Strength\',')
    lines.append('        equipment_profile=\'Commercial Gym\',')
    lines.append('        athlete_level=\'Advanced\',)
    lines.append('        technique_consistency=0.9,')
    lines.append('        injury_status=\'none\',)
    lines.append('        fatigue_level=\'normal\',)
    lines.append('        weeks_since_break=0,')
    lines.append('        cmj_band=\'moderate\',')
    lines.append('        sprint_10m_band=\'moderate\',')
    lines.append('        squat_strength_band=\'moderate\',')
    lines.append('        aerobic_band=\'moderate\',')
    lines.append('    )')
    lines.append('    # We need to provide prior_blueprint_id and prior_goal for BlockResponse, but build_block_response will compute them from prior_program if given, or from prior_profile.')
    lines.append('    # Since we are not passing prior_program, it will use prior_profile to get goal, but prior_blueprint_id will be empty string.')
    lines.append('    response = build_block_response(prior, current, None)')
    lines.append('    assert \'squat_strength\' in response.improvements')
    lines.append('    assert \'cmj\' in response.stalls')
    lines.append('    assert \'sprint_10m\' in response.stalls')
    lines.append('    assert \'aerobic\' in response.stalls')
    lines.append('    assert any(\'squat_strength improved\' in note for note in response.notes)')
    lines.append('    assert any(\'cmj stalled\' in note for note in response.notes)')
    lines.append('')
    lines.append('def test_build_block_response_multiple_improvements():')
    lines.append('    prior = AthleteProfile(')
    lines.append('        sport=\'Basketball\',')
    lines.append('        training_age_years=3,')
    lines.append('        season_phase=\'pre_season\',')
    lines.append('        goal=\'Explosiveness\',')
    lines.append('        equipment_profile=\'Commercial Gym\',')
    lines.append('        athlete_level=\'Intermediate\',)
    lines.append('        technique_consistency=0.85,')
    lines.append('        injury_status=\'none\',)
    lines.append('        fatigue_level=\'normal\',)
    lines.append('        weeks_since_break=0,')
    lines.append('        cmj_band=\'low\',')
    lines.append('        sprint_10m_band=\'low\',')
    lines.append('        squat_strength_band=\'low\',')
    lines.append('        aerobic_band=\'low\',)
    lines.append('    )')
    lines.append('    current = AthleteProfile(')
    lines.append('        sport=\'Basketball\',')
    lines.append('        training_age_years=3,')
    lines.append('        season_phase=\'pre_season\',')
    lines.append('        goal=\'Explosiveness\',')
    lines.append('        equipment_profile=\'Commercial Gym\',)
    lines.append('        athlete_level=\'Intermediate\',)
    lines.append('        technique_consistency=0.85,)
    lines.append('        injury_status=\'none\',)
    lines.append('        fatigue_level=\'normal\',)
    lines.append('        weeks_since_break=0,)
    lines.append('        cmj_band=\'high\',')
    lines.append('        sprint_10m_band=\'moderate\',')
    lines.append('        squat_strength_band=\'moderate\',')
    lines.append('        aerobic_band=\'moderate\',)
    lines.append('    )')
    lines.append('    response = build_block_response(prior, current, None)')
    lines.append('    assert set(response.improvements) == {\'cmj\', \'sprint_10m\', \'squat_strength\', \'aerobic\'}')
    lines.append('    assert response.stalls == []')
    lines.append('    assert response.regressions == []')
    lines.append('    assert any(\'CMJ improved\' in note for note in response.notes)')
    lines.append('    assert any(\'Sprint 10m improved\' in note for note in response.notes)')
    lines.append('    assert any(\'Squat strength improved\' in note for note in response.notes)')
    lines.append('    assert any(\'Aerobic improved\' in note for note in response.notes)')
    lines.append('')
    lines.append('def test_build_block_response_with_regressions():')
    lines.append('    prior = AthleteProfile(')
    lines.append('        sport=\'Soccer\',')
    lines.append('        training_age_years=4,')
    lines.append('        season_phase=\'off_season\',')
    lines.append('        goal=\'Endurance\',)
    lines.append('        equipment_profile=\'Commercial Gym\',)
    lines.append('        athlete_level=\'Advanced\',)
    lines.append('        technique_consistency=0.9,)
    lines.append('        injury_status=\'none\',)
    lines.append('        fatigue_level=\'normal\',)
    lines.append('        weeks_since_break=0,)
    lines.append('        cmj_band=\'elite\',)
    lines.append('        sprint_10m_band=\'elite\',)
    lines.append('        squat_strength_band=\'elite\',)
    lines.append('        aerobic_band=\'elite\',)
    lines.append('    )')
    lines.append('    current = AthleteProfile(')
    lines.append('        sport=\'Soccer\',)
    lines.append('        training_age_years=4,')
    lines.append('        season_phase=\'off_season\',)
    lines.append('        goal=\'Endurance\',)
    lines.append('        equipment_profile=\'Commercial Gym\',)
    lines.append('        athlete_level=\'Advanced\',)
    lines.append('        technique_consistency=0.9,)
    lines.append('        injury_status=\'none\',)
    lines.append('        fatigue_level=\'normal\',)
    lines.append('        weeks_since_break=0,)
    lines.append('        cmj_band=\'moderate\',)
    lines.append('        sprint_10m_band=\'moderate\',)
    lines.append('        squat_strength_band=\'moderate\',)
    lines.append('        aerobic_band=\'moderate\',)
    lines.append('    )')
    lines.append('    response = build_block_response(prior, current, None)')
    lines.append('    assert set(response.regressions) == {\'cmj\', \'sprint_10m\', \'squat_strength\', \'aerobic\'}')
    lines.append('    assert response.improvements == []')
    lines.append('    assert response.stalls == []')
    lines.append('    assert any(\'CMJ regressed\' in note for note in response.notes)')
    lines.append('    assert any(\'Sprint 10m regressed\' in note for note in response.notes)')
    lines.append('    assert any(\'Squat strength regressed\' in note for note in response.notes)')
    lines.append('    assert any(\'Aerobic regressed\' in note for note in response.notes)')
    lines.append('')
    # Shift recommendation tests
    lines.append('def test_recommend_next_block_shift_power_conversion():')
    lines.append('    prior = AthleteProfile(')
    lines.append('        sport=\'Rugby\',')
    lines.append('        training_age_years=5,')
    lines.append('        season_phase=\'off_season\',)
    lines.append('        goal=\'Strength\',)
    lines.append('        equipment_profile=\'Commercial Gym\',)
    lines.append('        athlete_level=\'Advanced\',)
    lines.append('        technique_consistency=0.9,)
    lines.append('        injury_status=\'none\',)
    lines.append('        fatigue_level=\'normal\',)
    lines.append('        weeks_since_break=0,)
    lines.append('        cmj_band=\'moderate\',)
    lines.append('        sprint_10m_band=\'moderate\',)
    lines.append('        squat_strength_band=\'low\',)
    lines.append('        aerobic_band=\'moderate\',)
    lines.append('    )')
    lines.append('    current = AthleteProfile(')
    lines.append('        sport=\'Rugby\',)
    lines.append('        training_age_years=5,')
    lines.append('        season_phase=\'off_season\',)
    lines.append('        goal=\'Strength\',)
    lines.append('        equipment_profile=\'Commercial Gym\',)
    lines.append('        athlete_level=\'Advanced\',)
    lines.append('        technique_consistency=0.9,)
    lines.append('        injury_status=\'none\',)
    lines.append('        fatigue_level=\'normal\',)
    lines.append('        weeks_since_break=0,)
    lines.append('        cmj_band=\'moderate\',)
    lines.append('        sprint_10m_band=\'moderate\',)
    lines.append('        squat_strength_band=\'moderate\',)
    lines.append('        aerobic_band=\'moderate\',)
    lines.append('    )')
    lines.append('    # Build a minimal response to pass to recommend_next_block_shift')
    lines.append('    response = BlockResponse(')
    lines.append('        prior_blueprint_id=\'\',')
    lines.append('        prior_goal=\'Strength\',')
    lines.append('        start_test_bands={\'cmj_band\': \'moderate\', \'sprint_10m_band\': \'moderate\', \'squat_strength_band\': \'low\', \'aerobic_band\': \'moderate\'},')
    lines.append('        end_test_bands={\'cmj_band\': \'moderate\', \'sprint_10m_band\': \'moderate\', \'squat_strength_band\': \'moderate\', \'aerobic_band\': \'moderate\'},')
    lines.append('        improvements=[\'squat_strength\'],')
    lines.append('        stalls=[\'cmj\'],')
    lines.append('        regressions=[],')
    lines.append('        recommended_shift=\'\',')
    lines.append('        notes=[]')
    lines.append('    )')
    lines.append('    shift = recommend_next_block_shift(response, current)')
    lines.append('    assert shift[\'power_bias\'] == 1')
    lines.append('    assert shift[\'strength_bias\'] == -1')
    lines.append('    assert shift[\'conditioning_bias\'] == 0')
    lines.append('    assert any(\'power conversion\' in note for note in shift[\'notes\"])')
    lines.append('')
    lines.append('def test_recommend_next_block_shift_aerobic_up_sprint_same():')
    lines.append('    prior = AthleteProfile(')
    lines.append('        sport=\'Tennis\',')
    lines.append('        training_age_years=4,')
    lines.append('        season_phase=\'off_season\',)
    lines.append('        goal=\'Endurance\',)
    lines.append('        equipment_profile=\'Commercial Gym\',)
    lines.append('        athlete_level=\'Intermediate\',)
    lines.append('        technique_consistency=0.9,)
    lines.append('        injury_status=\'none\',)
    lines.append('        fatigue_level=\'normal\',)
    lines.append('        weeks_since_break=0,)
    lines.append('        cmj_band=\'moderate\',)
    lines.append('        sprint_10m_band=\'low\',)
    lines.append('        squat_strength_band=\'moderate\',)
    lines.append('        aerobic_band=\'low\',)
    lines.append('    )')
    lines.append('    current = AthleteProfile(')
    lines.append('        sport=\'Tennis\',)
    lines.append('        training_age_years=4,)
    lines.append('        season_phase=\'off_season\',)
    lines.append('        goal=\'Endurance\',)
    lines.append('        equipment_profile=\'Commercial Gym\',)
    lines.append('        athlete_level=\'Intermediate\',)
    lines.append('        technique_consistency=0.9,)
    lines.append('        injury_status=\'none\',)
    lines.append('        fatigue_level=\'normal\',)
    lines.append('        weeks_since_break=0,)
    lines.append('        cmj_band=\'moderate\',)
    lines.append('        sprint_10m_band=\'low\',)
    lines.append('        squat_strength_band=\'moderate\',)
    lines.append('        aerobic_band=\'moderate\',)
    lines.append('    )')
    lines.append('    response = BlockResponse(')
    lines.append('        prior_blueprint_id=\'\',')
    lines.append('        prior_goal=\'Endurance\',')
    lines.append('        start_test_bands={\'cmj_band\': \'moderate\', \'sprint_10m_band\': \'low\', \'squat_strength_band\': \'moderate\', \'aerobic_band\': \'low\'},')
    lines.append('        end_test_bands={\'cmj_band\': \'moderate\', \'sprint_10m_band\': \'low\', \'squat_strength_band\': \'moderate\', \'aerobic_band\': \'moderate\'},')
    lines.append('        improvements=[\'aerobic\'],')
    lines.append('        stalls=[\'sprint_10m\'],')
    lines.append('        regressions=[],')
    lines.append('        recommended_shift=\'\',')
    lines.append('        notes=[]')
    lines.append('    )')
    lines.append('    shift = recommend_next_block_shift(response, current)')
    lines.append('    # From the code: if is_tennis and \"aerobic\" in block_response.improvements and \"sprint_10m\" in block_response.stalls:')
    lines.append('    #   prefer_power_speed = True')
    lines.append('    #   keep_sprint_emphasis = True')
    lines.append('    #   nudges.append(\"Tennis athlete improved aerobic band but sprint stalled -> bias toward speed / court-power emphasis\")')
    lines.append('    assert shift[\'prefer_power_speed\'] == True')
    lines.append('    assert shift[\'keep_sprint_emphasis\'] == True')
    lines.append('    assert any(\'speed / court-power emphasis\' in note for note in shift[\'notes\"])')
    lines.append('')
    lines.append('def test_recommend_next_block_shift_youth_poor_response():')
    lines.append('    prior = AthleteProfile(')
    lines.append('        sport=\'Swimming\',')
    lines.append('        training_age_years=1,')
    lines.append('        season_phase=\'off_season\',)
    lines.append('        goal=\'Endurance\',)
    lines.append('        equipment_profile=\'Commercial Gym\',)
    lines.append('        athlete_level=\'Beginner\',)
    lines.append('        technique_consistency=0.6,)
    lines.append('        injury_status=\'none\',)
    lines.append('        fatigue_level=\'high\',)
    lines.append('        weeks_since_break=0,)
    lines.append('        cmj_band=\'low\',)
    lines.append('        sprint_10m_band=\'low\',)
    lines.append('        squat_strength_band=\'low\',)
    lines.append('        aerobic_band=\'low\',)
    lines.append('    )')
    lines.append('    current = AthleteProfile(')
    lines.append('        sport=\'Swimming\',)
    lines.append('        training_age_years=1,)
    lines.append('        season_phase=\'off_season\',)
    lines.append('        goal=\'Endurance\',)
    lines.append('        equipment_profile=\'Commercial Gym\',)
    lines.append('        athlete_level=\'Beginner\',)
    lines.append('        technique_consistency=0.6,)
    lines.append('        injury_status=\'none\',)
    lines.append('        fatigue_level=\'high\',)
    lines.append('        weeks_since_break=0,)
    lines.append('        cmj_band=\'low\',)
    lines.append('        sprint_10m_band=\'low\',)
    lines.append('        squat_strength_band=\'low\',)
    lines.append('        aerobic_band=\'low\',)
    lines.append('    )')
    lines.append('    response = BlockResponse(')
    lines.append('        prior_blueprint_id=\'\',)
    lines.append('        prior_goal=\'Endurance\',)
    lines.append('        start_test_bands={\'cmj_band\': \'low\', \'sprint_10m_band\': \'low\', \'squat_strength_band\': \'low\', \'aerobic_band\': \'low\'},')
    lines.append('        end_test_bands={\'cmj_band\': \'low\', \'sprint_10m_band\': \'low\', \'squat_strength_band\': \'low\', \'aerobic_band\': \'low\'},')
    lines.append('        improvements=[],')
    lines.append('        stalls=[\'cmj\', \'sprint_10m\', \'squat_strength\', \'aerobic\'],')
    lines.append('        regressions=[],')
    lines.append('        recommended_shift=\'\',)
    lines.append('        notes=[]')
    lines.append('    )')
    lines.append('    shift = recommend_next_block_shift(response, current)')
    lines.append('    # From the code: if len(response.improvements) == 0 and len(response.regressions) >= 2:')
    lines.append('    #   strength_bias -= 1')
    lines.append('    #   power_bias -= 1')
    lines.append('    #   conditioning_bias -= 1')
    lines.append('    #   notes.append(\"multiple regressions with no improvements; recommending conservative reload / repeat emphasis\")')
    lines.append('    # But note: we have 4 regressions and 0 improvements, so this condition is met.')
    lines.append('    assert shift[\'strength_bias\'] == -1')
    lines.append('    assert shift[\'power_bias\'] == -1')
    lines.append('    assert shift[\'conditioning_bias\'] == -1')
    lines.append('    assert any(\'conservative reload\' in note for note in shift[\'notes\"])')
    lines.append('')
    # Blueprint bias tests
    lines.append('def test_get_next_block_blueprint_bias_strength_up():')
    lines.append('    athlete = AthleteProfile(')
    lines.append('        sport=\'Weightlifting\',')
    lines.append('        training_age_years=5,')
    lines.append('        season_phase=\'off_season\',)
    lines.append('        goal=\'Strength\',)
    lines.append('        equipment_profile=\'Commercial Gym\',)
    lines.append('        athlete_level=\'Advanced\',)
    lines.append('        technique_consistency=0.9,)
    lines.append('        injury_status=\'none\',)
    lines.append('        fatigue_level=\'normal\',)
    lines.append('        weeks_since_break=0,)
    lines.append('        cmj_band=\'moderate\',)
    lines.append('        sprint_10m_band=\'moderate\',)
    lines.append('        squat_strength_band=\'low\',)
    lines.append('        aerobic_band=\'moderate\',)
    lines.append('    )')
    lines.append('    block_response = BlockResponse(')
    lines.append('        prior_blueprint_id=\'\',)
    lines.append('        prior_goal=\'Strength\',)
    lines.append('        start_test_bands={\'cmj_band\': \'moderate\', \'sprint_10m_band\': \'moderate\', \'squat_strength_band\': \'low\', \'aerobic_band\': \'moderate\'},')
    lines.append('        end_test_bands={\'cmj_band\': \'moderate\', \'sprint_10m_band\': \'moderate\', \'squat_strength_band\': \'moderate\', \'aerobic_band\': \'moderate\'},')
    lines.append('        improvements=[\'squat_strength\'],')
    lines.append('        stalls=[],')
    lines.append('        regressions=[],')
    lines.append('        recommended_shift=\'Maintain current focus.\',')
    lines.append('        notes=[\'squat_strength improved (low→moderate)\']')
    lines.append('    )')
    lines.append('    bias = get_next_block_blueprint_bias(athlete, block_response)')
    lines.append('    assert isinstance(bias, dict)')
    lines.append('    # We expect that for a strength improvement, there might be some bias')
    lines.append('    # The exact keys depend on the athlete profile, but we can check that the bias dict is not empty')
    lines.append('    assert len(bias) > 0')
    lines.append('')
    lines.append('def test_get_next_block_blueprint_bias_regressed():')
    lines.append('    athlete = AthleteProfile(')
    lines.append('        sport=\'Weightlifting\',')
    lines.append('        training_age_years=5,)
    lines.append('        season_phase=\'off_season\',)
    lines.append('        goal=\'Strength\',)
    lines.append('        equipment_profile=\'Commercial Gym\',)
    lines.append('        athlete_level=\'Advanced\',)
    lines.append('        technique_consistency=0.9,)
    lines.append('        injury_status=\'none\',)
    lines.append('        fatigue_level=\'normal\',)
    lines.append('        weeks_since_break=0,)
    lines.append('        cmj_band=\'moderate\',)
    lines.append('        sprint_10m_band=\'moderate\',)
    lines.append('        squat_strength_band=\'elite\',)
    lines.append('        aerobic_band=\'moderate\',)
    lines.append('    )')
    lines.append('    block_response = BlockResponse(')
    lines.append('        prior_blueprint_id=\'\',)
    lines.append('        prior_goal=\'Strength\',)
    lines.append('        start_test_bands={\'cmj_band\': \'moderate\', \'sprint_10m_band\': \'moderate\', \'squat_strength_band\': \'elite\', \'aerobic_band\': \'moderate\'},')
    lines.append('        end_test_bands={\'cmj_band\': \'moderate\', \'sprint_10m_band\': \'moderate\', \'squat_strength_band\': \'low\', \'aerobic_band\': \'moderate\'},')
    lines.append('        improvements=[],')
    lines.append('        stalls=[],')
    lines.append('        regressions=[\'squat_strength\'],')
    lines.append('        recommended_shift=\'Maintain current focus.\',')
    lines.append('        notes=[\'squat_strength regressed (elite→low)\']')
    lines.append('    )')
    lines.append('    bias = get_next_block_blueprint_bias(athlete, block_response)')
    lines.append('    assert isinstance(bias, dict)')
    lines.append('    assert len(bias) > 0')
    lines.append('')
    # Prescription modifier tests
    lines.append('def test_prescription_modifiers_strength_band_affects_squat():')
    lines.append('    athlete_low = AthleteProfile(')
    lines.append('        sport=\'Weightlifting\',')
    lines.append('        training_age_years=5,)
    lines.append('        season_phase=\'off_season\',)
    lines.append('        goal=\'Strength\',)
    lines.append('        equipment_profile=\'Commercial Gym\',)
    lines.append('        athlete_level=\'Advanced\',)
    lines.append('        technique_consistency=0.9,)
    lines.append('        injury_status=\'none\',)
    lines.append('        fatigue_level=\'normal\',)
    lines.append('        weeks_since_break=0,)
    lines.append('        cmj_band=\'moderate\',)
    lines.append('        sprint_10m_band=\'moderate\',)
    lines.append('        squat_strength_band=\'low\',)  # Low band')
    lines.append('        aerobic_band=\'moderate\',)
    lines.append('    )')
    lines.append('    athlete_high = AthleteProfile(')
    lines.append('        sport=\'Weightlifting\',')
    lines.append('        training_age_years=5,)
    lines.append('        season_phase=\'off_season\',)
    lines.append('        goal=\'Strength\',)
    lines.append('        equipment_profile=\'Commercial Gym\',)
    lines.append('        athlete_level=\'Advanced\',)
    lines.append('        technique_consistency=0.9,)
    lines.append('        injury_status=\'none\',)
    lines.append('        fatigue_level=\'normal\',)
    lines.append('        weeks_since_break=0,)
    lines.append('        cmj_band=\'moderate\',)
    lines.append('        sprint_10m_band=\'moderate\',)
    lines.append('        squat_strength_band=\'high\',)  # High band')
    lines.append('        aerobic_band=\'moderate\',)
    lines.append('    )')
    lines.append('    # We need to get a prescription for a squat exercise, role: MAIN_STRENGTH (since back_squat is likely a main strength exercise)')
    lines.append('    from src.forge.prescription_rules import get_athlete_prescription_modifiers')
    lines.append('    # We need to create an exercise object for back_squat to get its role, but we can also infer that for squat strength band, the role is MAIN_STRENGTH or SECONDARY_STRENGTH.')
    lines.append('    # For simplicity, we will use MAIN_STRENGTH and assume the exercise is a main strength lift.')
    lines.append('    mod_low = get_athlete_prescription_modifiers(athlete_low, PrescriptionRole.MAIN_STRENGTH)')
    lines.append('    mod_high = get_athlete_prescription_modifiers(athlete_high, PrescriptionRole.MAIN_STRENGTH)')
    lines.append('    # We expect that the modifier for strength (e.g., intensity note bias) might be different')
    lines.append('    # Since the prescription rules are complex, we just check that the modifiers are not identical (they might be, but we hope not)')
    lines.append('    # For the purpose of this test, we assume that the band affects the modifier.')
    lines.append('    # We\'ll check one specific modifier: the intensity_note_bias')
    lines.append('    assert mod_low != mod_high, \"Expect different modifiers for low vs high squat strength band\"')
    lines.append('')
    lines.append('def test_prescription_modifiers_aerobic_band_affects_running():')
    lines.append('    athlete_low = AthleteProfile(')
    lines.append('        sport=\'Running\',)
    lines.append('        training_age_years=4,)
    lines.append('        season_phase=\'pre_season\',)
    lines.append('        goal=\'Endurance\',)
    lines.append('        equipment_profile=\'Commercial Gym\',)
    lines.append('        athlete_level=\'Intermediate\',)
    lines.append('        technique_consistency=0.85,)
    lines.append('        injury_status=\'none\',)
    lines.append('        fatigue_level=\'normal\',)
    lines.append('        weeks_since_break=0,)
    lines.append('        cmj_band=\'moderate\',)
    lines.append('        sprint_10m_band=\'moderate\',)
    lines.append('        squat_strength_band=\'moderate\',)
    lines.append('        aerobic_band=\'low\',)  # Low aerobic')
    lines.append('    )')
    lines.append('    athlete_high = AthleteProfile(')
    lines.append('        sport=\'Running\',)
    lines.append('        training_age_years=4,)
    lines.append('        season_phase=\'pre_season\',)
    lines.append('        goal=\'Endurance\',)
    lines.append('        equipment_profile=\'Commercial Gym\',)
    lines.append('        athlete_level=\'Intermediate\',)
    lines.append('        technique_consistency=0.85,)
    lines.append('        injury_status=\'none\',)
    lines.append('        fatigue_level=\'normal\',)
    lines.append('        weeks_since_break=0,)
    lines.append('        cmj_band=\'moderate\',)
    lines.append('        sprint_10m_band=\'moderate\',)
    lines.append('        squat_strength_band=\'moderate\',)
    lines.append('        aerobic_band=\'high\',)  # High aerobic')
    lines.append('    )')
    lines.append('    from src.forge.prescription_rules import get_athlete_prescription_modifiers')
    lines.append('    # For a tempo run, which is a conditioning exercise, the role is CONDITIONING_LIFT')
    lines.append('    mod_low = get_athlete_prescription_modifiers(athlete_low, PrescriptionRole.CONDITIONING_LIFT)')
    lines.append('    mod_high = get_athlete_prescription_modifiers(athlete_high, PrescriptionRole.CONDITIONING_LIFT)')
    lines.append('    assert mod_low != mod_high, \"Expect different modifiers for low vs high aerobic band\"')
    lines.append('')
    # End-to-end generator tests
    lines.append('def test_generate_program_different_block_response_changes_output():')
    lines.append('    # Create two athletes that are identical except for prior block response (via different current bands)')
    lines.append('    # We\'ll simulate two different prior blocks by setting different current bands')
    lines.append('    # and then set the block_response attribute on the athlete.')
    lines.append('    base = {')
    lines.append('        \"sport\": \"Rowing\",')
    lines.append('        \"training_age_years\": 4,')
    lines.append('        \"season_phase\": \"off_season\",')
    lines.append('        \"goal\": \"Endurance\",')
    lines.append('        \"equipment_profile\": \"Commercial Gym\",')
    lines.append('        \"athlete_level\": \"Intermediate\",')
    lines.append('        \"technique_consistency\": 0.9,')
    lines.append('        \"injury_status\": \"none\",')
    lines.append('        \"fatigue_level\": \"normal\",)
    lines.append('        \"weeks_since_break\": 0,')
    lines.append('    }')
    lines.append('    # Athlete A: low bands')
    lines.append('    athlete_a = AthleteProfile(')
    lines.append('        **base,')
    lines.append('        cmj_band=\'low\',')
    lines.append('        sprint_10m_band=\'low\',')
    lines.append('        squat_strength_band=\'low\',)
    lines.append('        aerobic_band=\'low\',')
    lines.append('    )')
    lines.append('    # Athlete B: high bands')
    lines.append('    athlete_b = AthleteProfile(')
    lines.append('        **base,')
    lines.append('        cmj_band=\'high\',)
    lines.append('        sprint_10m_band=\'high\',)
    lines.append('        squat_strength_band=\'high\',)
    lines.append('        aerobic_band=\'high\',')
    lines.append('    )')
    lines.append('    # We need to simulate that these are the current profiles, and we have a prior profile that shows a change.')
    lines.append('    # For athlete A: no change (prior = current)')
    lines.append('    prior_a = athlete_a')
    lines.append('    response_a = build_block_response(prior_a, athlete_a, None)')
    lines.append('    athlete_a.block_response = response_a')
    lines.append('    # For athlete B: improved from low to high')
    lines.append('    prior_b = AthleteProfile(')
    lines.append('        **base,')
    lines.append('        cmj_band=\'low\',)
    lines.append('        sprint_10m_band=\'low\',)
    lines.append('        squat_strength_band=\'low\',)
    lines.append('        aerobic_band=\'low\',)
    lines.append('    )')
    lines.append('    response_b = build_block_response(prior_b, athlete_b, None)')
    lines.append('    athlete_b.block_response = response_b')
    lines.append('    # Generate programs')
    lines.append('    program_a = generate_program(athlete_a)')
    lines.append('    program_b = generate_program(athlete_b)')
    lines.append('    # We expect the programs to be different')
    lines.append('    # We\'ll compare the personalization notes, which should include the block review note.')
    lines.append('    # The block review note will be different because the block_response is different.')
    lines.append('    notes_a = program_a.personalization_notes')
    lines.append('    notes_b = program_b.personalization_notes')
    lines.append('    # We expect that the block review note is present in both but different')
    lines.append('    block_notes_a = [note for note in notes_a if note.startswith(\'Block Review:\')]')
    lines.append('    block_notes_b = [note for note in notes_b if note.startswith(\'Block Review:\')]')
    lines.append('    assert len(block_notes_a) > 0, \"Expected block review note in program A\"')
    lines.append('    assert len(block_notes_b) > 0, \"Expected block review note in program B\"')
    lines.append('    # The notes should be different because the block responses are different')
    lines.append('    assert block_notes_a[0] != block_notes_b[0], \"Expect different block review notes for different block responses\"')
    lines.append('')
    # Additional test: blueprint selection divergence
    lines.append('def test_blueprint_selection_divergence():')
    lines.append('    # We want to show that for the same athlete profile, different block responses lead to different blueprint selection.')
    lines.append('    # We will create an athlete profile that is on the edge (e.g., intermediate) and then adjust the block response to favor different blueprints.')
    lines.append('    # We will use the get_next_block_blueprint_bias function to see if the bias changes the score.')
    lines.append('    # We need two different block responses that should bias towards different blueprints.')
    lines.append('    # We will pick two blueprints that are known to be for different focuses (e.g., strength vs endurance).')
    lines.append('    # We will then compute the bias for each block response and see if the bias is different.')
    lines.append('    athlete = AthleteProfile(')
    lines.append('        sport=\'Rowing\',')
    lines.append('        training_age_years=4,)
    lines.append('        season_phase=\'off_season\',)
    lines.append('        goal=\'Endurance\',)  # This might favor endurance blueprints')
    lines.append('        equipment_profile=\'Commercial Gym\',)
    lines.append('        athlete_level=\'Intermediate\',)
    lines.append('        technique_consistency=0.9,)
    lines.append('        injury_status=\'none\',)
    lines.append('        fatigue_level=\'normal\',)
    lines.append('        weeks_since_break=0,)
    lines.append('        cmj_band=\'moderate\',)
    lines.append('        sprint_10m_band=\'moderate\',)
    lines.append('        squat_strength_band=\'moderate\',)
    lines.append('        aerobic_band=\'moderate\',)
    lines.append('    )')
    lines.append('    # Block response that indicates strength improvement')
    lines.append('    response_strength = BlockResponse(')
    lines.append('        prior_blueprint_id=\'\',)
    lines.append('        prior_goal=\'Endurance\',)
    lines.append('        start_test_bands={\'cmj_band\': \'moderate\', \'sprint_10m_band\': \'moderate\', \'squat_strength_band\': \'low\', \'aerobic_band\': \'moderate\'},')
    lines.append('        end_test_bands={\'cmj_band\': \'moderate\', \'sprint_10m_band\': \'moderate\', \'squat_strength_band\': \'moderate\', \'aerobic_band\': \'moderate\'},')
    lines.append('        improvements=[\'squat_strength\'],')
    lines.append('        stalls=[],')
    lines.append('        regressions=[],')
    lines.append('        recommended_shift=\'Maintain current focus.\',')
    lines.append('        notes=[\'squat_strength improved (low→moderate)\']')
    lines.append('    )')
    lines.append('    # Block response that indicates endurance improvement')
    lines.append('    response_endurance = BlockResponse(')
    lines.append('        prior_blueprint_id=\'\',)
    lines.append('        prior_goal=\'Endurance\',)
    lines.append('        start_test_bands={\'cmj_band\': \'moderate\', \'sprint_10m_band\': \'moderate\', \'squat_strength_band\': \'moderate\', \'aerobic_band\': \'low\'},')
    lines.append('        end_test_bands={\'cmj_band\': \'moderate\', \'sprint_10m_band\': \'moderate\', \'squat_strength_band\': \'moderate\', \'aerobic_band\': \'moderate\'},')
    lines.append('        improvements=[\'aerobic\'],')
    lines.append('        stalls=[],')
    lines.append('        regressions=[],')
    lines.append('        recommended_shift=\'Maintain current focus.\',')
    lines.append('        notes=[\'aerobic improved (low→moderate)\']')
    lines.append('    )')
    lines.append('    # We will get the blueprint bias for each')
    lines.append('    bias_strength = get_next_block_blueprint_bias(athlete, response_strength)')
    lines.append('    bias_endurance = get_next_block_blueprint_bias(athlete, response_endurance)')
    lines.append('    # We expect the bias to be different')
    lines.append('    assert bias_strength != bias_endurance, \"Expect different bias for strength vs endurance block responses\"')
    lines.append('')
    # Backward compatibility test: when no block response, behavior unchanged
    lines.append('def test_backward_compatibility_no_block_response():')
    lines.append('    athlete = AthleteProfile(')
    lines.append('        sport=\'Cycling\',')
    lines.append('        training_age_years=3,)
    lines.append('        season_phase=\'off_season\',)
    lines.append('        goal=\'Endurance\',)
    lines.append('        equipment_profile=\'Commercial Gym\',)
    lines.append('        athlete_level=\'Intermediate\',)
    lines.append('        technique_consistency=0.85,)
    lines.append('        injury_status=\'none\',)
    lines.append('        fatigue_level=\'normal\',)
    lines.append('        weeks_since_break=0,)
    lines.append('        cmj_band=\'moderate\',)
    lines.append('        sprint_10m_band=\'moderate\',)
    lines.append('        squat_strength_band=\'moderate\',)
    lines.append('        aerobic_band=\'moderate\',)
    lines.append('    )')
    lines.append('    # Ensure no block_response attribute')
    lines.append('    if hasattr(athlete, \'block_response\'):')
    lines.append('        del athlete.block_response')
    lines.append('    # Generate program without block response (should be same as before Wave 7)')
    lines.append('    program_no_response = generate_program(athlete)')
    lines.append('    assert program_no_response is not None')
    lines.append('    # We can also check that the personalization notes do not contain block review notes when block_response is None')
    lines.append('    # But note: our current main.py will not add block review notes if block_response is None or not present.')
    lines.append('    block_notes = [note for note in program_no_response.personalization_notes if note.startswith(\'Block Review:\')]')
    lines.append('    assert len(block_notes) == 0, \"Expected no block review notes when no block response\"')
    lines.append('')
    # Write the test file
    content = '\\n'.join(lines)
    with open('D:/forge/tests/test_wave7_hardening.py', 'w') as f:
        f.write(content)