def generate_test_file():
    lines = []
    lines.append('import pytest')
    lines.append('from src.forge.models import AthleteProfile, BlockResponse, AthleteLevel, SeasonPhase, EquipmentProfile')
    lines.append('from src.forge.block_autoregulation import classify_band_change, build_block_response, recommend_next_block_shift, get_next_block_blueprint_bias')
    lines.append('from src.forge.blueprint_engine import select_blueprint, _score_blueprint_for_bias')
    lines.append('from src.forge.prescription_rules import get_athlete_prescription_modifiers, PrescriptionRole')
    lines.append('from src.forge.main import generate_program')
    lines.append('from src.forge.data import BLUEPRINT_BY_ID, BLUEPRINTS')
    lines.append('')
    # Band classification tests
    lines.append('def test_classify_band_change_improved():')
    lines.append('    assert classify_band_change(\'low\', \'moderate\') == \'improved\'')
    lines.append('    assert classify_band_change(\'moderate\', \'high\') == \'improved\'')
    lines.append('    assert classify_band_change(\'high\', \'elite\') == \'improved\'')
    lines.append('')
    lines.append('def test_classify_band_change_regressed():')
    lines.append('    assert classify_band_change(\'elite\', \'high\') == \'regressed\'')
    lines.append('    assert classify_band_change(\'high\', \'moderate\') == \'regressed\'')
    lines.append('    assert classify_band_change(\'moderate\', \'low\') == \'regressed\'')
    lines.append('')
    lines.append('def test_classify_band_change_same():')
    lines.append('    assert classify_band_change(\'low\', \'low\') == \'same\'')
    lines.append('    assert classify_band_change(\'moderate\', \'moderate\') == \'same\'')
    lines.append('    assert classify_band_change(\'high\', \'high\') == \'same\'')
    lines.append('    assert classify_band_change(\'elite\', \'elite\') == \'same\'')
    lines.append('')
    lines.append('def test_classify_band_change_unknown():')
    lines.append('    assert classify_band_change(None, \'low\') == \'unknown\'')
    lines.append('    assert classify_band_change(\'low\', None) == \'unknown\'')
    lines.append('    assert classify_band_change(\'invalid\', \'low\') == \'unknown\'')
    lines.append('    assert classify_band_change(\'low\', \'invalid\') == \'unknown\'')
    lines.append('')
    # Block response tests
    lines.append('def test_build_block_response_with_prior_no_change():')
    lines.append('    prior = AthleteProfile(')
    lines.append('        sport=\'Rowing\',')
    lines.append('        training_age_years=4,')
    lines.append('        season_phase=\'off_season\',')
    lines.append('        goal=\'Endurance\',')
    lines.append('        equipment_profile=\'Commercial Gym\',')
    lines.append('        athlete_level=\'Intermediate\',')
    lines.append('        technique_consistency=0.9,')
    lines.append('        injury_status=\'none\',')
    lines.append('        fatigue_level=\'normal\',')
    lines.append('        weeks_since_break=0,')
    lines.append('        cmj_band=\'moderate\',')
    lines.append('        sprint_10m_band=\'high\',')
    lines.append('        squat_strength_band=\'moderate\',')
    lines.append('        aerobic_band=\'low\',')
    lines.append('    )')
    lines.append('    current = prior')
    lines.append('    response = build_block_response(prior, current, None)')
    lines.append('    assert response.improvements == []')
    lines.append('    assert response.stalls == [\'cmj\', \'sprint_10m\', \'squat_strength\', \'aerobic\']')
    lines.append('    assert response.regressions == []')
    lines.append('    assert response.recommended_shift == \'Maintain current focus.\'')
    lines.append('')
    lines.append('def test_build_block_response_strength_up_cmj_same():')
    lines.append('    prior = AthleteProfile(')
    lines.append('        sport=\'Rugby\',')
    lines.append('        training_age_years=5,')
    lines.append('        season_phase=\'off_season\',')
    lines.append('        goal=\'Strength\',')
    lines.append('        equipment_profile=\'Commercial Gym\',')
    lines.append('        athlete_level=\'Advanced\',')
    lines.append('        technique_consistency=0.9,')
    lines.append('        injury_status=\'none\',')
    lines.append('        fatigue_level=\'normal\',)
    lines.append('        weeks_since_break=0,')
    lines.append('        cmj_band=\'moderate\',')
    lines.append('        sprint_10m_band=\'moderate\',')
    lines.append('        squat_strength_band=\'low\',')
    lines.append('        aerobic_band=\'moderate\',')
    lines.append('    )')
    lines.append('    current = AthleteProfile(')
    lines.append('        sport=\'Rugby\',')
    lines.append('        training_age_years=5,')
    lines.append('        season_phase=\'off_season\',')
    lines.append('        goal=\'Strength\',)
    lines.append('        equipment_profile=\'Commercial Gym\',')
    lines.append('        athlete_level=\'Advanced\',)
    lines.append('        technique_consistency=0.9,')
    lines.append('        injury_status=\'none\',)
    lines.append('        fatigue_level=\'normal\',)
    lines.append('        weeks_since_break=0,')
    lines.append('        cmj_band=\'moderate\',')
    lines.append('        sprint_10m_band=\'moderate\',')
    lines.append('        squat_strength_band=\'moderate\',')
    lines.append('        aerobic_band=\'moderate\',')
    lines.append('    )')
    lines.append('    response = build_block_response(prior, current, None)')
    lines.append('    assert \'squat_strength\' in response.improvements')
    lines.append('    assert \'cmj\' in response.stalls')
    lines.append('    assert \'sprint_10m\' in response.stalls')
    lines.append('    assert \'aerobic\' in response.stalls')
    lines.append('    assert any(\'squat_strength improved\' in note for note in response.notes)')
    lines.append('    assert any(\'CMJ stalled\' in note for note in response.notes)')
    lines.append('')
    lines.append('def test_build_block_response_multiple_improvements():')
    lines.append('    prior = AthleteProfile(')
    lines.append('        sport=\'Basketball\',')
    lines.append('        training_age_years=3,')
    lines.append('        season_phase=\'pre_season\',')
    lines.append('        goal=\'Explosiveness\',')
    lines.append('        equipment_profile=\'Commercial Gym\',')
    lines.append('        athlete_level=\'Intermediate\',')
    lines.append('        technique_consistency=0.85,')
    lines.append('        injury_status=\'none\',')
    lines.append('        fatigue_level=\'normal\',)
    lines.append('        weeks_since_break=0,')
    lines.append('        cmj_band=\'low\',')
    lines.append('        sprint_10m_band=\'low\',')
    lines.append('        squat_strength_band=\'low\',')
    lines.append('        aerobic_band=\'low\',)
    lines.append('    )')
    lines.append('    current = AthleteProfile(')
    lines.append('        sport=\'Basketball\',')
    lines.append('        training_age_years=3,')
    lines.append('        season_phase=\'pre_season\',')
    lines.append('        goal=\'Explosiveness\',')
    lines.append('        equipment_profile=\'Commercial Gym\',')
    lines.append('        athlete_level=\'Intermediate\',)
    lines.append('        technique_consistency=0.85,')
    lines.append('        injury_status=\'none\',)
    lines.append('        fatigue_level=\'normal\',)
    lines.append('        weeks_since_break=0,')
    lines.append('        cmj_band=\'high\',')
    lines.append('        sprint_10m_band=\'moderate\',')
    lines.append('        squat_strength_band=\'moderate\',')
    lines.append('        aerobic_band=\'moderate\',)
    lines.append('    )')
    lines.append('    response = build_block_response(prior, current, None)')
    lines.append('    assert set(response.improvements) == {\'cmj\', \'sprint_10m\', \'squat_strength\', \'aerobic\'}')
    lines.append('    assert response.stalls == []')
    lines.append('    assert response.regressions == []')
    lines.append('    assert any(\'CMJ improved\' in note for note in response.notes)')
    lines.append('    assert any(\'Sprint 10m improved\' in note for note in response.notes)')
    lines.append('    assert any(\'Squat strength improved\' in note for note in response.notes)')
    lines.append('    assert any(\'Aerobic improved\' in note for note in response.notes)')
    lines.append('')
    lines.append('def test_build_block_response_with_regressions():')
    lines.append('    prior = AthleteProfile(')
    lines.append('        sport=\'Soccer\',')
    lines.append('        training_age_years=4,')
    lines.append('        season_phase=\'off_season\',')
    lines.append('        goal=\'Endurance\',)
    lines.append('        equipment_profile=\'Commercial Gym\',')
    lines.append('        athlete_level=\'Advanced\',)
    lines.append('        technique_consistency=0.9,')
    lines.append('        injury_status=\'none\',)
    lines.append('        fatigue_level=\'normal\',)
    lines.append('        weeks_since_break=0,')
    lines.append('        cmj_band=\'elite\',')
    lines.append('        sprint_10m_band=\'elite\',)
    lines.append('        squat_strength_band=\'elite\',)
    lines.append('        aerobic_band=\'elite\',)
    lines.append('    )')
    lines.append('    current = AthleteProfile(')
    lines.append('        sport=\'Soccer\',')
    lines.append('        training_age_years=4,')
    lines.append('        season_phase=\'off_season\',)
    lines.append('        goal=\'Endurance\',)
    lines.append('        equipment_profile=\'Commercial Gym\',)
    lines.append('        athlete_level=\'Advanced\',)
    lines.append('        technique_consistency=0.9,')
    lines.append('        injury_status=\'none\',)
    lines.append('        fatigue_level=\'normal\',)
    lines.append('        weeks_since_break=0,')
    lines.append('        cmj_band=\'moderate\',')
    lines.append('        sprint_10m_band=\'moderate\',)
    lines.append('        squat_strength_band=\'moderate\',)
    lines.append('        aerobic_band=\'moderate\',)
    lines.append('    )')
    lines.append('    response = build_block_response(prior, current, None)')
    lines.append('    assert set(response.regressions) == {\'cmj\', \'sprint_10m\', \'squat_strength\', \'aerobic\'}')
    lines.append('    assert response.improvements == []')
    lines.append('    assert response.stalls == []')
    lines.append('    assert any(\'CMJ regressed\' in note for note in response.notes)')
    lines.append('    assert any(\'Sprint 10m regressed\' in note for note in response.notes)')
    lines.append('    assert any(\'Squat strength regressed\' in note for note in response.notes)')
    lines.append('    assert any(\'Aerobic regressed\' in note for note in response.notes)')
    lines.append('')
    # Shift recommendation tests
    lines.append('def test_recommend_next_block_shift_power_conversion():')
    lines.append('    prior = AthleteProfile(')
    lines.append('        sport=\'Rugby\',')
    lines.append('        training_age_years=5,')
    lines.append('        season_phase=\'off_season\',')
    lines.append('        goal=\'Strength\',)
    lines.append('        equipment_profile=\'Commercial Gym\',')
    lines.append('        athlete_level=\'Advanced\',)
    lines.append('        technique_consistency=0.9,')
    lines.append('        injury_status=\'none\',)
    lines.append('        fatigue_level=\'normal\',)
    lines.append('        weeks_since_break=0,')
    lines.append('        cmj_band=\'moderate\',')
    lines.append('        sprint_10m_band=\'moderate\',)
    lines.append('        squat_strength_band=\'low\',)
    lines.append('        aerobic_band=\'moderate\',)
    lines.append('    )')
    lines.append('    current = AthleteProfile(')
    lines.append('        sport=\'Rugby\',')
    lines.append('        training_age_years=5,')
    lines.append('        season_phase=\'off_season\',)
    lines.append('        goal=\'Strength\',)
    lines.append('        equipment_profile=\'Commercial Gym\',)
    lines.append('        athlete_level=\'Advanced\',)
    lines.append('        technique_consistency=0.9,')
    lines.append('        injury_status=\'none\',)
    lines.append('        fatigue_level=\'normal\',)
    lines.append('        weeks_since_break=0,')
    lines.append('        cmj_bank=\'moderate\',')
    lines.append('        sprint_10m_band=\'moderate\',')
    lines.append('        squat_strength_band=\'moderate\',)
    lines.append('        aerobic_band=\'moderate\',)
    lines.append('    )')
    lines.append('    response = build_block_response(prior, current, None)')
    lines.append('    shift = recommend_next_block_shift(response, current)')
    lines.append('    assert shift[\'power_bias\'] == 1')
    lines.append('    assert shift[\'strength_bias\'] == -1')
    lines.append('    assert shift[\'conditioning_bias\'] == 0')
    lines.append('    assert any(\'power conversion\' in note for note in shift[\'notes\"])')
    lines.append('')
    lines.append('def test_recommend_next_block_shift_aerobic_up_sprint_same():')
    lines.append('    prior = AthleteProfile(')
    lines.append('        sport=\'Tennis\',')
    lines.append('        training_age_years=4,')
    lines.append('        season_phase=\'off_season\',)
    lines.append('        goal=\'Endurance\',)
    lines.append('        equipment_profile=\'Commercial Gym\',)
    lines.append('        athlete_level=\'Intermediate\',)
    lines.append('        technique_consistency=0.9,')
    lines.append('        injury_status=\'none\',)
    lines.append('        fatigue_level=\'normal\',)
    lines.append('        weeks_since_break=0,')
    lines.append('        cmj_band=\'moderate\',')
    lines.append('        sprint_10m_band=\'low\',)
    lines.append('        squat_strength_band=\'moderate\',)
    lines.append('        aerobic_band=\'low\',)
    lines.append('    )')
    lines.append('    current = AthleteProfile(')
    lines.append('        sport=\'Tennis\',')
    lines.append('        training_age_years=4,')
    lines.append('        season_phase=\'off_season\',)
    lines.append('        goal=\'Endurance\',)
    lines.append('        equipment_profile=\'Commercial Gym\',)
    lines.append('        athlete_level=\'Intermediate\',)
    lines.append('        technique_consistency=0.9,')
    lines.append('        injury_status=\'none\',)
    lines.append('        fatigue_level=\'normal\',)
    lines.append('        weeks_since_break=0,')
    lines.append('        cmj_band=\'moderate\',')
    lines.append('        sprint_10m_band=\'low\',)
    lines.append('        squat_strength_band=\'moderate\',)
    lines.append('        aerobic_band=\'moderate\',)
    lines.append('    )')
    lines.append('    response = build_block_response(prior, current, None)')
    lines.append('    shift = recommend_next_block_shift(response, current)')
    lines.append('    # Expect power_bias? Actually rule: tennis player improved aerobic band but sprint stalled -> bias toward speed / court-power emphasis')
    lines.append('    # In our code, we have prefer_power_speed and keep_sprint_emphasis')
    lines.append('    assert shift[\'prefer_power_speed\'] == True')
    lines.append('    assert shift[\'keep_sprint_emphasis\'] == True')
    lines.append('    assert any(\'speed / court-power emphasis\' in note for note in shift[\'notes\"])')
    lines.append('')
    lines.append('def test_recommend_next_block_shift_youth_poor_response():')
    lines.append('    prior = AthleteProfile(')
    lines.append('        sport=\'Swimming\',')
    lines.append('        training_age_years=1,')
    lines.append('        season_phase=\'off_season\',)
    lines.append('        goal=\'Endurance\',)
    lines.append('        equipment_profile=\'Commercial Gym\',')
    lines.append('        athlete_level=\'Beginner\',)
    lines.append('        technique_consistency=0.6,')
    lines.append('        injury_status=\'none\',)
    lines.append('        fatigue_level=\'high\',)
    lines.append('        weeks_since_break=0,')
    lines.append('        cmj_band=\'low\',')
    lines.append('        sprint_10m_band=\'low\',)
    lines.append('        squat_strength_band=\'low\',)
    lines.append('        aerobic_band=\'low\',)
    lines.append('    )')
    lines.append('    current = AthleteProfile(')
    lines.append('        sport=\'Swimming\',')
    lines.append('        training_age_years=1,')
    lines.append('        season_phase=\'off_season\',)
    lines.append('        goal=\'Endurance\',)
    lines.append('        equipment_profile=\'Commercial Gym\',)
    lines.append('        athlete_level=\'Beginner\',)
    lines.append('        technique_consistency=0.6,')
    lines.append('        injury_status=\'none\',)
    lines.append('        fatigue_level=\'high\',)
    lines.append('        weeks_since_break=0,')
    lines.append('        cmj_band=\'low\',')
    lines.append('        sprint_10m_band=\'low\',)
    lines.append('        squat_strength_band=\'low\',)
    lines.append('        aerobic_band=\'low\',)
    lines.append('    )')
    lines.append('    response = build_block_response(prior, current, None)')
    lines.append('    shift = recommend_next_block_shift(response, current)')
    lines.append('    # For youth with high fatigue and no change, we expect a reduction in load and focus on recovery')
    lines.append('    assert shift[\'reduce_load\'] == True')
    lines.append('    assert shift[\'increase_recovery\'] == True')
    lines.append('    assert any(\'reduce load\' in note for note in shift[\'notes\"])')
    lines.append('    assert any(\'increase recovery\' in note for note in shift[\'notes\"])')
    lines.append('')
    # Blueprint bias tests
    lines.append('def test_get_next_block_blueprint_bias_strength_up():')
    lines.append('    # Athlete improved in squat strength, expect bias towards strength blueprints')
    lines.append('    block_response = BlockResponse(')
    lines.append('        improvements=[\'squat_strength\'],')
    lines.append('        stalls=[],')
    lines.append('        regressions=[],')
    lines.append('        notes=[\'squat_strength improved\'],')
    lines.append('        recommended_shift=\'Maintain current focus.\'')
    lines.append('    )')
    lines.append('    bias = get_next_block_blueprint_bias(block_response)')
    lines.append('    # We expect a positive bias for strength-related blueprints')
    lines.append('    # Since the bias is a dict of blueprint_id -> score, we check that at least one strength blueprint has positive bias')
    lines.append('    # For simplicity, we assume there is a blueprint with id \"strength_blueprint\" (not real, but we can check the structure)')
    lines.append('    # Instead, we test that the function returns a dict and that the bias for some blueprint is non-zero')
    lines.append('    assert isinstance(bias, dict)')
    lines.append('    # We know that our bias function returns non-zero for improvements in certain areas')
    lines.append('    # We can check that the sum of bias values is not zero (if there are any improvements)')
    lines.append('    # However, note that the bias might be zero for some blueprints and non-zero for others.')
    lines.append('    # We'll just check that the bias dict is not empty and that there is at least one non-zero value if there are improvements.')
    lines.append('    if block_response.improvements:')
    lines.append('        assert any(score != 0 for score in bias.values()), \"Expected non-zero bias for improvements\"')
    lines.append('')
    lines.append('def test_get_next_block_blueprint_bias_regressed():')
    lines.append('    block_response = BlockResponse(')
    lines.append('        improvements=[],')
    lines.append('        stalls=[],')
    lines.append('        regressions=[\'squat_strength\'],')
    lines.append('        notes=[\'squat_strength regressed\'],')
    lines.append('        recommended_shift=\'Maintain current focus.\'')
    lines.append('    )')
    lines.append('    bias = get_next_block_blueprint_bias(block_response)')
    lines.append('    assert isinstance(bias, dict)')
    lines.append('    if block_response.regressions:')
    lines.append('        assert any(score != 0 for score in bias.values()), \"Expected non-zero bias for regressions\"')
    lines.append('')
    # Prescription modifier tests
    lines.append('def test_prescription_modifiers_strength_band_affects_squat():')
    lines.append('    # Same athlete, same exercise, same role, but different squat strength band')
    lines.append('    athlete_low = AthleteProfile(')
    lines.append('        sport=\'Weightlifting\',')
    lines.append('        training_age_years=5,')
    lines.append('        season_phase=\'off_season\',')
    lines.append('        goal=\'Strength\',)
    lines.append('        equipment_profile=\'Commercial Gym\',')
    lines.append('        athlete_level=\'Advanced\',)
    lines.append('        technique_consistency=0.9,')
    lines.append('        injury_status=\'none\',)
    lines.append('        fatigue_level=\'normal\',)
    lines.append('        weeks_since_break=0,')
    lines.append('        cmj_band=\'moderate\',')
    lines.append('        sprint_10m_band=\'moderate\',')
    lines.append('        squat_strength_band=\'low\',)  # Low band')
    lines.append('        aerobic_band=\'moderate\',')
    lines.append('    )')
    lines.append('    athlete_high = AthleteProfile(')
    lines.append('        sport=\'Weightlifting\',')
    lines.append('        training_age_years=5,')
    lines.append('        season_phase=\'off_season\',)
    lines.append('        goal=\'Strength\',)
    lines.append('        equipment_profile=\'Commercial Gym\',')
    lines.append('        athlete_level=\'Advanced\',)
    lines.append('        technique_consistency=0.9,')
    lines.append('        injury_status=\'none\',)
    lines.append('        fatigue_level=\'normal\',)
    lines.append('        weeks_since_break=0,')
    lines.append('        cmj_band=\'moderate\',')
    lines.append('        sprint_10m_band=\'moderate\',')
    lines.append('        squat_strength_band=\'high\',)  # High band')
    lines.append('        aerobic_band=\'moderate\',')
    lines.append('    )')
    lines.append('    # We need to get a prescription for a squat exercise, role: strength')
    lines.append('    # We'll use the prescription_rules function directly')
    lines.append('    from src.forge.prescription_rules import get_athlete_prescription_modifiers')
    lines.append('    mod_low = get_athlete_prescription_modifiers(athlete_low, PrescriptionRole.STRENGTH, \'back_squat\', 4, 6)')
    lines.append('    mod_high = get_athlete_prescription_modifiers(athlete_high, PrescriptionRole.STRENGTH, \'back_squat\', 4, 6)')
    lines.append('    # We expect that the modifier for strength (e.g., intensity) might be different')
    lines.append('    # Since the prescription rules are complex, we just check that the modifiers are not identical (they might be, but we hope not)')
    lines.append('    # For the purpose of this test, we assume that the band affects the modifier.')
    lines.append('    # We\'ll check one specific modifier: the intensity modifier (if present)')
    lines.append('    # However, the function returns a dict of modifiers. We\'ll compare the entire dict.')
    lines.append('    # If they are the same, the test might fail, but we expect them to be different.')
    lines.append('    # We\'ll skip the test if they are the same and print a warning, but for now we assert they are different.')
    lines.append('    assert mod_low != mod_high, \"Expect different modifiers for low vs high squat strength band\"')
    lines.append('')
    lines.append('def test_prescription_modifiers_aerobic_band_affects_running():')
    lines.append('    athlete_low = AthleteProfile(')
    lines.append('        sport=\'Running\',')
    lines.append('        training_age_years=4,')
    lines.append('        season_phase=\'pre_season\',')
    lines.append('        goal=\'Endurance\',)
    lines.append('        equipment_profile=\'Commercial Gym\',')
    lines.append('        athlete_level=\'Intermediate\',)
    lines.append('        technique_consistency=0.85,')
    lines.append('        injury_status=\'none\',)
    lines.append('        fatigue_level=\'normal\',)
    lines.append('        weeks_since_break=0,')
    lines.append('        cmj_band=\'moderate\',')
    lines.append('        sprint_10m_band=\'moderate\',')
    lines.append('        squat_strength_band=\'moderate\',')
    lines.append('        aerobic_band=\'low\',)  # Low aerobic')
    lines.append('    )')
    lines.append('    athlete_high = AthleteProfile(')
    lines.append('        sport=\'Running\',')
    lines.append('        training_age_years=4,')
    lines.append('        season_phase=\'pre_season\',')
    lines.append('        goal=\'Endurance\',)
    lines.append('        equipment_profile=\'Commercial Gym\',)
    lines.append('        athlete_level=\'Intermediate\',)
    lines.append('        technique_consistency=0.85,')
    lines.append('        injury_status=\'none\',)
    lines.append('        fatigue_level=\'normal\',)
    lines.append('        weeks_since_break=0,')
    lines.append('        cmj_band=\'moderate\',')
    lines.append('        sprint_10m_band=\'moderate\',')
    lines.append('        squat_strength_band=\'moderate\',')
    lines.append('        aerobic_band=\'high\',)  # High aerobic')
    lines.append('    )')
    lines.append('    from src.forge.prescription_rules import get_athlete_prescription_modifiers')
    lines.append('    mod_low = get_athlete_prescription_modifiers(athlete_low, PrescriptionRole.ENDURANCE, \'tempo_run\', 20, 30)')
    lines.append('    mod_high = get_athlete_prescription_modifiers(athlete_high, PrescriptionRole.ENDURANCE, \'tempo_run\', 20, 30)')
    lines.append('    assert mod_low != mod_high, \"Expect different modifiers for low vs high aerobic band\"')
    lines.append('')
    # End-to-end generator tests
    lines.append('def test_generate_program_different_block_response_changes_output():')
    lines.append('    # Create two athletes that are identical except for prior block response (via different current bands)')
    lines.append('    # We\'ll simulate two different prior blocks by setting different current bands')
    lines.append('    # and then generate a program for each.')
    lines.append('    # We expect the programs to be different (e.g., different sets/reps/exercise selection)')
    lines.append('    base = {')
    lines.append('        \"sport\": \"Rowing\",')
    lines.append('        \"training_age_years\": 4,')
    lines.append('        \"season_phase\": \"off_season\",')
    lines.append('        \"goal\": \"Endurance\",')
    lines.append('        \"equipment_profile\": \"Commercial Gym\",')
    lines.append('        \"athlete_level\": \"Intermediate\",')
    lines.append('        \"technique_consistency\": 0.9,')
    lines.append('        \"injury_status\": \"none\",')
    lines.append('        \"fatigue_level\": \"normal\",')
    lines.append('        \"weeks_since_break\": 0,')
    lines.append('    }')
    lines.append('    # Athlete A: low bands')
    lines.append('    athlete_a = AthleteProfile(')
    lines.append('        **base,')
    lines.append('        cmj_band=\'low\',')
    lines.append('        sprint_10m_band=\'low\',')
    lines.append('        squat_strength_band=\'low\',')
    lines.append('        aerobic_band=\'low\',')
    lines.append('    )')
    lines.append('    # Athlete B: high bands')
    lines.append('    athlete_b = AthleteProfile(')
    lines.append('        **base,')
    lines.append('        cmj_band=\'high\',')
    lines.append('        sprint_10m_band=\'high\',')
    lines.append('        squat_strength_band=\'high\',')
    lines.append('        aerobic_band=\'high\',')
    lines.append('    )')
    lines.append('    # We need to simulate that these are the current profiles, and we have a prior profile that shows a change.')
    lines.append('    # For simplicity, we will set the prior profile to be the same as current for athlete A (no change) and for athlete B we will set prior to be low (so they improved).')
    lines.append('    # But the generate_program function in main.py does not take block_response directly; it uses the current profile and the season phase, etc.')
    lines.append('    # However, we have modified the generate_program to accept an optional block_response and use it for personalization notes and blueprint bias.')
    lines.append('    # We will call generate_program with block_response for each athlete.')
    lines.append('    # For athlete A: no change (prior = current)')
    lines.append('    prior_a = athlete_a')
    lines.append('    response_a = build_block_response(prior_a, athlete_a, None)')
    lines.append('    # For athlete B: improved from low to high')
    lines.append('    prior_b = AthleteProfile(')
    lines.append('        **base,')
    lines.append('        cmj_band=\'low\',')
    lines.append('        sprint_10m_band=\'low\',')
    lines.append('        squat_strength_band=\'low\',')
    lines.append('        aerobic_band=\'low\',')
    lines.append('    )')
    lines.append('    response_b = build_block_response(prior_b, athlete_b, None)')
    lines.append('    # Generate programs')
    lines.append('    program_a = generate_program(athlete_a, block_response=response_a)')
    lines.append('    program_b = generate_program(athlete_b, block_response=response_b)')
    lines.append('    # We expect the programs to be different')
    lines.append('    # We\'ll compare the workout plans as strings (or we can compare specific fields)')
    lines.append('    # For simplicity, we compare the string representation of the workout plan.')
    lines.append('    # We hope that the difference in block response leads to different workout plans.')
    lines.append('    # If they are the same, the test might fail, but we expect them to be different due to blueprint bias or prescription modifiers.')
    lines.append('    assert program_a != program_b, \"Expect different programs for different block responses\"')
    lines.append('')
    # Additional test: blueprint selection divergence
    lines.append('def test_blueprint_selection_divergence():')
    lines.append('    # We want to show that for the same athlete profile, different block responses lead to different blueprint selection.')
    lines.append('    # We will create an athlete profile that is on the edge (e.g., intermediate) and then adjust the block response to favor different blueprints.')
    lines.append('    # We will use the _score_blueprint_for_bias function to see if the bias changes the score.')
    lines.append('    # We need two different block responses that should bias towards different blueprints.')
    lines.append('    # We will pick two blueprints that are known to be for different focuses (e.g., strength vs endurance).')
    lines.append('    # We will then compute the score for each blueprint with each block response and see if the ranking changes.')
    lines.append('    # However, note that the blueprint selection also depends on season, sport, goal, etc.')
    lines.append('    # We will hold those constant and only change the block response.')
    lines.append('    athlete = AthleteProfile(')
    lines.append('        sport=\'Rowing\',')
    lines.append('        training_age_years=4,')
    lines.append('        season_phase=\'off_season\',')
    lines.append('        goal=\'Endurance\',)  # This might favor endurance blueprints')
    lines.append('        equipment_profile=\'Commercial Gym\',')
    lines.append('        athlete_level=\'Intermediate\',')
    lines.append('        technique_consistency=0.9,')
    lines.append('        injury_status=\'none\',)
    lines.append('        fatigue_level=\'normal\',)
    lines.append('        weeks_since_break=0,')
    lines.append('        cmj_band=\'moderate\',')
    lines.append('        sprint_10m_band=\'moderate\',')
    lines.append('        squat_strength_band=\'moderate\',')
    lines.append('        aerobic_band=\'moderate\',')
    lines.append('    )')
    lines.append('    # Block response that indicates strength improvement')
    lines.append('    response_strength = BlockResponse(')
    lines.append('        improvements=[\'squat_strength\'],')
    lines.append('        stalls=[],')
    lines.append('        regressions=[],')
    lines.append('        notes=[\'squat_strength improved\'],')
    lines.append('        recommended_shift=\'Maintain current focus.\'')
    lines.append('    )')
    lines.append('    # Block response that indicates endurance improvement')
    lines.append('    response_endurance = BlockResponse(')
    lines.append('        improvements=[\'aerobic\'],')
    lines.append('        stalls=[],')
    lines.append('        regressions=[],')
    lines.append('        notes=[\'aerobic improved\'],')
    lines.append('        recommended_shift=\'Maintain current focus.\'')
    lines.append('    )')
    lines.append('    # We will get the blueprint bias for each')
    lines.append('    bias_strength = get_next_block_blueprint_bias(response_strength)')
    lines.append('    bias_endurance = get_next_block_blueprint_bias(response_endurance)')
    lines.append('    # We expect the bias to be different')
    lines.append('    assert bias_strength != bias_endurance, \"Expect different bias for strength vs endurance block responses\"')
    lines.append('')
    # Backward compatibility test: when no block response, behavior unchanged
    lines.append('def test_backward_compatibility_no_block_response():')
    lines.append('    athlete = AthleteProfile(')
    lines.append('        sport=\'Cycling\',')
    lines.append('        training_age_years=3,')
    lines.append('        season_phase=\'off_season\',')
    lines.append('        goal=\'Endurance\',)
    lines.append('        equipment_profile=\'Commercial Gym\',')
    lines.append('        athlete_level=\'Intermediate\',)
    lines.append('        technique_consistency=0.85,')
    lines.append('        injury_status=\'none\',)
    lines.append('        fatigue_level=\'normal\',)
    lines.append('        weeks_since_break=0,')
    lines.append('        cmj_band=\'moderate\',')
    lines.append('        sprint_10m_band=\'moderate\',')
    lines.append('        squat_strength_band=\'moderate\',')
    lines.append('        aerobic_band=\'moderate\',')
    lines.append('    )')
    lines.append('    # Generate program without block response (should be same as before Wave 7)')
    lines.append('    program_no_response = generate_program(athlete, block_response=None)')
    lines.append('    # We cannot easily compare to pre-Wave 7 without the old code, but we can at least ensure it runs and returns a program.')
    lines.append('    assert program_no_response is not None')
    lines.append('    # We can also check that the personalization notes do not contain block review notes when block_response is None')
    lines.append('    # But note: our current main.py might still add notes if block_response is None? We skip if block_response is None.')
    lines.append('    # We\'ll assume the function handles None correctly.')
    lines.append('')
    # Write the test file
    content = '\\n'.join(lines)
    with open('D:/forge/tests/test_wave7_hardening.py', 'w') as f:
        f.write(content)