-- Forge Exercise Intelligence Database - Migration 000026 (Down)
-- Description: Remove CSCS Expert Exercise Library Expansion
-- 
-- Safely removes exercises added in migration 000026
-- Uses ON CONFLICT DO NOTHING for idempotency

BEGIN;

-- Remove exercise tags first (foreign key constraint)
DELETE FROM exercise_tags 
WHERE exercise_id IN (
    SELECT id FROM exercises WHERE name IN (
        -- Complexes
        'Lunge to Step-Up with Knee Drive Complex',
        'Romanian Deadlift to Box Jump Complex',
        'Split Squat to Lateral Bound Complex',
        'Front Squat to Push Press Complex',
        'Nordic Curl Eccentric to Hip Extension Complex',
        'Cossack Squat to Skater Hop Complex',
        'Pull-Up to Muscle-Up Transition Complex',
        'Inverted Row to Push-Up Complex',
        'Farmers Carry to Overhead Press Complex',
        'Renegade Row to Push-Up Complex',
        'Face Pull to External Rotation Complex',
        'Z Press to Landmine Press Complex',
        'Trap Bar Deadlift to Vertical Jump Contrast',
        'Bench Press to Medicine Ball Chest Pass Contrast',
        'Power Clean to Broad Jump Complex',
        'Back Squat to Hurdle Hop Complex',
        'Weighted Pull-Up to Clap Push-Up Contrast',
        'Snatch Pull to Overhead Med Ball Slam Complex',
        -- Olympic variations
        'Hang Power Clean from Mid-Thigh',
        'Hang Power Snatch from Hip Pocket',
        'Clean Pull from Blocks',
        'Snatch Pull from Blocks',
        'Push Jerk from Rack',
        'Split Jerk',
        'Muscle Snatch',
        'Behind Neck Push Press',
        'Tall Kneeling Clean',
        'Tall Kneeling Snatch',
        'Mid-Thigh Clean Isometric Hold',
        'Overhead Squat Balance',
        -- Unilateral lower body
        'Curtsy Lunge',
        'Step-Down from Box',
        'Single-Leg Romanian Deadlift',
        'Pistol Squat Progression',
        'Lateral Lunge (Cossack)',
        'Single-Leg Box Squat',
        'Reverse Lunge with Torso Rotation',
        'Single-Leg Calf Raise',
        'Adductor Slide',
        'Single-Leg Glute Bridge March',
        -- Loaded carries
        'Farmers Walk',
        'Suitcase Carry',
        'Rack Carry',
        'Overhead Carry',
        'Waiters Walk',
        'Zercher Carry',
        'Front Rack Carry',
        'Single-Arm Bottoms-Up Kettlebell Carry',
        -- Core anti-movement
        'Pallof Press',
        'Pallof Press with Rotation',
        'Ab Wheel Rollout',
        'Stir the Pot',
        'Dead Bug',
        'Bird Dog',
        'Side Plank with Hip Dip',
        'Cable Chop',
        'Cable Lift',
        'McGill Big 3 Circuit',
        -- Plyometrics
        'Pogo Hop',
        'Ankle Hops',
        'Line Hops',
        'Tuck Jump',
        'Pike Jump',
        '180° Jump',
        'Single-Leg Hops in Place',
        'Single-Leg Hops for Distance',
        'Bounding for Distance',
        'Depth Drop to Stick',
        'Depth Jump to Max Vertical',
        'Shock Lateral Bounds',
        -- Eccentric overload
        'Flywheel Squat',
        'Flywheel RDL',
        'Flywheel Calf Raise',
        'Eccentric-Only Pull-Up',
        'Eccentric-Only Nordic Curl',
        'Yo-Yo Leg Curl',
        -- BFR exercises
        'BFR Bodyweight Squat',
        'BFR Walking',
        'BFR Leg Extension Machine',
        'BFR Hamstring Curl',
        'BFR Calf Raise',
        'BFR Arm Curl',
        -- Mobility & prehab
        '90/90 Hip Switches',
        'Worlds Greatest Stretch',
        'Thoracic Spine Windmills',
        'Ankle Dorsiflexion Mobilization',
        'Hip Flexor Stretch with Posterior Tilt',
        'Band-Dislocated Shoulder Pass-Through',
        'Scapular Wall Slides',
        'Adductor Rock Backs',
        'Couch Stretch',
        'Lat Hang with Active Depression',
        -- Strongman
        'Atlas Stone Load',
        'Sandbag Shouldering',
        'Yoke Walk',
        'Sled Push',
        'Sled Drag',
        'Keg Toss',
        'Log Press',
        'Axle Bar Deadlift',
        -- Conditioning
        'Battle Ropes Waves',
        'Battle Ropes Slams',
        'Assault Bike Sprint',
        'Rower Intervals',
        'Burpee',
        'Burpee Box Jump Over',
        'Mountain Climbers',
        'Bear Crawl'
    )
);

-- Remove exercise movement pattern mappings
DELETE FROM exercise_movement_patterns 
WHERE exercise_id IN (
    SELECT id FROM exercises WHERE name IN (
        'Lunge to Step-Up with Knee Drive Complex',
        'Romanian Deadlift to Box Jump Complex',
        'Split Squat to Lateral Bound Complex',
        'Front Squat to Push Press Complex',
        'Nordic Curl Eccentric to Hip Extension Complex',
        'Cossack Squat to Skater Hop Complex',
        'Pull-Up to Muscle-Up Transition Complex',
        'Inverted Row to Push-Up Complex',
        'Farmers Carry to Overhead Press Complex',
        'Renegade Row to Push-Up Complex',
        'Face Pull to External Rotation Complex',
        'Z Press to Landmine Press Complex',
        'Trap Bar Deadlift to Vertical Jump Contrast',
        'Bench Press to Medicine Ball Chest Pass Contrast',
        'Power Clean to Broad Jump Complex',
        'Back Squat to Hurdle Hop Complex',
        'Weighted Pull-Up to Clap Push-Up Contrast',
        'Snatch Pull to Overhead Med Ball Slam Complex',
        'Hang Power Clean from Mid-Thigh',
        'Hang Power Snatch from Hip Pocket',
        'Clean Pull from Blocks',
        'Snatch Pull from Blocks',
        'Push Jerk from Rack',
        'Split Jerk',
        'Muscle Snatch',
        'Behind Neck Push Press',
        'Tall Kneeling Clean',
        'Tall Kneeling Snatch',
        'Mid-Thigh Clean Isometric Hold',
        'Overhead Squat Balance',
        'Curtsy Lunge',
        'Step-Down from Box',
        'Single-Leg Romanian Deadlift',
        'Pistol Squat Progression',
        'Lateral Lunge (Cossack)',
        'Single-Leg Box Squat',
        'Reverse Lunge with Torso Rotation',
        'Single-Leg Calf Raise',
        'Adductor Slide',
        'Single-Leg Glute Bridge March',
        'Farmers Walk',
        'Suitcase Carry',
        'Rack Carry',
        'Overhead Carry',
        'Waiters Walk',
        'Zercher Carry',
        'Front Rack Carry',
        'Single-Arm Bottoms-Up Kettlebell Carry',
        'Pallof Press',
        'Pallof Press with Rotation',
        'Ab Wheel Rollout',
        'Stir the Pot',
        'Dead Bug',
        'Bird Dog',
        'Side Plank with Hip Dip',
        'Cable Chop',
        'Cable Lift',
        'McGill Big 3 Circuit',
        'Pogo Hop',
        'Ankle Hops',
        'Line Hops',
        'Tuck Jump',
        'Pike Jump',
        '180° Jump',
        'Single-Leg Hops in Place',
        'Single-Leg Hops for Distance',
        'Bounding for Distance',
        'Depth Drop to Stick',
        'Depth Jump to Max Vertical',
        'Shock Lateral Bounds',
        'Flywheel Squat',
        'Flywheel RDL',
        'Flywheel Calf Raise',
        'Eccentric-Only Pull-Up',
        'Eccentric-Only Nordic Curl',
        'Yo-Yo Leg Curl',
        'BFR Bodyweight Squat',
        'BFR Walking',
        'BFR Leg Extension Machine',
        'BFR Hamstring Curl',
        'BFR Calf Raise',
        'BFR Arm Curl',
        '90/90 Hip Switches',
        'Worlds Greatest Stretch',
        'Thoracic Spine Windmills',
        'Ankle Dorsiflexion Mobilization',
        'Hip Flexor Stretch with Posterior Tilt',
        'Band-Dislocated Shoulder Pass-Through',
        'Scapular Wall Slides',
        'Adductor Rock Backs',
        'Couch Stretch',
        'Lat Hang with Active Depression',
        'Atlas Stone Load',
        'Sandbag Shouldering',
        'Yoke Walk',
        'Sled Push',
        'Sled Drag',
        'Keg Toss',
        'Log Press',
        'Axle Bar Deadlift',
        'Battle Ropes Waves',
        'Battle Ropes Slams',
        'Assault Bike Sprint',
        'Rower Intervals',
        'Burpee',
        'Burpee Box Jump Over',
        'Mountain Climbers',
        'Bear Crawl'
    )
);

-- Remove exercise equipment mappings
DELETE FROM exercise_equipment 
WHERE exercise_id IN (
    SELECT id FROM exercises WHERE name IN (
        'Lunge to Step-Up with Knee Drive Complex',
        'Romanian Deadlift to Box Jump Complex',
        'Split Squat to Lateral Bound Complex',
        'Front Squat to Push Press Complex',
        'Nordic Curl Eccentric to Hip Extension Complex',
        'Cossack Squat to Skater Hop Complex',
        'Pull-Up to Muscle-Up Transition Complex',
        'Inverted Row to Push-Up Complex',
        'Farmers Carry to Overhead Press Complex',
        'Renegade Row to Push-Up Complex',
        'Face Pull to External Rotation Complex',
        'Z Press to Landmine Press Complex',
        'Trap Bar Deadlift to Vertical Jump Contrast',
        'Bench Press to Medicine Ball Chest Pass Contrast',
        'Power Clean to Broad Jump Complex',
        'Back Squat to Hurdle Hop Complex',
        'Weighted Pull-Up to Clap Push-Up Contrast',
        'Snatch Pull to Overhead Med Ball Slam Complex',
        'Hang Power Clean from Mid-Thigh',
        'Hang Power Snatch from Hip Pocket',
        'Clean Pull from Blocks',
        'Snatch Pull from Blocks',
        'Push Jerk from Rack',
        'Split Jerk',
        'Muscle Snatch',
        'Behind Neck Push Press',
        'Tall Kneeling Clean',
        'Tall Kneeling Snatch',
        'Mid-Thigh Clean Isometric Hold',
        'Overhead Squat Balance',
        'Curtsy Lunge',
        'Step-Down from Box',
        'Single-Leg Romanian Deadlift',
        'Pistol Squat Progression',
        'Lateral Lunge (Cossack)',
        'Single-Leg Box Squat',
        'Reverse Lunge with Torso Rotation',
        'Single-Leg Calf Raise',
        'Adductor Slide',
        'Single-Leg Glute Bridge March',
        'Farmers Walk',
        'Suitcase Carry',
        'Rack Carry',
        'Overhead Carry',
        'Waiters Walk',
        'Zercher Carry',
        'Front Rack Carry',
        'Single-Arm Bottoms-Up Kettlebell Carry',
        'Pallof Press',
        'Pallof Press with Rotation',
        'Ab Wheel Rollout',
        'Stir the Pot',
        'Dead Bug',
        'Bird Dog',
        'Side Plank with Hip Dip',
        'Cable Chop',
        'Cable Lift',
        'McGill Big 3 Circuit',
        'Pogo Hop',
        'Ankle Hops',
        'Line Hops',
        'Tuck Jump',
        'Pike Jump',
        '180° Jump',
        'Single-Leg Hops in Place',
        'Single-Leg Hops for Distance',
        'Bounding for Distance',
        'Depth Drop to Stick',
        'Depth Jump to Max Vertical',
        'Shock Lateral Bounds',
        'Flywheel Squat',
        'Flywheel RDL',
        'Flywheel Calf Raise',
        'Eccentric-Only Pull-Up',
        'Eccentric-Only Nordic Curl',
        'Yo-Yo Leg Curl',
        'BFR Bodyweight Squat',
        'BFR Walking',
        'BFR Leg Extension Machine',
        'BFR Hamstring Curl',
        'BFR Calf Raise',
        'BFR Arm Curl',
        '90/90 Hip Switches',
        'Worlds Greatest Stretch',
        'Thoracic Spine Windmills',
        'Ankle Dorsiflexion Mobilization',
        'Hip Flexor Stretch with Posterior Tilt',
        'Band-Dislocated Shoulder Pass-Through',
        'Scapular Wall Slides',
        'Adductor Rock Backs',
        'Couch Stretch',
        'Lat Hang with Active Depression',
        'Atlas Stone Load',
        'Sandbag Shouldering',
        'Yoke Walk',
        'Sled Push',
        'Sled Drag',
        'Keg Toss',
        'Log Press',
        'Axle Bar Deadlift',
        'Battle Ropes Waves',
        'Battle Ropes Slams',
        'Assault Bike Sprint',
        'Rower Intervals',
        'Burpee',
        'Burpee Box Jump Over',
        'Mountain Climbers',
        'Bear Crawl'
    )
);

-- Remove exercise physical qualities mappings
DELETE FROM exercise_physical_qualities 
WHERE exercise_id IN (
    SELECT id FROM exercises WHERE name IN (
        'Lunge to Step-Up with Knee Drive Complex',
        'Romanian Deadlift to Box Jump Complex',
        'Split Squat to Lateral Bound Complex',
        'Front Squat to Push Press Complex',
        'Nordic Curl Eccentric to Hip Extension Complex',
        'Cossack Squat to Skater Hop Complex',
        'Pull-Up to Muscle-Up Transition Complex',
        'Inverted Row to Push-Up Complex',
        'Farmers Carry to Overhead Press Complex',
        'Renegade Row to Push-Up Complex',
        'Face Pull to External Rotation Complex',
        'Z Press to Landmine Press Complex',
        'Trap Bar Deadlift to Vertical Jump Contrast',
        'Bench Press to Medicine Ball Chest Pass Contrast',
        'Power Clean to Broad Jump Complex',
        'Back Squat to Hurdle Hop Complex',
        'Weighted Pull-Up to Clap Push-Up Contrast',
        'Snatch Pull to Overhead Med Ball Slam Complex',
        'Hang Power Clean from Mid-Thigh',
        'Hang Power Snatch from Hip Pocket',
        'Clean Pull from Blocks',
        'Snatch Pull from Blocks',
        'Push Jerk from Rack',
        'Split Jerk',
        'Muscle Snatch',
        'Behind Neck Push Press',
        'Tall Kneeling Clean',
        'Tall Kneeling Snatch',
        'Mid-Thigh Clean Isometric Hold',
        'Overhead Squat Balance',
        'Curtsy Lunge',
        'Step-Down from Box',
        'Single-Leg Romanian Deadlift',
        'Pistol Squat Progression',
        'Lateral Lunge (Cossack)',
        'Single-Leg Box Squat',
        'Reverse Lunge with Torso Rotation',
        'Single-Leg Calf Raise',
        'Adductor Slide',
        'Single-Leg Glute Bridge March',
        'Farmers Walk',
        'Suitcase Carry',
        'Rack Carry',
        'Overhead Carry',
        'Waiters Walk',
        'Zercher Carry',
        'Front Rack Carry',
        'Single-Arm Bottoms-Up Kettlebell Carry',
        'Pallof Press',
        'Pallof Press with Rotation',
        'Ab Wheel Rollout',
        'Stir the Pot',
        'Dead Bug',
        'Bird Dog',
        'Side Plank with Hip Dip',
        'Cable Chop',
        'Cable Lift',
        'McGill Big 3 Circuit',
        'Pogo Hop',
        'Ankle Hops',
        'Line Hops',
        'Tuck Jump',
        'Pike Jump',
        '180° Jump',
        'Single-Leg Hops in Place',
        'Single-Leg Hops for Distance',
        'Bounding for Distance',
        'Depth Drop to Stick',
        'Depth Jump to Max Vertical',
        'Shock Lateral Bounds',
        'Flywheel Squat',
        'Flywheel RDL',
        'Flywheel Calf Raise',
        'Eccentric-Only Pull-Up',
        'Eccentric-Only Nordic Curl',
        'Yo-Yo Leg Curl',
        'BFR Bodyweight Squat',
        'BFR Walking',
        'BFR Leg Extension Machine',
        'BFR Hamstring Curl',
        'BFR Calf Raise',
        'BFR Arm Curl',
        '90/90 Hip Switches',
        'Worlds Greatest Stretch',
        'Thoracic Spine Windmills',
        'Ankle Dorsiflexion Mobilization',
        'Hip Flexor Stretch with Posterior Tilt',
        'Band-Dislocated Shoulder Pass-Through',
        'Scapular Wall Slides',
        'Adductor Rock Backs',
        'Couch Stretch',
        'Lat Hang with Active Depression',
        'Atlas Stone Load',
        'Sandbag Shouldering',
        'Yoke Walk',
        'Sled Push',
        'Sled Drag',
        'Keg Toss',
        'Log Press',
        'Axle Bar Deadlift',
        'Battle Ropes Waves',
        'Battle Ropes Slams',
        'Assault Bike Sprint',
        'Rower Intervals',
        'Burpee',
        'Burpee Box Jump Over',
        'Mountain Climbers',
        'Bear Crawl'
    )
);

-- Remove exercise training methods mappings
DELETE FROM exercise_training_methods 
WHERE exercise_id IN (
    SELECT id FROM exercises WHERE name IN (
        'Lunge to Step-Up with Knee Drive Complex',
        'Romanian Deadlift to Box Jump Complex',
        'Split Squat to Lateral Bound Complex',
        'Front Squat to Push Press Complex',
        'Nordic Curl Eccentric to Hip Extension Complex',
        'Cossack Squat to Skater Hop Complex',
        'Pull-Up to Muscle-Up Transition Complex',
        'Inverted Row to Push-Up Complex',
        'Farmers Carry to Overhead Press Complex',
        'Renegade Row to Push-Up Complex',
        'Face Pull to External Rotation Complex',
        'Z Press to Landmine Press Complex',
        'Trap Bar Deadlift to Vertical Jump Contrast',
        'Bench Press to Medicine Ball Chest Pass Contrast',
        'Power Clean to Broad Jump Complex',
        'Back Squat to Hurdle Hop Complex',
        'Weighted Pull-Up to Clap Push-Up Contrast',
        'Snatch Pull to Overhead Med Ball Slam Complex',
        'Hang Power Clean from Mid-Thigh',
        'Hang Power Snatch from Hip Pocket',
        'Clean Pull from Blocks',
        'Snatch Pull from Blocks',
        'Push Jerk from Rack',
        'Split Jerk',
        'Muscle Snatch',
        'Behind Neck Push Press',
        'Tall Kneeling Clean',
        'Tall Kneeling Snatch',
        'Mid-Thigh Clean Isometric Hold',
        'Overhead Squat Balance',
        'Curtsy Lunge',
        'Step-Down from Box',
        'Single-Leg Romanian Deadlift',
        'Pistol Squat Progression',
        'Lateral Lunge (Cossack)',
        'Single-Leg Box Squat',
        'Reverse Lunge with Torso Rotation',
        'Single-Leg Calf Raise',
        'Adductor Slide',
        'Single-Leg Glute Bridge March',
        'Farmers Walk',
        'Suitcase Carry',
        'Rack Carry',
        'Overhead Carry',
        'Waiters Walk',
        'Zercher Carry',
        'Front Rack Carry',
        'Single-Arm Bottoms-Up Kettlebell Carry',
        'Pallof Press',
        'Pallof Press with Rotation',
        'Ab Wheel Rollout',
        'Stir the Pot',
        'Dead Bug',
        'Bird Dog',
        'Side Plank with Hip Dip',
        'Cable Chop',
        'Cable Lift',
        'McGill Big 3 Circuit',
        'Pogo Hop',
        'Ankle Hops',
        'Line Hops',
        'Tuck Jump',
        'Pike Jump',
        '180° Jump',
        'Single-Leg Hops in Place',
        'Single-Leg Hops for Distance',
        'Bounding for Distance',
        'Depth Drop to Stick',
        'Depth Jump to Max Vertical',
        'Shock Lateral Bounds',
        'Flywheel Squat',
        'Flywheel RDL',
        'Flywheel Calf Raise',
        'Eccentric-Only Pull-Up',
        'Eccentric-Only Nordic Curl',
        'Yo-Yo Leg Curl',
        'BFR Bodyweight Squat',
        'BFR Walking',
        'BFR Leg Extension Machine',
        'BFR Hamstring Curl',
        'BFR Calf Raise',
        'BFR Arm Curl',
        '90/90 Hip Switches',
        'Worlds Greatest Stretch',
        'Thoracic Spine Windmills',
        'Ankle Dorsiflexion Mobilization',
        'Hip Flexor Stretch with Posterior Tilt',
        'Band-Dislocated Shoulder Pass-Through',
        'Scapular Wall Slides',
        'Adductor Rock Backs',
        'Couch Stretch',
        'Lat Hang with Active Depression',
        'Atlas Stone Load',
        'Sandbag Shouldering',
        'Yoke Walk',
        'Sled Push',
        'Sled Drag',
        'Keg Toss',
        'Log Press',
        'Axle Bar Deadlift',
        'Battle Ropes Waves',
        'Battle Ropes Slams',
        'Assault Bike Sprint',
        'Rower Intervals',
        'Burpee',
        'Burpee Box Jump Over',
        'Mountain Climbers',
        'Bear Crawl'
    )
);

-- Remove exercise sport mappings
DELETE FROM exercise_sport_mapping 
WHERE exercise_id IN (
    SELECT id FROM exercises WHERE name IN (
        'Lunge to Step-Up with Knee Drive Complex',
        'Romanian Deadlift to Box Jump Complex',
        'Split Squat to Lateral Bound Complex',
        'Front Squat to Push Press Complex',
        'Nordic Curl Eccentric to Hip Extension Complex',
        'Cossack Squat to Skater Hop Complex',
        'Pull-Up to Muscle-Up Transition Complex',
        'Inverted Row to Push-Up Complex',
        'Farmers Carry to Overhead Press Complex',
        'Renegade Row to Push-Up Complex',
        'Face Pull to External Rotation Complex',
        'Z Press to Landmine Press Complex',
        'Trap Bar Deadlift to Vertical Jump Contrast',
        'Bench Press to Medicine Ball Chest Pass Contrast',
        'Power Clean to Broad Jump Complex',
        'Back Squat to Hurdle Hop Complex',
        'Weighted Pull-Up to Clap Push-Up Contrast',
        'Snatch Pull to Overhead Med Ball Slam Complex',
        'Hang Power Clean from Mid-Thigh',
        'Hang Power Snatch from Hip Pocket',
        'Clean Pull from Blocks',
        'Snatch Pull from Blocks',
        'Push Jerk from Rack',
        'Split Jerk',
        'Muscle Snatch',
        'Behind Neck Push Press',
        'Tall Kneeling Clean',
        'Tall Kneeling Snatch',
        'Mid-Thigh Clean Isometric Hold',
        'Overhead Squat Balance',
        'Curtsy Lunge',
        'Step-Down from Box',
        'Single-Leg Romanian Deadlift',
        'Pistol Squat Progression',
        'Lateral Lunge (Cossack)',
        'Single-Leg Box Squat',
        'Reverse Lunge with Torso Rotation',
        'Single-Leg Calf Raise',
        'Adductor Slide',
        'Single-Leg Glute Bridge March',
        'Farmers Walk',
        'Suitcase Carry',
        'Rack Carry',
        'Overhead Carry',
        'Waiters Walk',
        'Zercher Carry',
        'Front Rack Carry',
        'Single-Arm Bottoms-Up Kettlebell Carry',
        'Pallof Press',
        'Pallof Press with Rotation',
        'Ab Wheel Rollout',
        'Stir the Pot',
        'Dead Bug',
        'Bird Dog',
        'Side Plank with Hip Dip',
        'Cable Chop',
        'Cable Lift',
        'McGill Big 3 Circuit',
        'Pogo Hop',
        'Ankle Hops',
        'Line Hops',
        'Tuck Jump',
        'Pike Jump',
        '180° Jump',
        'Single-Leg Hops in Place',
        'Single-Leg Hops for Distance',
        'Bounding for Distance',
        'Depth Drop to Stick',
        'Depth Jump to Max Vertical',
        'Shock Lateral Bounds',
        'Flywheel Squat',
        'Flywheel RDL',
        'Flywheel Calf Raise',
        'Eccentric-Only Pull-Up',
        'Eccentric-Only Nordic Curl',
        'Yo-Yo Leg Curl',
        'BFR Bodyweight Squat',
        'BFR Walking',
        'BFR Leg Extension Machine',
        'BFR Hamstring Curl',
        'BFR Calf Raise',
        'BFR Arm Curl',
        '90/90 Hip Switches',
        'Worlds Greatest Stretch',
        'Thoracic Spine Windmills',
        'Ankle Dorsiflexion Mobilization',
        'Hip Flexor Stretch with Posterior Tilt',
        'Band-Dislocated Shoulder Pass-Through',
        'Scapular Wall Slides',
        'Adductor Rock Backs',
        'Couch Stretch',
        'Lat Hang with Active Depression',
        'Atlas Stone Load',
        'Sandbag Shouldering',
        'Yoke Walk',
        'Sled Push',
        'Sled Drag',
        'Keg Toss',
        'Log Press',
        'Axle Bar Deadlift',
        'Battle Ropes Waves',
        'Battle Ropes Slams',
        'Assault Bike Sprint',
        'Rower Intervals',
        'Burpee',
        'Burpee Box Jump Over',
        'Mountain Climbers',
        'Bear Crawl'
    )
);

-- Remove the exercises themselves
DELETE FROM exercises WHERE name IN (
    -- Complexes
    'Lunge to Step-Up with Knee Drive Complex',
    'Romanian Deadlift to Box Jump Complex',
    'Split Squat to Lateral Bound Complex',
    'Front Squat to Push Press Complex',
    'Nordic Curl Eccentric to Hip Extension Complex',
    'Cossack Squat to Skater Hop Complex',
    'Pull-Up to Muscle-Up Transition Complex',
    'Inverted Row to Push-Up Complex',
    'Farmers Carry to Overhead Press Complex',
    'Renegade Row to Push-Up Complex',
    'Face Pull to External Rotation Complex',
    'Z Press to Landmine Press Complex',
    'Trap Bar Deadlift to Vertical Jump Contrast',
    'Bench Press to Medicine Ball Chest Pass Contrast',
    'Power Clean to Broad Jump Complex',
    'Back Squat to Hurdle Hop Complex',
    'Weighted Pull-Up to Clap Push-Up Contrast',
    'Snatch Pull to Overhead Med Ball Slam Complex',
    -- Olympic variations
    'Hang Power Clean from Mid-Thigh',
    'Hang Power Snatch from Hip Pocket',
    'Clean Pull from Blocks',
    'Snatch Pull from Blocks',
    'Push Jerk from Rack',
    'Split Jerk',
    'Muscle Snatch',
    'Behind Neck Push Press',
    'Tall Kneeling Clean',
    'Tall Kneeling Snatch',
    'Mid-Thigh Clean Isometric Hold',
    'Overhead Squat Balance',
    -- Unilateral lower body
    'Curtsy Lunge',
    'Step-Down from Box',
    'Single-Leg Romanian Deadlift',
    'Pistol Squat Progression',
    'Lateral Lunge (Cossack)',
    'Single-Leg Box Squat',
    'Reverse Lunge with Torso Rotation',
    'Single-Leg Calf Raise',
    'Adductor Slide',
    'Single-Leg Glute Bridge March',
    -- Loaded carries
    'Farmers Walk',
    'Suitcase Carry',
    'Rack Carry',
    'Overhead Carry',
    'Waiters Walk',
    'Zercher Carry',
    'Front Rack Carry',
    'Single-Arm Bottoms-Up Kettlebell Carry',
    -- Core anti-movement
    'Pallof Press',
    'Pallof Press with Rotation',
    'Ab Wheel Rollout',
    'Stir the Pot',
    'Dead Bug',
    'Bird Dog',
    'Side Plank with Hip Dip',
    'Cable Chop',
    'Cable Lift',
    'McGill Big 3 Circuit',
    -- Plyometrics
    'Pogo Hop',
    'Ankle Hops',
    'Line Hops',
    'Tuck Jump',
    'Pike Jump',
    '180° Jump',
    'Single-Leg Hops in Place',
    'Single-Leg Hops for Distance',
    'Bounding for Distance',
    'Depth Drop to Stick',
    'Depth Jump to Max Vertical',
    'Shock Lateral Bounds',
    -- Eccentric overload
    'Flywheel Squat',
    'Flywheel RDL',
    'Flywheel Calf Raise',
    'Eccentric-Only Pull-Up',
    'Eccentric-Only Nordic Curl',
    'Yo-Yo Leg Curl',
    -- BFR exercises
    'BFR Bodyweight Squat',
    'BFR Walking',
    'BFR Leg Extension Machine',
    'BFR Hamstring Curl',
    'BFR Calf Raise',
    'BFR Arm Curl',
    -- Mobility & prehab
    '90/90 Hip Switches',
    'Worlds Greatest Stretch',
    'Thoracic Spine Windmills',
    'Ankle Dorsiflexion Mobilization',
    'Hip Flexor Stretch with Posterior Tilt',
    'Band-Dislocated Shoulder Pass-Through',
    'Scapular Wall Slides',
    'Adductor Rock Backs',
    'Couch Stretch',
    'Lat Hang with Active Depression',
    -- Strongman
    'Atlas Stone Load',
    'Sandbag Shouldering',
    'Yoke Walk',
    'Sled Push',
    'Sled Drag',
    'Keg Toss',
    'Log Press',
    'Axle Bar Deadlift',
    -- Conditioning
    'Battle Ropes Waves',
    'Battle Ropes Slams',
    'Assault Bike Sprint',
    'Rower Intervals',
    'Burpee',
    'Burpee Box Jump Over',
    'Mountain Climbers',
    'Bear Crawl'
);

-- Remove new tags (only if they have no other associations)
DELETE FROM tags WHERE name IN (
    'Complex',
    'Contrast',
    'Combo',
    'Circuit',
    'Density',
    'Flow'
);

COMMIT;
