-- Migration 000032: Phase 7 - Bridge Movements, Pain-Safe Variants & Re-entry Protocols
-- Adds 35 critical exercises for injury prevention and return-to-play
-- Source: IOC Consensus, Stuart McGill Research, Premier League Medical

INSERT INTO exercises (id, name, category, subcategory, movement_pattern, equipment, difficulty, source_organization, description, coaching_cues, common_errors, contraindications, regressions, progressions, equipment_alternatives, is_pain_safe, created_at) VALUES
-- BRIDGE MOVEMENTS (15)
(301, 'Box Squat to Stand', 'Strength', 'Bridge', 'Bilateral Knee', 'Barbell/Box', 'Intermediate', 'IOC Consensus', 'Transition from seated box squat to standing without hands', 'Keep chest up, drive through heels, engage core before standing', 'Rounding back, using momentum, knees caving in', 'Acute hip flexor strain', 'Use higher box, hand assistance', 'Add weight, reduce box height', 'Chair/Bench', true, NOW()),
(302, 'Incline Push-Up', 'Strength', 'Bridge', 'Upper Push', 'Bench/Box', 'Beginner', 'NSCA', 'Push-up performed with hands elevated to reduce load', 'Straight line body, lower chest to surface, full extension', 'Hips sagging, partial range of motion', 'Acute wrist pain', 'Wall push-up', 'Decline push-up', 'Wall/Railing', true, NOW()),
(303, 'Assisted Pull-Up', 'Strength', 'Bridge', 'Upper Pull', 'Band/Machine', 'Intermediate', 'EXOS', 'Vertical pull with band or machine assistance', 'Full hang to chin over bar, controlled descent', 'Kipping, incomplete extension', 'Acute shoulder instability', 'Lat pulldown', 'Weighted pull-up', 'Lat Pulldown Machine', true, NOW()),
(304, 'Half-Kneeling Pallof Press', 'Core', 'Bridge', 'Anti-Rotation', 'Cable/Band', 'Beginner', 'Stuart McGill', 'Rotational stability in half-kneeling stance', 'Brace core, press straight out, resist rotation', 'Leaning, rotating torso', 'Acute knee pain (bottom leg)', 'Seated Pallof', 'Standing Pallof', 'Band anchored low', true, NOW()),
(305, 'Supported Single Leg RDL', 'Strength', 'Bridge', 'Unilateral Hip', 'TRX/Rack', 'Intermediate', 'UKSCA', 'Single leg hinge with hand support for balance', 'Hinge at hip, keep back flat, slight knee bend', 'Rounding back, losing balance', 'Acute ankle sprain', 'Double leg RDL', 'Unassisted Single Leg RDL', 'Wall for balance', true, NOW()),
(306, 'Wall Sit', 'Strength', 'Bridge', 'Bilateral Knee', 'Bodyweight', 'Beginner', 'Premier League Medical', 'Isometric squat hold against wall', 'Back flat against wall, knees at 90 degrees', 'Knees past toes, rounding lower back', 'Acute patellar tendonitis (severe)', 'Higher angle sit', 'Weighted wall sit', 'N/A', true, NOW()),
(307, 'Glute Bridge March', 'Activation', 'Bridge', 'Hip Extension', 'Mat', 'Beginner', 'Stuart McGill', 'Bridge hold with alternating leg lift', 'Squeeze glutes, keep hips level, small marches', 'Hips dropping, arching lower back', 'Acute lumbar disc herniation', 'Static Glute Bridge', 'Single Leg Bridge', 'N/A', true, NOW()),
(308, 'Quadruped Rock Back', 'Mobility', 'Bridge', 'Spinal Flexion', 'Mat', 'Beginner', 'Stuart McGill', 'Rocking hips back to heels on hands and knees', 'Keep spine neutral, rock until tension, return', 'Rounding spine aggressively', 'Acute wrist pain', 'Smaller range', 'Add thoracic rotation', 'N/A', true, NOW()),
(309, 'Dead Bug', 'Core', 'Bridge', 'Anti-Extension', 'Mat', 'Beginner', 'Stuart McGill', 'Supine limb movement maintaining spinal contact', 'Press lower back to floor, opposite arm/leg reach', 'Arching back, moving too fast', 'Acute neck pain', 'Arms only', 'Add resistance band', 'N/A', true, NOW()),
(310, 'Bird Dog', 'Core', 'Bridge', 'Anti-Rotation', 'Mat', 'Beginner', 'Stuart McGill', 'Quadruped opposite arm/leg extension', 'Neutral spine, extend fully, hold briefly', 'Rounding back, rotating hips', 'Acute shoulder impingement', 'Arm only/Leg only', 'Add resistance', 'N/A', true, NOW()),
(311, 'Split Stance Landmine Press', 'Strength', 'Bridge', 'Upper Push', 'Landmine', 'Intermediate', 'EXOS', 'Overhead press in split stance for stability', 'Brace core, press up and slightly forward', 'Leaning back, pressing straight up', 'Acute shoulder labral tear', 'Half-kneeling press', 'Standing landmine press', 'DB Overhead Press', true, NOW()),
(312, 'Step-Up to Balance', 'Strength', 'Bridge', 'Unilateral Knee', 'Box', 'Intermediate', 'NSCA', 'Step up and hold balance on top leg', 'Drive through heel, control down, pause on top', 'Pushing off bottom foot, rushing', 'Acute ankle instability', 'Lower box', 'Add overhead reach', 'N/A', true, NOW()),
(313, 'Farmers Carry (Light)', 'Conditioning', 'Bridge', 'Loaded Carry', 'KB/DB', 'Beginner', 'StrongFirst', 'Walking with light loads for gait re-education', 'Tall posture, shoulders back, steady steps', 'Leaning, shrugging shoulders', 'Acute grip injury', 'Suitcase carry (one side)', 'Heavy farmers carry', 'Water jugs', true, NOW()),
(314, 'Sidelying Clamshell', 'Activation', 'Bridge', 'Hip Abduction', 'Band', 'Beginner', 'Premier League Medical', 'Hip external rotation in sidelying', 'Keep feet together, open knee, don''t roll back', 'Rolling hips back, using momentum', 'Acute lateral hip bursitis', 'No band', 'Heel tap progression', 'N/A', true, NOW()),
(315, 'Prone Y-T-W', 'Activation', 'Bridge', 'Scapular Stability', 'Mat/Bench', 'Beginner', 'ASCA', 'Scapular retraction/depression patterns', 'Thumb up, squeeze shoulder blades, controlled lift', 'Using neck muscles, lifting too high', 'Acute cervical spine issue', 'Smaller range', 'Add light weights', 'N/A', true, NOW()),

-- PAIN-SAFE VARIANTS (10)
(316, 'Goblet Squat', 'Strength', 'Pain-Safe', 'Bilateral Knee', 'KB/DB', 'Intermediate', 'StrongFirst', 'Front-loaded squat promoting upright torso', 'Elbows inside knees, deep squat, chest up', 'Leaning forward, heels lifting', 'Severe knee effusion', 'Box goblet squat', 'Heavy goblet squat', 'Dumbbell', true, NOW()),
(317, 'Trap Bar Deadlift', 'Strength', 'Pain-Safe', 'Bilateral Hip', 'Trap Bar', 'Intermediate', 'NSCA', 'Center-loaded deadlift reducing shear force', 'Hips down, chest up, push floor away', 'Rounding back, hips rising first', 'Acute lumbar strain', 'Elevated handles', 'Heavy conventional', 'N/A', true, NOW()),
(318, 'Neutral Grip DB Bench', 'Strength', 'Pain-Safe', 'Upper Push', 'DB', 'Intermediate', 'ACSМ', 'Horizontal press with neutral grip', 'Shoulders packed, press up and slightly in', 'Flaring elbows, bouncing bar', 'Acute AC joint separation', 'Floor press', 'Incline DB press', 'N/A', true, NOW()),
(319, 'Chest Supported Row', 'Strength', 'Pain-Safe', 'Upper Pull', 'DB/Bench', 'Intermediate', 'UKSCA', 'Horizontal pull eliminating lower back stress', 'Chest on incline bench, pull to hips', 'Using momentum, shrugging', 'Acute pectoral strain', 'Lighter weight', 'Single arm row', 'Machine Row', true, NOW()),
(320, 'Seated Cable Row', 'Strength', 'Pain-Safe', 'Upper Pull', 'Cable', 'Beginner', 'EXOS', 'Supported horizontal pull', 'Sit tall, pull to belly button, squeeze back', 'Leaning back too far, rounding spine', 'Acute lumbar disc issue', 'Light weight', 'Single arm row', 'Band Row', true, NOW()),
(321, 'Reverse Hyperextension', 'Posterior Chain', 'Pain-Safe', 'Hip Extension', 'Machine', 'Intermediate', 'Louie Simmons', 'Hip extension with spine decompression', 'Hold handles, lift legs with glutes, control down', 'Swinging, using lower back', 'Acute hamstring avulsion', 'Bodyweight only', 'Add weight', 'Swiss Ball Reverse Hyper', true, NOW()),
(322, 'Swiss Ball Hamstring Curl', 'Posterior Chain', 'Pain-Safe', 'Knee Flexion', 'Swiss Ball', 'Intermediate', 'ASCA', 'Eccentric/concentric curl on unstable surface', 'Hips high, curl ball in, control out', 'Hips dropping, cramping', 'Acute calf strain', 'Partial range', 'Single leg curl', 'Slider Curl', true, NOW()),
(323, 'Landmine Arc Row', 'Strength', 'Pain-Safe', 'Upper Pull', 'Landmine', 'Intermediate', 'EXOS', 'Angled row reducing shear on spine', 'Staggered stance, row to hip, rotate slightly', 'Rounding back, pulling too high', 'Acute rotator cuff tear', 'Two hand hold', 'Single arm heavy', 'Cable Row', true, NOW()),
(324, 'Zercher Squat', 'Strength', 'Pain-Safe', 'Bilateral Knee', 'Barbell', 'Advanced', 'StrongFirst', 'Front-loaded squat in elbow crease', 'Elbows on quads, upright torso, deep squat', 'Elbow pain, rounding back', 'Acute elbow bursitis', 'Goblet squat', 'Heavy Zercher', 'Sandbag', true, NOW()),
(325, 'Safety Bar Squat', 'Strength', 'Pain-Safe', 'Bilateral Knee', 'Safety Bar', 'Advanced', 'Westside Barbell', 'Specialty bar reducing shoulder stress', 'Lean into camber, squat deep, drive up', 'Leaning too far forward', 'Acute cervical spine issue', 'Goblet squat', 'Heavy Safety Bar', 'Front Squat', true, NOW()),

-- RE-ENTRY / RETURN TO PLAY (10)
(326, 'Ankle Dorsiflexion w/ Band', 'Mobility', 'Re-Entry', 'Ankle Mobility', 'Band', 'Beginner', 'IOC Consensus', 'Restoring ankle dorsiflexion range', 'Band around foot, pull knee over toe', 'Compensating with hip', 'Acute ankle fracture', 'Active ROM only', 'Weighted dorsiflexion', 'N/A', true, NOW()),
(327, 'Hip 90/90 Switch', 'Mobility', 'Re-Entry', 'Hip Rotation', 'Mat', 'Beginner', 'Kelly Starrett', 'Internal/external hip rotation flow', 'Sit tall, rotate knees side to side', 'Forcing range, rounding back', 'Acute hip labral tear', 'Assisted switch', 'Weighted switch', 'N/A', true, NOW()),
(328, 'Thoracic Extension over Foam Roller', 'Mobility', 'Re-Entry', 'Thoracic Mobility', 'Foam Roller', 'Beginner', 'Kelly Starrett', 'Extending thoracic spine over roller', 'Support head, extend over roller, breathe', 'Crunching neck, rolling too fast', 'Acute thoracic fracture', 'Static hold', 'Dynamic extension', 'N/A', true, NOW()),
(329, 'Scapular Push-Up', 'Activation', 'Re-Entry', 'Scapular Stability', 'Mat', 'Beginner', 'EXOS', 'Protraction/retraction without elbow bend', 'Arms straight, move shoulder blades only', 'Bending elbows', 'Acute wrist fracture', 'Wall scapular push-up', 'Elevated feet', 'N/A', true, NOW()),
(330, 'Single Leg Balance Reach', 'Balance', 'Re-Entry', 'Proprioception', 'Mat', 'Beginner', 'UKSCA', 'Single leg stance with reach pattern', 'Soft knee, reach opposite hand, maintain balance', 'Touching down, locking knee', 'Acute vestibular disorder', 'Two leg balance', 'Eyes closed', 'N/A', true, NOW()),
(331, 'Walking Knee Hugs', 'Mobility', 'Re-Entry', 'Hip Extension', 'Bodyweight', 'Beginner', 'ALTIS', 'Dynamic stretch for glutes/hips', 'Pull knee to chest, step, alternate', 'Rounding lower back', 'Acute hip flexor strain', 'Static hug', 'Add rotation', 'N/A', true, NOW()),
(332, 'Walking Quad Stretch', 'Mobility', 'Re-Entry', 'Knee Flexion', 'Bodyweight', 'Beginner', 'ALTIS', 'Dynamic stretch for quads', 'Pull heel to glute, step, alternate', 'Leaning forward, arching back', 'Acute knee ligament injury', 'Static stretch', 'Prone quad stretch', 'N/A', true, NOW()),
(333, 'Inchworm', 'Mobility', 'Re-Entry', 'Full Body', 'Bodyweight', 'Beginner', 'EXOS', 'Walk out to plank and back', 'Hands walk out, pause in plank, walk back', 'Sagging hips, rushing', 'Acute wrist pain', 'Walk out only', 'Add push-up', 'N/A', true, NOW()),
(334, 'Lateral Lunge to Stand', 'Mobility', 'Re-Entry', 'Frontal Plane', 'Bodyweight', 'Beginner', 'IOC Consensus', 'Frontal plane lunge pattern', 'Step side, sink hips, return to stand', 'Knee caving in, leaning too far', 'Acute groin strain', 'Shallow lunge', 'Deep lunge with reach', 'N/A', true, NOW()),
(335, 'Single Leg Calf Raise', 'Strength', 'Re-Entry', 'Plantar Flexion', 'Step', 'Beginner', 'Premier League Medical', 'Isolated calf strengthening', 'Raise up on toes, control down, single leg', 'Bouncing, incomplete range', 'Acute Achilles rupture', 'Double leg', 'Weighted single leg', 'N/A', true, NOW());

-- Update schema to add is_pain_safe column if not exists (handled in app logic usually, but explicit here)
-- Note: Ensure 'is_pain_safe' column exists in exercises table. 
-- If running on existing DB, you might need: 
-- ALTER TABLE exercises ADD COLUMN IF NOT EXISTS is_pain_safe BOOLEAN DEFAULT false;

COMMENT ON COLUMN exercises.is_pain_safe IS 'Indicates if exercise is suitable for pain-modified training or return-to-play protocols';
