-- Forge Exercise Intelligence Database - Migration 000008 (Up)
-- Description: Seed Cricket-specific roles, performance drivers, assessments, benchmarks, deficits, and mappings.

-- -------------------------------------------------------------
-- Seed Roles
-- -------------------------------------------------------------
INSERT INTO roles (sport_id, name, description) VALUES
(
    (SELECT id FROM sports WHERE name = 'Cricket'),
    'Fast Bowler',
    'High-intensity bowler requiring extreme lower body bracing forces, shoulder/trunk rotational velocity, and repeat sprint ability.'
),
(
    (SELECT id FROM sports WHERE name = 'Cricket'),
    'Spinner',
    'Rotational specialist requiring extreme trunk/hip separation, finger-wrist snap capacity, and shoulder rotator cuff endurance.'
),
(
    (SELECT id FROM sports WHERE name = 'Cricket'),
    'Batter',
    'Requires high-velocity bat speed, quick reaction times, hand-eye coordination, and multi-directional acceleration/deceleration.'
),
(
    (SELECT id FROM sports WHERE name = 'Cricket'),
    'Wicket Keeper',
    'Squat-dominant specialist requiring isometric lower body endurance, ultra-fast lateral reactive agility, and hand speed.'
),
(
    (SELECT id FROM sports WHERE name = 'Cricket'),
    'All Rounder',
    'Generalist requiring balanced development of both high workload capacity (aerobic/anaerobic) and explosive power.'
);

-- -------------------------------------------------------------
-- Seed Performance Drivers (Physical Demands)
-- -------------------------------------------------------------

-- Drivers for Fast Bowler
INSERT INTO performance_drivers (role_id, name, description, priority) VALUES
(
    (SELECT id FROM roles WHERE name = 'Fast Bowler' AND sport_id = (SELECT id FROM sports WHERE name = 'Cricket')),
    'Front Foot Brace Force',
    'Ability of the front leg to lock and brace during landing, transmitting vertical ground reaction forces into ball release speed.',
    'Primary'
),
(
    (SELECT id FROM roles WHERE name = 'Fast Bowler' AND sport_id = (SELECT id FROM sports WHERE name = 'Cricket')),
    'Trunk Flexion Rotational Power',
    'Ability of the torso to flex and rotate explosively at the release point to maximize ball velocity.',
    'Primary'
);

-- Drivers for Spinner
INSERT INTO performance_drivers (role_id, name, description, priority) VALUES
(
    (SELECT id FROM roles WHERE name = 'Spinner' AND sport_id = (SELECT id FROM sports WHERE name = 'Cricket')),
    'Hip-Shoulder Separation Torque',
    'Torque generated by rotating the pelvis ahead of the upper torso, key to spinning the ball.',
    'Primary'
);

-- Drivers for Batter
INSERT INTO performance_drivers (role_id, name, description, priority) VALUES
(
    (SELECT id FROM roles WHERE name = 'Batter' AND sport_id = (SELECT id FROM sports WHERE name = 'Cricket')),
    'Lateral Deceleration Capacity',
    'Ability to decelerate and change direction rapidly when running between wickets or adjusting to short balls.',
    'Primary'
);

-- Drivers for Wicket Keeper
INSERT INTO performance_drivers (role_id, name, description, priority) VALUES
(
    (SELECT id FROM roles WHERE name = 'Wicket Keeper' AND sport_id = (SELECT id FROM sports WHERE name = 'Cricket')),
    'Lower Body Isometric Squat Endurance',
    'Ability to hold deep squat postures for extended spells without performance degradation.',
    'Primary'
);

-- -------------------------------------------------------------
-- Seed Assessments
-- -------------------------------------------------------------
INSERT INTO assessments (name, description, metric_unit) VALUES
(
    'Isometric Mid-Thigh Pull (IMTP)',
    'A static test performed on dual force plates with the athlete pulling upward at maximum effort. Measures peak force and absolute strength.',
    'N'
),
(
    'Force Plate Countermovement Jump (CMJ)',
    'A vertical jump test measuring jump height, peak power, and rate of force development (RFD).',
    'cm'
),
(
    'Medicine Ball Rotational Velocity Test',
    'Measuring the velocity of a medicine ball rotational throw using radar or velocity sensors.',
    'm/s'
),
(
    'Isometric Wall Sit Squat Hold Test',
    'Holding a single-leg or double-leg wall sit squat at 90 degrees knee flexion. Measures local muscular endurance.',
    's'
)
ON CONFLICT (name) DO NOTHING;

-- -------------------------------------------------------------
-- Map Drivers to Assessments (driver_assessments)
-- -------------------------------------------------------------
INSERT INTO driver_assessments (performance_driver_id, assessment_id) VALUES
(
    (SELECT id FROM performance_drivers WHERE name = 'Front Foot Brace Force'),
    (SELECT id FROM assessments WHERE name = 'Isometric Mid-Thigh Pull (IMTP)')
),
(
    (SELECT id FROM performance_drivers WHERE name = 'Front Foot Brace Force'),
    (SELECT id FROM assessments WHERE name = 'Force Plate Countermovement Jump (CMJ)')
),
(
    (SELECT id FROM performance_drivers WHERE name = 'Trunk Flexion Rotational Power'),
    (SELECT id FROM assessments WHERE name = 'Medicine Ball Rotational Velocity Test')
),
(
    (SELECT id FROM performance_drivers WHERE name = 'Hip-Shoulder Separation Torque'),
    (SELECT id FROM assessments WHERE name = 'Medicine Ball Rotational Velocity Test')
),
(
    (SELECT id FROM performance_drivers WHERE name = 'Lateral Deceleration Capacity'),
    (SELECT id FROM assessments WHERE name = 'Force Plate Countermovement Jump (CMJ)')
),
(
    (SELECT id FROM performance_drivers WHERE name = 'Lower Body Isometric Squat Endurance'),
    (SELECT id FROM assessments WHERE name = 'Isometric Wall Sit Squat Hold Test')
);

-- -------------------------------------------------------------
-- Seed Benchmarks
-- -------------------------------------------------------------
INSERT INTO benchmarks (assessment_id, name, min_value, max_value, classification) VALUES
-- IMTP Peak Force Benchmarks
((SELECT id FROM assessments WHERE name = 'Isometric Mid-Thigh Pull (IMTP)'), 'IMTP Peak Force Elite', 3500.00, NULL, 'Elite'),
((SELECT id FROM assessments WHERE name = 'Isometric Mid-Thigh Pull (IMTP)'), 'IMTP Peak Force Optimal', 3000.00, 3499.99, 'Optimal'),
((SELECT id FROM assessments WHERE name = 'Isometric Mid-Thigh Pull (IMTP)'), 'IMTP Peak Force Sub-optimal', 2200.00, 2999.99, 'Sub-optimal'),
((SELECT id FROM assessments WHERE name = 'Isometric Mid-Thigh Pull (IMTP)'), 'IMTP Peak Force Poor', NULL, 2199.99, 'Poor'),

-- CMJ Jump Height Benchmarks
((SELECT id FROM assessments WHERE name = 'Force Plate Countermovement Jump (CMJ)'), 'CMJ Jump Height Elite', 50.00, NULL, 'Elite'),
((SELECT id FROM assessments WHERE name = 'Force Plate Countermovement Jump (CMJ)'), 'CMJ Jump Height Optimal', 40.00, 49.99, 'Optimal'),
((SELECT id FROM assessments WHERE name = 'Force Plate Countermovement Jump (CMJ)'), 'CMJ Jump Height Sub-optimal', 30.00, 39.99, 'Sub-optimal'),
((SELECT id FROM assessments WHERE name = 'Force Plate Countermovement Jump (CMJ)'), 'CMJ Jump Height Poor', NULL, 29.99, 'Poor'),

-- Medicine Ball Throw Velocity Benchmarks
((SELECT id FROM assessments WHERE name = 'Medicine Ball Rotational Velocity Test'), 'MB Velocity Elite', 12.00, NULL, 'Elite'),
((SELECT id FROM assessments WHERE name = 'Medicine Ball Rotational Velocity Test'), 'MB Velocity Optimal', 10.00, 11.99, 'Optimal'),
((SELECT id FROM assessments WHERE name = 'Medicine Ball Rotational Velocity Test'), 'MB Velocity Sub-optimal', 8.00, 9.99, 'Sub-optimal'),
((SELECT id FROM assessments WHERE name = 'Medicine Ball Rotational Velocity Test'), 'MB Velocity Poor', NULL, 7.99, 'Poor');

-- -------------------------------------------------------------
-- Seed Deficits
-- -------------------------------------------------------------
INSERT INTO deficits (assessment_id, name, description) VALUES
(
    (SELECT id FROM assessments WHERE name = 'Isometric Mid-Thigh Pull (IMTP)'),
    'Lower Body Absolute Strength Deficit',
    'Athlete exhibits sub-optimal peak force capability, reducing front-foot landing brace stiffness.'
),
(
    (SELECT id FROM assessments WHERE name = 'Force Plate Countermovement Jump (CMJ)'),
    'Rate of Force Development Deficit',
    'Athlete is slow to generate vertical force, limiting plyometric reactive power.'
),
(
    (SELECT id FROM assessments WHERE name = 'Medicine Ball Rotational Velocity Test'),
    'Rotational Core Power Deficit',
    'Athlete exhibits low transverse plane throwing velocity, limiting hip-to-shoulder force transfer.'
),
(
    (SELECT id FROM assessments WHERE name = 'Isometric Wall Sit Squat Hold Test'),
    'Local Muscular Endurance Deficit',
    'Athlete lacks quad/glute isometric capacity, causing fatigue during long wicket-keeping stints.'
);

-- -------------------------------------------------------------
-- Seed Deficit <-> Training Method mappings
-- -------------------------------------------------------------
INSERT INTO deficit_training_methods (deficit_id, training_method_id) VALUES
(
    (SELECT id FROM deficits WHERE name = 'Lower Body Absolute Strength Deficit'),
    (SELECT id FROM training_methods WHERE name = 'Cluster Sets')
),
(
    (SELECT id FROM deficits WHERE name = 'Lower Body Absolute Strength Deficit'),
    (SELECT id FROM training_methods WHERE name = 'Velocity-Based Training')
),
(
    (SELECT id FROM deficits WHERE name = 'Rate of Force Development Deficit'),
    (SELECT id FROM training_methods WHERE name = 'Plyometric (Fast)')
),
(
    (SELECT id FROM deficits WHERE name = 'Rate of Force Development Deficit'),
    (SELECT id FROM training_methods WHERE name = 'Contrast Training')
),
(
    (SELECT id FROM deficits WHERE name = 'Rotational Core Power Deficit'),
    (SELECT id FROM training_methods WHERE name = 'Plyometric (Slow)')
),
(
    (SELECT id FROM deficits WHERE name = 'Local Muscular Endurance Deficit'),
    (SELECT id FROM training_methods WHERE name = 'Isometric (Yielding)')
);

-- -------------------------------------------------------------
-- Seed Deficit <-> Movement Template mappings
-- -------------------------------------------------------------
INSERT INTO deficit_movement_templates (deficit_id, movement_template_id) VALUES
(
    (SELECT id FROM deficits WHERE name = 'Lower Body Absolute Strength Deficit'),
    (SELECT id FROM movement_templates WHERE name = 'Lower Body Power')
),
(
    (SELECT id FROM deficits WHERE name = 'Lower Body Absolute Strength Deficit'),
    (SELECT id FROM movement_templates WHERE name = 'Cricket Fast Bowler Power')
),
(
    (SELECT id FROM deficits WHERE name = 'Rate of Force Development Deficit'),
    (SELECT id FROM movement_templates WHERE name = 'Cricket Fast Bowler Power')
),
(
    (SELECT id FROM deficits WHERE name = 'Rate of Force Development Deficit'),
    (SELECT id FROM movement_templates WHERE name = 'Reactive Agility')
),
(
    (SELECT id FROM deficits WHERE name = 'Rotational Core Power Deficit'),
    (SELECT id FROM movement_templates WHERE name = 'Rotational Power')
),
(
    (SELECT id FROM deficits WHERE name = 'Local Muscular Endurance Deficit'),
    (SELECT id FROM movement_templates WHERE name = 'Shoulder Robustness') -- Secondary accessory targets
);
