BLUEPRINTS_DATA = [
    {
        "id": 1,
        "name": "Full Body Strength",
        "purpose": "General strength accrual across all major movement patterns. Highest frequency of each pattern per week.",
        "typical_athlete": "Beginner-intermediate, off-season general population, youth athletes (14-17), sport-generalists",
        "best_training_age": "0-3 years",
        "best_season_phase": ["off_season", "pre_season"],
        "contraindications": "Advanced athletes needing specific peak, late pre-season (<4 weeks to competition), in-season maintenance phase",
        "typical_outcomes": "Consistent strength gains across squat, hinge, press, pull patterns. Improved movement competency. Foundation for advanced training. Works best as a 4-8 week block before progressing to more specialised work.",
        "progression_path": "Strength + Power",
        "regression_path": "Youth Foundation (U14-U20)",
        "mandatory_families": ["DLKD", "DLHD", "HPush", "HPull"],
        "optional_families": ["Core", "Acc", "VPush", "VPull", "Ball"],
        "slot_order": ["Ball", "DLKD", "HPush", "DLHD", "HPull", "Core"],
        "min_session_composition": [
            {"family": "DLKD", "mandatory": True, "count": 1, "notes": "Primary squat pattern"},
            {"family": "DLHD", "mandatory": True, "count": 1, "notes": "Primary hinge pattern"},
            {"family": "HPush", "mandatory": True, "count": 1, "notes": "Horizontal press"},
            {"family": "HPull", "mandatory": True, "count": 1, "notes": "Horizontal pull"},
        ],
    },
    {
        "id": 2,
        "name": "Strength + Power",
        "purpose": "Hybrid strength-power development. Heavy strength + explosive work in same session.",
        "typical_athlete": "Intermediate-advanced, field sport off-season, track & field, rugby pre-season, contact sport athletes",
        "best_training_age": "2-5 years",
        "best_season_phase": ["off_season", "pre_season"],        "contraindications": "Athletes with poor movement quality, early post-injury (<4 weeks cleared), hypertrophy-deficient athletes needing mass first, training age <1 year, in-season maintenance phase",
        "typical_outcomes": "Simultaneous strength and power gains without interference effect. Improved RFD alongside maximal strength. Most commonly used blueprint for serious off-season blocks.",
        "progression_path": "Power + Speed",
        "regression_path": "Full Body Strength",
        "mandatory_families": ["Ball", "DLKD", "DLHD", "HPush"],
        "optional_families": ["Carry", "Sprint", "Rot", "Core"],
        "slot_order": ["Ball", "DLKD", "HPush", "HPull", "DLHD", "Core"],        "min_session_composition": [
            {"family": "Ball", "mandatory": True, "count": 1, "notes": "Explosive primer"},
            {"family": "DLKD", "mandatory": True, "count": 1, "notes": "Heavy compound squat"},
            {"family": "DLHD", "mandatory": True, "count": 1, "notes": "Explosive variant hinge"},
            {"family": "HPush", "mandatory": True, "count": 1, "notes": "Heavy press"},
        ],
    },
    {
        "id": 3,
        "name": "Strength + Conditioning",
        "purpose": "Strength maintenance + energy system development. Common in pre-season / GPP blocks.",
        "typical_athlete": "Team sport, pre-season, returning from off-season break, athletes needing work capacity",
        "best_training_age": "1-4 years",
        "best_season_phase": ["pre_season", "off_season"],        "contraindications": "Athletes needing peak strength (conditioning interferes), low recovery capacity, advanced athletes in specific peaking blocks, in-season maintenance (use Power Maintenance instead), 2-a-day training schedules",
        "typical_outcomes": "Improved work capacity and conditioning base. Strength maintained (not maximised). Best used as a 4-6 week bridge between off-season and pre-season. Higher conditioning tolerance over time.",
        "progression_path": "Full Body Strength",
        "regression_path": "Mixed Modal (GPP)",
        "mandatory_families": ["DLKD", "DLHD", "HPush", "HPull"],
        "optional_families": ["Carry", "Core", "Acc", "Sprint"],
        "slot_order": ["DLKD", "DLHD", "HPush", "HPull", "Core"],        "min_session_composition": [
            {"family": "DLKD", "mandatory": True, "count": 1, "notes": "Either DLKD or DLHD required (not necessarily both per session)"},
            {"family": "DLHD", "mandatory": True, "count": 1, "notes": "Either DLKD or DLHD required (not necessarily both per session)"},
            {"family": "HPush", "mandatory": True, "count": 1, "notes": "Push pattern"},
            {"family": "HPull", "mandatory": True, "count": 1, "notes": "Pull pattern"},
        ],
    },
    {
        "id": 4,
        "name": "Power + Speed",
        "purpose": "Maximise rate of force development + velocity. Low volume, high intensity, full recovery.",
        "typical_athlete": "Advanced field sport, track sprinters, court sport in-season, peaking phase athletes",
        "best_training_age": "3+ years",
        "best_season_phase": ["pre_season", "off_season", "in_season"],        "contraindications": "Strength-deficient athletes (<1.5x BW squat M / <1.2x BW squat F), early post-injury, hypertrophy phase, athletes needing general strength foundation, pre-meet taper week",
        "typical_outcomes": "Improved RFD, sprint speed, jump height, reactive strength. Best for peaking power qualities. Short-term (4-6 week) block not sustainable long-term.",
        "progression_path": "Sprint Development",
        "regression_path": "Strength + Power",
        "mandatory_families": ["Sprint", "Plyo", "Ball"],
        "optional_families": ["DLHD", "HPush", "Core"],
        "slot_order": ["Sprint", "Plyo", "Ball", "DLHD", "Core"],        "min_session_composition": [
            {"family": "Sprint", "mandatory": True, "count": 1, "notes": "Speed primer"},
            {"family": "Plyo", "mandatory": True, "count": 1, "notes": "Plyometric / reactive"},
            {"family": "Ball", "mandatory": True, "count": 1, "notes": "Ballistic throw / lift"},
        ],
    },
    {
        "id": 5,
        "name": "Upper / Lower Split",
        "purpose": "Higher per-session volume per region. Two lower sessions, two upper sessions per microcycle.",
        "typical_athlete": "Intermediate-advanced bodybuilding, strength athletes, athletes tolerating high per-session volume well, hypertrophy-focused",
        "best_training_age": "2-5 years",
        "best_season_phase": ["off_season"],        "contraindications": "Youth/low training age needing full body frequency (3x/week minimum per pattern), in-season with limited session availability, field sport athletes in competition phase, very long season with high practice load",
        "typical_outcomes": "Higher regional volume per session. Good for hypertrophy and strength plateaus. Each body part trained 2x/week with higher per-session volume than full body approaches.",
        "progression_path": "Hypertrophy / Mass Accrual",
        "regression_path": "Full Body Strength",
        "mandatory_families": ["DLKD", "DLHD", "HPush", "HPull"],
        "optional_families": ["Carry", "Core", "Acc", "Rot", "VPush", "VPull"],
        "slot_order": ["Plyo", "DLKD", "DLHD", "VPush", "HPush", "VPull", "HPull", "Carry", "Core", "Acc"],        "min_session_composition": [
            {"family": "DLKD", "mandatory": True, "count": 1, "notes": "Lower day: squat pattern"},
            {"family": "DLHD", "mandatory": True, "count": 1, "notes": "Lower day: hinge pattern"},
            {"family": "HPush", "mandatory": True, "count": 1, "notes": "Upper day: horizontal press"},
            {"family": "HPull", "mandatory": True, "count": 1, "notes": "Upper day: horizontal pull"},
        ],
    },
    {
        "id": 6,
        "name": "Power Maintenance",
        "purpose": "Retain power qualities with minimal fatigue during season. Low dose, high stimulus.",
        "typical_athlete": "In-season team sport, competing court sport, mid-competition phase, tournament blocks",
        "best_training_age": "2+ years",
        "best_season_phase": ["in_season"],        "contraindications": "Off-season (use development blueprints instead), deload/recovery weeks, early return from injury, athletes needing strength development (not yet established), pre-season (too early for maintenance)",
        "typical_outcomes": "Power retained with minimal CNS fatigue. Competitive readiness maintained without compromising recovery. Not a development blueprint but a preservation blueprint.",
        "progression_path": "Strength + Power",
        "regression_path": "Deload / Active Recovery",
        "mandatory_families": ["Ball", "Plyo"],
        "optional_families": ["Sprint", "DLHD", "Core", "Acc"],
        "slot_order": ["Sprint", "Ball", "Plyo", "Core"],        "min_session_composition": [
            {"family": "Ball", "mandatory": True, "count": 1, "notes": "1-2 explosive lifts"},
            {"family": "Plyo", "mandatory": True, "count": 1, "notes": "Low volume plyometric"},
        ],
    },
    {
        "id": 7,
        "name": "Youth Foundation (U14-U20)",
        "purpose": "Build movement literacy, general strength, and athleticism. No specialisation. Fun + competence.",
        "typical_athlete": "Adolescents (13-20), beginner training age, multi-sport athletes, late-maturing athletes",
        "best_training_age": "0-2 years",
        "best_season_phase": ["off_season", "pre_season", "in_season", "transition"],        "contraindications": "Athletes 20+ (move to adult blueprint), sport-specialised seniors in off-season need more specific loading, post-rehab athletes needing targeted protocol, elite-level athletes in peaking phase",
        "typical_outcomes": "Improved movement competency in squat, hinge, lunge, push, pull. General strength foundation. Athletic skill development. Reduced injury risk in sport practice.",
        "progression_path": "Full Body Strength",
        "regression_path": None,
        "mandatory_families": ["DLKD", "DLHD", "HPush", "HPull"],
        "optional_families": ["All"],
        "slot_order": ["Sprint", "DLKD", "DLHD", "HPush", "HPull", "Core"],        "min_session_composition": [
            {"family": "DLKD", "mandatory": True, "count": 1, "notes": "Either DLKD or DLHD required per session"},
            {"family": "DLHD", "mandatory": True, "count": 1, "notes": "Either DLKD or DLHD required per session"},
            {"family": "HPush", "mandatory": True, "count": 1, "notes": "Push pattern — age-appropriate regression"},
            {"family": "HPull", "mandatory": True, "count": 1, "notes": "Pull pattern — age-appropriate regression"},
        ],
    },
    {
        "id": 8,
        "name": "Court Sport Athletic Development",
        "purpose": "Multi-directional power, deceleration, change of direction, and lateral strength.",
        "typical_athlete": "Tennis, badminton, basketball, volleyball, netball — all phases; cricket fielding specialists",
        "best_training_age": "1-5 years",
        "best_season_phase": ["off_season", "pre_season", "in_season", "transition"],        "contraindications": "Linear-only sport athletes (track, cycling, swimming), early rehab phase (use Return to Sport), athletes without established bilateral strength base",
        "typical_outcomes": "Improved COD speed, single-leg strength, rotational power, deceleration ability. Court-specific athletic qualities developed beyond what general strength programming provides.",
        "progression_path": "Strength + Power",
        "regression_path": "Full Body Strength",
        "mandatory_families": ["Sprint", "SLKD", "HPush", "Rot"],
        "optional_families": ["DLHD", "Ball", "Carry", "Core", "Acc"],
        "slot_order": ["Sprint", "Plyo", "SLKD", "Rot", "HPull", "Core"],        "min_session_composition": [
            {"family": "Sprint", "mandatory": True, "count": 1, "notes": "COD primer"},
            {"family": "SLKD", "mandatory": True, "count": 1, "notes": "Single-leg knee dominant"},
            {"family": "HPush", "mandatory": True, "count": 1, "notes": "Horizontal push"},
            {"family": "Rot", "mandatory": True, "count": 1, "notes": "Rotational power"},
        ],
    },
    {
        "id": 9,
        "name": "Rugby Off-Season",
        "purpose": "Build collision-ready strength, power, and mass. Contact preparation with conditioning.",
        "typical_athlete": "Rugby union/league, American football, any contact sport — off-season phase; forwards especially",
        "best_training_age": "2-5 years",
        "best_season_phase": ["off_season"],        "contraindications": "In-season (use Power Maintenance instead), non-contact sport, early off-season recovery phase (first 2-4 weeks off), athletes with training age <2 years, pre-season (too late for this volume)",
        "typical_outcomes": "Significant strength gains (squat, deadlift, press). Collision readiness. Mass accrual. Contact confidence. Most demanding blueprint in the catalog with best results from consistent 8-12 week blocks.",
        "progression_path": "Strength + Power",
        "regression_path": "Full Body Strength",
        "mandatory_families": ["Ball", "DLKD", "HPush", "HPull", "Carry"],
        "optional_families": ["Sprint", "Core", "Rot", "Acc"],
        "slot_order": ["Sprint", "Ball", "DLKD", "HPull", "HPush", "Carry", "Acc"],        "min_session_composition": [
            {"family": "Ball", "mandatory": True, "count": 1, "notes": "Power primer"},
            {"family": "DLKD", "mandatory": True, "count": 1, "notes": "Heavy compound squat"},
            {"family": "HPush", "mandatory": True, "count": 1, "notes": "Horizontal push"},
            {"family": "HPull", "mandatory": True, "count": 1, "notes": "Horizontal pull"},
            {"family": "Carry", "mandatory": True, "count": 1, "notes": "Strongman-style carry"},
        ],
    },
    {
        "id": 10,
        "name": "Sprint Development",
        "purpose": "Max velocity and/or acceleration improvement. Strength underpins but speed is priority.",
        "typical_athlete": "Track sprinters (100-400m), field sport speed block, returning from speed loss, acceleration-deficient athletes",
        "best_training_age": "2-5 years",
        "best_season_phase": ["pre_season", "off_season", "in_season"],        "contraindications": "Injury return (Achilles, hamstring, groin — use Return to Sport first), technique-deficient (clean up mechanics at lower intensity first), pre-meet taper week, athletes needing strength foundation first (<1.5x BW squat)",
        "typical_outcomes": "Improved acceleration (0-20m), max velocity (20-60m), sprint mechanics. Strength maintenance. Reactive strength improvement.",
        "progression_path": "Power + Speed",
        "regression_path": "Full Body Strength",
        "mandatory_families": ["Sprint", "DLHD", "Plyo"],
        "optional_families": ["DLKD", "HPull", "Core", "Acc"],
        "slot_order": ["Sprint", "Plyo", "DLHD", "DLKD", "Core", "Acc"],        "min_session_composition": [
            {"family": "Sprint", "mandatory": True, "count": 2, "notes": "2-3 sprint variations (accel/maxV)"},
            {"family": "DLHD", "mandatory": True, "count": 1, "notes": "Hip-dominant strength"},
            {"family": "Plyo", "mandatory": True, "count": 1, "notes": "Reactive strength"},
        ],
    },
    {
        "id": 11,
        "name": "Hypertrophy / Mass Accrual",
        "purpose": "Maximise muscle cross-sectional area. Higher volume, moderate loads, shorter rest.",
        "typical_athlete": "Bodybuilding phase, underweight athlete, post-rehab mass return, off-season mass block, young athletes needing weight gain",
        "best_training_age": "1-5 years",
        "best_season_phase": ["off_season"],        "contraindications": "In-season (unless severely underweight), pre-competition (<6 weeks out), speed/power peaking phases, athletes needing CNS freshness for competition, very long season with high practice volume",
        "typical_outcomes": "Significant muscle mass gain. Improved work capacity and metabolic conditioning. Strength gains secondary to hypertrophy.",
        "progression_path": "Strength + Power",
        "regression_path": "Full Body Strength",
        "mandatory_families": ["DLKD", "DLHD", "HPush", "HPull"],
        "optional_families": ["All"],
        "slot_order": ["DLKD", "DLHD", "HPush", "HPull", "Core"],        "min_session_composition": [
            {"family": "DLKD", "mandatory": True, "count": 1, "notes": "Compound squat (lower rep)"},
            {"family": "DLHD", "mandatory": True, "count": 1, "notes": "Compound hinge (lower rep)"},
            {"family": "HPush", "mandatory": True, "count": 1, "notes": "Horizontal press (higher rep)"},
            {"family": "HPull", "mandatory": True, "count": 1, "notes": "Horizontal pull (higher rep)"},
        ],
    },
    {
        "id": 12,
        "name": "Return to Sport (Foundation)",
        "purpose": "Rebuild movement capacity post-injury. Low intensity, high control, no pain.",
        "typical_athlete": "Post-rehab (cleared by medical/PT), ACL return, hamstring return, shoulder return, general injury return to training",
        "best_training_age": "Any (training age is injury-modified — current capacity determines starting point, not history)",
        "best_season_phase": ["transition"],        "contraindications": "Unreleased by medical team, active pain during exercise, acute injury phase (<6 weeks post-injury for most soft tissue), psychological unreadiness (fear of re-injury, hesitation), unresolved movement compensations",
        "typical_outcomes": "Safe return to sport-specific loading. Movement confidence restored. Pain-free strength development. Injury-specific reconditioning. Foundation for return to full training in 4-8 weeks.",
        "progression_path": "Full Body Strength",
        "regression_path": None,
        "mandatory_families": ["Acc", "DLKD", "DLHD", "Core"],
        "optional_families": ["SLKD", "Sprint", "Rot", "Carry"],
        "slot_order": ["Acc", "DLKD", "DLHD", "SLKD", "Core", "Sprint"],        "min_session_composition": [
            {"family": "Acc", "mandatory": True, "count": 1, "notes": "Activation / prehab"},
            {"family": "DLKD", "mandatory": True, "count": 1, "notes": "Regressed squat variation (either DLKD or DLHD)"},
            {"family": "DLHD", "mandatory": True, "count": 1, "notes": "Regressed hinge variation (either DLKD or DLHD)"},
            {"family": "Core", "mandatory": True, "count": 1, "notes": "Core stability"},
        ],
    },
    {
        "id": 13,
        "name": "Deload / Active Recovery",
        "purpose": "Systemic recovery, movement practice, connective tissue health. Intent is not stimulus — it's maintenance.",
        "typical_athlete": "Any athlete at end of training block, post-competition, high fatigue state, returning from illness, between mesocycles",
        "best_training_age": "Any — all athletes need deload periods regardless of training age",
        "best_season_phase": ["transition"],        "contraindications": "Athlete needing stimulus (deloading beyond 14 days causes detraining), pre-competition taper week (use specific taper protocol instead), athlete who hasn't completed a full training block, early off-season (first 2 weeks of off-season ARE the deload)",
        "typical_outcomes": "Reduced systemic fatigue. Movement quality maintained. Connective tissue health improved. Psychological freshness restored. Strength losses minimal (<5% over 7 days).",
        "progression_path": None,
        "regression_path": None,
        "mandatory_families": [],
        "optional_families": ["Acc", "Core", "Carry"],
        "slot_order": ["Acc", "DLKD", "DLHD", "Core", "Acc"],        "min_session_composition": [],
    },
    {
        "id": 14,
        "name": "Mixed Modal (GPP)",
        "purpose": "Broad athletic capacity across all domains. Nothing maximised, everything developed. Strength, power, speed, conditioning all touched weekly.",
        "typical_athlete": "Off-season multi-sport, beginner athlete, military/tactical, general fitness, pre-specialisation athlete",
        "best_training_age": "0-3 years",
        "best_season_phase": ["off_season", "pre_season"],        "contraindications": "Sport-specialised athlete in-season (needs focused blueprint), advanced athlete needing peaking (needs specificity), any block requiring sport-specific emphasis, late pre-season (<6 weeks to competition), post-rehab athlete (needs controlled loading, not rotation)",
        "typical_outcomes": "Broad athletic foundation. Improved capacity across all 15 movement families. General work capacity and fitness. Identification of strength and weakness areas. Best as a 4-8 week foundation block before specialisation.",
        "progression_path": "Full Body Strength",
        "regression_path": "Youth Foundation (U14-U20)",
        "mandatory_families": [],
        "optional_families": ["All"],
        "slot_order": ["Sprint", "Plyo", "DLKD", "DLHD", "HPush", "HPull", "Carry", "Core", "Acc"],        "min_session_composition": [],
    },
]
