"""
Role profiles for various sports, converted from TypeScript roleProfiles.ts.

Each profile contains sport-specific demands, movements, exercise categories,
tests with benchmarks, forge biases, and injury risk factors.
"""

from __future__ import annotations

ROLE_PROFILES = [
    {
        "sport": "Cricket",
        "role": "Pace Bowler",
        "sport_specific_exercises": ["Cricket"],
        "primary_demands": [
            "Repeat high-intensity bowling (8–10 overs per spell)",
            "Eccentric load absorption on landing leg",
            "Trunk stiffness & anti-rotation under torsion",
            "Deceleration & braking from delivery stride",
            "Lumbar-pelvic stability through front-foot contact",
        ],
        "priority_movements": [
            "Nordic hamstring / eccentric knee flexor",
            "Drop lunge / single-leg landing control",
            "Anti-rotation core (Paloff press, chops, half-kneeling)",
            "Single-leg hip extension (glute dominance)",
            "Rotational med ball slams (front foot strike pattern)",
        ],
        "priority_exercise_categories": [
            "Eccentric hamstring",
            "Anti-rotation core",
            "Single-leg landing control",
            "Hip extension bias",
            "Rotational power",
        "Injury Prevention",
        ],
        "tests": [
            {"name": "YoYo IR1", "benchmarks": {"elite": "> 20.1", "developmental": "16.1–20.0"}, "description": "Aerobic capacity for repeated high-intensity efforts"},
            {"name": "YoYo IR2", "benchmarks": {"elite": "> 13.5", "developmental": "10.1–13.4"}, "description": "Higher-intensity aerobic power & repeat sprint ability"},
            {"name": "Bronco", "benchmarks": {"elite": "< 5:00", "developmental": "5:00–5:30"}, "description": "Sport-specific shuttle run for multi-directional endurance"},
            {"name": "CMJ (relative peak power)", "benchmarks": {"elite": "> 55 W/kg", "developmental": "45–55 W/kg"}, "description": "Lower body power & reactive strength"},
            {"name": "10m Sprint", "benchmarks": {"elite": "< 1.70s", "developmental": "1.70–1.85s"}, "description": "Acceleration from standing start"},
            {"name": "Isometric Hamstring (N/kg)", "benchmarks": {"elite": "> 4.5 N/kg", "developmental": "3.5–4.5 N/kg"}, "description": "Hamstring eccentric strength & injury resilience"},
        ],
        "forge_biases": [
            "Prefer eccentric hamstring emphasis over pure posterior chain",
            "Favour anti-rotation core over flexion/extension bias",
            "Prioritise landing mechanics over take-off power",
            "Reduce axial spine loading in-season",
        ],
        "injury_risk_factors": [
            "Lumbar spine (stress fracture risk from hyperextension)",
            "Hamstring (eccentric overload during delivery stride)",
            "Side-of-release rib stress (fast bowling side)",
            "Anterior hip / groin (front hip impingement)",
            "Knee (patellar tendinopathy from landing forces)",
        ],
    },
    {
        "sport": "Cricket",
        "role": "Spinner",
        "sport_specific_exercises": ["Cricket"],
        "primary_demands": [
            "Shoulder rotation endurance (overs across spells)",
            "Trunk dissociation (thoracic vs lumbar rotation)",
            "Lower body stability through delivery stride",
            "Aerobic capacity for long bowling spells",
            "Landing consistency on non-dominant leg",
        ],
        "priority_movements": [
            "Thoracic rotation (half-kneeling band rotations)",
            "Glute med / lateral hip stability",
            "Single-leg balance & landing control",
            "Anti-rotation core (slow tempo holds)",
            "Hip internal/external rotation control",
        ],
        "priority_exercise_categories": [
            "Thoracic spine mobility",
            "Lateral hip stability",
            "Rotational core control",
            "Single-leg balance",
            "Shoulder external rotation endurance",
        "Injury Prevention",
        ],
        "tests": [
            {"name": "YoYo IR1", "benchmarks": {"elite": "> 19.0", "developmental": "15.0–19.0"}, "description": "Aerobic capacity for sustained bowling spells"},
            {"name": "YoYo IR2", "benchmarks": {"elite": "> 12.0", "developmental": "9.0–12.0"}, "description": "Repeat effort tolerance"},
            {"name": "Bronco", "benchmarks": {"elite": "< 5:30", "developmental": "5:30–6:00"}, "description": "General multi-directional endurance"},
            {"name": "CMJ (relative)", "benchmarks": {"elite": "> 48 W/kg", "developmental": "40–48 W/kg"}, "description": "Lower body power"},
            {"name": "Single-Leg Balance (eyes closed)", "benchmarks": {"elite": "> 30s", "developmental": "20–30s"}, "description": "Somatosensory control & landing stability"},
        ],
        "forge_biases": [
            "Emphasise thoracic mobility over lumbar range",
            "Favour slower tempo core control over ballistic",
            "Prioritise shoulder external rotation endurance",
            "Include lateral hip work to support delivery stride",
        ],
        "injury_risk_factors": [
            "Shoulder (rotator cuff — supraspinatus, infraspinatus)",
            "Lumbar facet (repeated rotation under load)",
            "Groin / adductor (drive leg push-off)",
            "Knee (meniscus from repetitive twisting)",
            "Non-dominant ankle (plant & twist mechanism)",
        ],
    },
    {
        "sport": "Cricket",
        "role": "Batter",
        "sport_specific_exercises": ["Cricket"],
        "primary_demands": [
            "Reactive strength & rapid force production",
            "Rotational power (hip-shoulder separation)",
            "Hand-eye coordination & reaction time",
            "Postural endurance (extended innings)",
            "Deceleration / stop-start agility between wickets",
        ],
        "priority_movements": [
            "Rotational med ball throws (bi-lateral)",
            "Counter-movement jump / standing broad jump",
            "Hip thrust / glute bridge (power transfer)",
            "Lateral shuffle & split-step mechanics",
            "Anti-rotation core (standing cable chop)",
        ],
        "priority_exercise_categories": [
            "Rotational power (med ball)",
            "Hip extension / glute dominance",
            "Lateral agility",
            "Reactive strength (jumps)",
            "Core anti-rotation",
        "Injury Prevention",
        ],
        "tests": [
            {"name": "YoYo IR1", "benchmarks": {"elite": "> 18.5", "developmental": "14.0–18.5"}, "description": "Aerobic capacity for multi-day innings"},
            {"name": "Bronco", "benchmarks": {"elite": "< 5:15", "developmental": "5:15–5:45"}, "description": "Fielding & running between wickets endurance"},
            {"name": "CMJ (relative)", "benchmarks": {"elite": "> 50 W/kg", "developmental": "42–50 W/kg"}, "description": "Lower body explosive power"},
            {"name": "Standing Broad Jump", "benchmarks": {"elite": "> 2.6m", "developmental": "2.3–2.6m"}, "description": "Horizontal power generation"},
            {"name": "Rotational Med Ball Throw (3kg)", "benchmarks": {"elite": "> 8m", "developmental": "6–8m"}, "description": "Rotational power for striking"},
            {"name": "5-0-5 COD", "benchmarks": {"elite": "< 2.35s", "developmental": "2.35–2.65s"}, "description": "Change of direction for quick singles"},
        ],
        "forge_biases": [
            "Prioritise rotational power generation over linear",
            "Add reactive jump training for rapid force production",
            "Include lateral COD work for running between wickets",
            "Prefer hip-dominant patterns over quad-dominant",
        ],
        "injury_risk_factors": [
            "Hamstring (sprinting between wickets)",
            "Lower back (rotational loading during drive/cut shots)",
            "Side strain (oblique — non-dominant side)",
            "Hand & wrist (ball impact — especially vs pace)",
            "Quad / groin (lunging front foot drives)",
        ],
    },
    {
        "sport": "Cricket",
        "role": "Wicketkeeper",
        "sport_specific_exercises": ["Cricket"],
        "primary_demands": [
            "Low body control & rapid weight shift",
            "Hip mobility & depth (squatting posture)",
            "Reactive agility (lateral & forward)",
            "Trunk flexion endurance (crouched hold)",
            "Shoulder endurance (throwing back to stumps / returns)",
        ],
        "priority_movements": [
            "Deep squat hold / goblet squat",
            "Lateral lunge / cossack squat",
            "Split-step shuffle / reactive agility",
            "Trunk forward lean endurance (farmer carry variation)",
            "Overhead shoulder stability (YTW raises)",
        ],
        "priority_exercise_categories": [
            "Deep squat / hip mobility",
            "Lateral agility",
            "Trunk flexor endurance",
            "Shoulder stability",
            "Rapid weight-shift drills",
        "Injury Prevention",
        ],
        "tests": [
            {"name": "YoYo IR1", "benchmarks": {"elite": "> 18.0", "developmental": "14.0–18.0"}, "description": "Aerobic endurance for long sessions in crouch"},
            {"name": "Bronco", "benchmarks": {"elite": "< 5:15", "developmental": "5:15–5:45"}, "description": "General fielding endurance"},
            {"name": "CMJ (relative)", "benchmarks": {"elite": "> 46 W/kg", "developmental": "38–46 W/kg"}, "description": "Lower body power for explosive movement"},
            {"name": "5-0-5 COD", "benchmarks": {"elite": "< 2.40s", "developmental": "2.40–2.70s"}, "description": "Lateral change of direction"},
            {"name": "Sit & Reach / Deep Squat Hold", "benchmarks": {"elite": "> 15cm / full depth", "developmental": "5–15cm / parallel"}, "description": "Hip & trunk mobility for crouch position"},
        ],
        "forge_biases": [
            "Favour hip mobility drills over pure strength",
            "Prioritise reactive agility over max speed",
            "Include trunk flexor endurance as a staple",
            "Add shoulder stability for return throws",
        ],
        "injury_risk_factors": [
            "Patellar / quadriceps tendinopathy (crouch to stand)",
            "Hip impingement (deep squatting posture)",
            "Lower back (flexed posture for extended periods)",
            "Throwing shoulder (rotator cuff — repetitive returns)",
            "Hamstring (rapid forward dives / saves)",
        ],
    },
    {
        "sport": "Cricket",
        "role": "All-Rounder",
        "sport_specific_exercises": ["Cricket"],
        "primary_demands": [
            "Balanced load between bowling & batting demands",
            "Repeat sprint ability & aerobic recovery",
            "Rotational power (striking + bowling torque)",
            "Eccentric control (landing leg + sprint deceleration)",
            "Total work capacity for multi-format load",
        ],
        "priority_movements": [
            "Nordic hamstring curl",
            "Rotational med ball (bi-lateral + single-arm)",
            "Drop lunge / landing control",
            "CMJ & broad jump (reactive strength)",
            "Anti-rotation core (Paloff, chops, half-kneeling)",
        ],
        "priority_exercise_categories": [
            "Eccentric hamstring",
            "Rotational power",
            "Landing control",
            "Reactive strength",
            "Aerobic capacity maintenance",
        "Injury Prevention",
        ],
        "tests": [
            {"name": "YoYo IR1", "benchmarks": {"elite": "> 19.0", "developmental": "15.0–19.0"}, "description": "Aerobic capacity for dual batting & bowling demands"},
            {"name": "YoYo IR2", "benchmarks": {"elite": "> 12.5", "developmental": "9.5–12.5"}, "description": "High-intensity repeat effort tolerance"},
            {"name": "Bronco", "benchmarks": {"elite": "< 5:15", "developmental": "5:15–5:45"}, "description": "Multi-directional endurance"},
            {"name": "CMJ (relative peak power)", "benchmarks": {"elite": "> 52 W/kg", "developmental": "44–52 W/kg"}, "description": "Lower body explosive power"},
            {"name": "Rotational Med Ball Throw (3kg)", "benchmarks": {"elite": "> 9m", "developmental": "6.5–9m"}, "description": "Rotational power output"},
            {"name": "10m Sprint", "benchmarks": {"elite": "< 1.75s", "developmental": "1.75–1.90s"}, "description": "Acceleration for quick runs / closing the field"},
        ],
        "forge_biases": [
            "Balance eccentric hamstring & rotational power across cycles",
            "Monitor total workload between discipline-specific training",
            "Include aerobic capacity work (compromise between batting & bowling)",
            "Use reactive strength index (RSI) as primary readiness marker",
        ],
        "injury_risk_factors": [
            "Hamstring (dual sprint + bowling demands)",
            "Lower back (rotational + flexion loading from both disciplines)",
            "Groin / adductor (driving leg + sprint mechanics)",
            "Shoulder (bowling + throwing + rotational striking)",
            "Knee (landing + deceleration from both activities)",
        ],
    },
    {
        "sport": "Badminton",
        "role": "Singles Player",
        "sport_specific_exercises": ["Badminton"],
        "primary_demands": [
            "High aerobic capacity for long rallies (70–90% aerobic energy)",
            "Repeated deep lunges & accelerations covering full court",
            "Multidirectional agility & footwork (shuffles, split-steps)",
            "Overhead power & accuracy (smashes, clears, drops)",
            "Single-leg strength & endurance for lunging recovery",
            "Superior recovery between points (aerobic conditioning)",
        ],
        "priority_movements": [
            "Deep forward lunge (front court reach)",
            "Lateral lunge (side-to-side coverage)",
            "Single-leg balance & landing control (after jumps)",
            "Rapid change-of-direction shuffles",
            "Explosive jumps (smash & intercept)",
        ],
        "priority_exercise_categories": [
            "Single-leg lunge variations (forward, lateral, reverse)",
            "Change-of-direction drills (ladders, cone shuttles)",
            "Plyometrics (drop jumps, bounding for jump smash control)",
            "Overhead stability (YTWL, rotator cuff)",
            "Anti-rotation core (chops, Pallof presses)",
            "Aerobic conditioning (interval runs, shadow play)",
        "Injury Prevention",
        ],
        "tests": [
            {"name": "YoYo IR1", "benchmarks": {"elite": "> 2000m", "academy": "1400-1800m"}, "description": "High-intensity aerobic capacity for long rallies"},
            {"name": "Bronco", "benchmarks": {"elite": "< 5:30", "academy": "5:30-6:00"}, "description": "Multi-directional endurance for court coverage"},
            {"name": "CMJ", "benchmarks": {"elite": "> 50cm", "academy": "40-50cm"}, "description": "Lower body explosive power for jumps & lunges"},
            {"name": "5-0-5 COD", "benchmarks": {"elite": "< 2.30s", "academy": "2.30-2.70s"}, "description": "Change of direction speed"},
            {"name": "Overhead MB Throw (3kg)", "benchmarks": {"elite": "> 10m", "academy": "6-8m"}, "description": "Rotational & overhead power"},
            {"name": "Single-Leg Balance (eyes closed)", "benchmarks": {"elite": "> 30s", "academy": "20-25s"}, "description": "Somatosensory control & landing stability"},
        ],
        "forge_biases": [
            "Prioritize aerobic conditioning (2x/week interval shuttles)",
            "Emphasize unilateral lower body strength for lunging",
            "Include overhead stability every session",
            "Favor eccentric hamstring work for lunging safety",
            "Avoid heavy eccentric knee work 48h before competition",
        ],
        "injury_risk_factors": [
            "Knee (patellar tendinopathy from lunging)",
            "Ankle (sprains from sudden direction changes)",
            "Shoulder (rotator cuff, impingement from overheads)",
            "Lower back (lumbar strains from twisting)",
            "Hamstring (sprinting to net in late matches)",
            "Elbow (tendinopathies from racket swing)",
        ],
    },
    {
        "sport": "Badminton",
        "role": "Doubles Player",
        "sport_specific_exercises": ["Badminton"],
        "primary_demands": [
            "Explosive power for smashes & quick reactions at net",
            "Short-burst speed (acceleration & deceleration)",
            "Reactive agility (split-step, drop-step responses)",
            "Shoulder power endurance (repeated overheads)",
            "Core stability (anti-rotation for balance)",
            "ATP-PC anaerobic system predominates (85–90% of efforts)",
        ],
        "priority_movements": [
            "Split-step & drop-step (reactive start)",
            "Rapid forward lunges (net play)",
            "Explosive overhead smash motion (jump smashes)",
            "Controlled single-leg landings (after jumps)",
            "Quick lateral movements & pivots",
        ],
        "priority_exercise_categories": [
            "Plyometric drills (drop jumps, hurdle jumps with landing control)",
            "Overhead power (med ball throws, slams)",
            "Sprint repeats (10–20m bursts with short rest)",
            "Reactive agility (partner-feeding, cue-based drills)",
            "Anti-rotation core (Paloff, chops)",
            "Shoulder endurance (high-rep med ball or band work)",
        "Injury Prevention",
        ],
        "tests": [
            {"name": "YoYo IR2", "benchmarks": {"elite": "> 1600m", "academy": "1000-1400m"}, "description": "High-intensity repeat endurance for short rallies"},
            {"name": "Bronco", "benchmarks": {"elite": "< 5:15", "academy": "5:15-5:45"}, "description": "Multi-directional endurance"},
            {"name": "CMJ", "benchmarks": {"elite": "> 50cm", "academy": "40-48cm"}, "description": "Lower body explosive power for smashes & jumps"},
            {"name": "10m Sprint", "benchmarks": {"elite": "< 1.60s", "academy": "1.60-1.80s"}, "description": "Acceleration for rapid court coverage"},
            {"name": "Overhead MB Throw (3kg)", "benchmarks": {"elite": "> 10m", "academy": "7-9m"}, "description": "Rotational & overhead power for smashes"},
            {"name": "Reactive Agility (pro-agility)", "benchmarks": {"elite": "< 4.5s", "academy": "4.5-5.0s"}, "description": "Reactive response & change of direction"},
        ],
        "forge_biases": [
            "Bias toward power & speed (plyometrics, Olympic-style lifts)",
            "Prioritize shoulder endurance for repeated smashes",
            "Include reactive agility drills (unpredictable cues)",
            "Frequent sprint & jump sets with rotation to avoid overload",
            "Core anti-rotation stability for overhead force transfer",
            "Avoid heavy eccentric work before match days",
        ],
        "injury_risk_factors": [
            "Shoulder (rotator cuff strains/impingement from smashes)",
            "Knee (jumper's knee, ACL stress from landing)",
            "Ankle (sprains from sharp pivots)",
            "Elbow (epicondylitis from racket swings)",
            "Wrist (sprains or tendinitis from net play)",
            "Lower back (lumbar strains from twisting motions)",
        ],
    },
    {
        "sport": "Badminton",
        "role": "Mixed Doubles Player",
        "sport_specific_exercises": ["Badminton"],
        "primary_demands": [
            "Explosive power for smashes & net reactions",
            "Short-burst speed & acceleration",
            "Reactive agility (split-step, responses)",
            "Shoulder power endurance (repeated overheads)",
            "Aerobic endurance (covers larger court area than standard doubles)",
            "Tactical rotation & partner communication",
        ],
        "priority_movements": [
            "Split-step & drop-step",
            "Rapid forward lunges & lateral movements",
            "Explosive overhead smash motion",
            "Controlled single-leg landings",
            "Multi-directional agility (covers more court)",
        ],
        "priority_exercise_categories": [
            "Plyometric drills with landing control",
            "Overhead power (med ball throws, slams)",
            "Sprint repeats (10–20m bursts)",
            "Reactive agility drills",
            "Anti-rotation core",
            "Aerobic conditioning (interval runs)",
        "Injury Prevention",
        ],
        "tests": [
            {"name": "YoYo IR1", "benchmarks": {"elite": "> 1800m", "academy": "1400-1700m"}, "description": "Aerobic capacity for extended court coverage"},
            {"name": "Bronco", "benchmarks": {"elite": "< 5:20", "academy": "5:20-5:50"}, "description": "Multi-directional endurance"},
            {"name": "CMJ", "benchmarks": {"elite": "> 48cm", "academy": "38-48cm"}, "description": "Lower body explosive power"},
            {"name": "10m Sprint", "benchmarks": {"elite": "< 1.65s", "academy": "1.65-1.85s"}, "description": "Acceleration for rapid court coverage"},
            {"name": "Overhead MB Throw (3kg)", "benchmarks": {"elite": "> 9m", "academy": "6-8m"}, "description": "Rotational & overhead power"},
        ],
        "forge_biases": [
            "Bias toward power & speed with added aerobic conditioning",
            "Include reactive agility drills",
            "Prioritize shoulder endurance for repeated smashes",
            "Balance power and endurance sessions",
        ],
        "injury_risk_factors": [
            "Shoulder (rotator cuff strains)",
            "Knee (jumper's knee)",
            "Ankle (sprains)",
            "Elbow (epicondylitis)",
            "Wrist (sprains or tendinitis)",
            "Lower back (lumbar strains)",
        ],
    },
    {
        "sport": "Tennis",
        "role": "Singles Player",
        "sport_specific_exercises": ["Tennis"],
        "primary_demands": [
            "High aerobic capacity for long matches (2–4+ hours)",
            "Repeated sprinting & lateral movement covering full court",
            "Rotational power for serves & groundstrokes (forehand/backhand)",
            "Single-leg stability & eccentric control during lunges",
            "Shoulder endurance for repeated serves & overheads",
            "Quick change of direction & split-step reaction",
        ],
        "priority_movements": [
            "Split-step & lateral shuffle (side-to-side coverage)",
            "Deep forward lunge (reaching wide shots)",
            "Open-stance forehand/backhand rotation (hip-shoulder separation)",
            "Serve motion (kinetic chain from legs to arm)",
            "Single-leg landing control (after jump serves)",
        ],
        "priority_exercise_categories": [
            "Rotational core (cable rotations, med ball throws)",
            "Single-leg lunge variations (forward, lateral)",
            "Agility drills (cone shuffles, ladder drills)",
            "Overhead stability (YTWL, rotator cuff)",
            "Aerobic conditioning (interval runs, court-based shuttles)",
            "Shoulder endurance (high-rep band work)",
            "Split-Step",
            "Lateral Lunge",
            "Diagonal Shuttle",
            "Rotational Cable",
            "Single-Leg Balance",
            "Overhead Band",
            "Carioca",
        "Injury Prevention",
        ],
        "tests": [
            {"name": "YoYo IR1", "benchmarks": {"elite": "> 2200m", "academy": "1600-2000m"}, "description": "High-intensity aerobic capacity for long matches"},
            {"name": "Bronco", "benchmarks": {"elite": "< 5:15", "academy": "5:15-5:45"}, "description": "Multi-directional endurance for court coverage"},
            {"name": "CMJ", "benchmarks": {"elite": "> 50cm", "academy": "40-48cm"}, "description": "Lower body explosive power for serves & sprints"},
            {"name": "5-0-5 COD", "benchmarks": {"elite": "< 2.40s", "academy": "2.40-2.80s"}, "description": "Change of direction speed"},
            {"name": "Rotational Med Ball Throw (3kg)", "benchmarks": {"elite": "> 10m", "academy": "7-9m"}, "description": "Rotational power for groundstrokes & serves"},
            {"name": "Single-Leg Balance (eyes closed)", "benchmarks": {"elite": "> 30s", "academy": "20-25s"}, "description": "Proprioception & landing stability"},
        ],
        "forge_biases": [
            "Prioritize aerobic conditioning (2–3x/week intervals)",
            "Emphasize unilateral lower body strength & eccentric control",
            "Include rotational core work every session",
            "Maintain shoulder health with external rotation & scapular stability",
            "Avoid heavy eccentric loading 48h before matches",
        ],
        "injury_risk_factors": [
            "Tennis elbow (lateral epicondylitis from groundstrokes)",
            "Shoulder (rotator cuff, impingement from serving)",
            "Knee (patellar tendinopathy, meniscus from lunges)",
            "Ankle (sprains from sudden direction changes)",
            "Lower back (lumbar strains from rotational loading)",
            "Hamstring (sprinting to drop shots)",
        ],
    },
    {
        "sport": "Tennis",
        "role": "Doubles Player",
        "sport_specific_exercises": ["Tennis"],
        "primary_demands": [
            "Explosive power for volleys & overhead smashes",
            "Short-burst speed & rapid reaction at net",
            "Shoulder endurance for repeated overheads & serves",
            "Core stability (anti-rotation for net play)",
            "Quick lateral movements & split-step responses",
            "Anaerobic power (shorter points, less running)",
        ],
        "priority_movements": [
            "Split-step & reactive lateral shuffle",
            "Rapid forward lunges (net play)",
            "Explosive overhead smash motion (jump & land)",
            "Quick pivots & direction changes",
            "Controlled single-leg landings (after smashes)",
        ],
        "priority_exercise_categories": [
            "Plyometric drills (drop jumps, hurdle jumps with landing control)",
            "Overhead power (med ball slams, throws)",
            "Sprint repeats (10–20m bursts)",
            "Reactive agility drills (partner cue-based)",
            "Anti-rotation core (Paloff, chops)",
            "Shoulder endurance (high-rep band or med ball)",
            "Split-Step",
            "Lateral Lunge",
            "Diagonal Shuttle",
            "Rotational Cable",
            "Single-Leg Balance",
            "Overhead Band",
            "Carioca",
        "Injury Prevention",
        ],
        "tests": [
            {"name": "YoYo IR2", "benchmarks": {"elite": "> 1500m", "academy": "1000-1400m"}, "description": "High-intensity repeat endurance for short rallies"},
            {"name": "Bronco", "benchmarks": {"elite": "< 5:10", "academy": "5:10-5:40"}, "description": "Multi-directional endurance"},
            {"name": "CMJ", "benchmarks": {"elite": "> 50cm", "academy": "40-48cm"}, "description": "Lower body explosive power for smashes & volleys"},
            {"name": "10m Sprint", "benchmarks": {"elite": "< 1.60s", "academy": "1.60-1.80s"}, "description": "Acceleration for quick net coverage"},
            {"name": "Overhead MB Throw (3kg)", "benchmarks": {"elite": "> 10m", "academy": "7-9m"}, "description": "Rotational & overhead power for smashes"},
            {"name": "Reactive Agility (pro-agility)", "benchmarks": {"elite": "< 4.4s", "academy": "4.4-4.9s"}, "description": "Reactive response & change of direction"},
        ],
        "forge_biases": [
            "Bias toward power & speed (plyometrics, explosive lifts)",
            "Prioritize shoulder endurance for repeated overheads",
            "Include reactive agility drills with unpredictable cues",
            "Emphasize anti-rotation core for stability at net",
            "Avoid heavy eccentric work before match days",
        ],
        "injury_risk_factors": [
            "Shoulder (rotator cuff strains/impingement from smashes & serves)",
            "Tennis elbow (lateral epicondylitis from volleys)",
            "Knee (jumper's knee from landing)",
            "Ankle (sprains from sharp pivots)",
            "Lower back (lumbar strains from rotational loading)",
            "Wrist (sprains from net play)",
        ],
    },
    {
        "sport": "Football",
        "role": "Goalkeeper",
        "sport_specific_exercises": ["Football"],
        "primary_demands": [
            "Explosive power for dives, jumps, and quick reactions",
            "Short-burst speed for coming off the line and sweeping",
            "Agility & reactive ability to save shots",
            "Upper body strength for holding crosses and handling",
            "Kicking power & accuracy for distribution",
            "Mental resilience & concentration",
        ],
        "priority_movements": [
            "Lateral dives (reactive save motion)",
            "Vertical jumps (high ball collection)",
            "Rapid forward sprints (sweeping)",
            "Single-leg landing control (after dives)",
            "Core stability (anti-rotation for handling)",
        ],
        "priority_exercise_categories": [
            "Plyometrics (drop jumps, hurdle jumps for explosive power)",
            "Reactive agility drills (partner cue-based)",
            "Upper body strength (bench press, rows for handling)",
            "Core stability (Paloff, anti-rotation)",
            "Sprint repeats (5-10m bursts)",
            "COD Drill",
            "Repeated Sprint",
            "Single-Leg Landing",
            "Lateral Shuffle",
            "Nordic",
            "Rotational Med Ball",
        "Injury Prevention",
        ],
        "tests": [
            {"name": "YoYo IR1", "benchmarks": {"elite": "> 1600m", "academy": "1200-1500m"}, "description": "Aerobic capacity (lower than outfield players)"},
            {"name": "CMJ", "benchmarks": {"elite": "> 45cm", "academy": "35-42cm"}, "description": "Lower body explosive power for jumps & dives"},
            {"name": "10m Sprint", "benchmarks": {"elite": "< 1.70s", "academy": "1.70-1.85s"}, "description": "Acceleration for sweeping"},
            {"name": "Reactive Agility (pro-agility)", "benchmarks": {"elite": "< 4.8s", "academy": "4.8-5.2s"}, "description": "Reactive change of direction for saves"},
            {"name": "Seated Med Ball Throw (3kg)", "benchmarks": {"elite": "> 6m", "academy": "4-6m"}, "description": "Upper body power for throws & punching"},
        ],
        "forge_biases": [
            "Prioritize explosive lower body power & agility",
            "Include upper body strength & power work",
            "Emphasize reactive drills & decision-making",
            "Maintain shoulder health & rotator cuff stability",
            "Avoid heavy eccentric lower body work before match days",
        ],
        "injury_risk_factors": [
            "Shoulder (rotator cuff, impingement from dives)",
            "Knee (patellar tendinopathy from landing)",
            "Ankle (sprains from awkward landings)",
            "Wrist (sprains from falls)",
            "Hip (adductor strains from split saves)",
        ],
    },
    {
        "sport": "Football",
        "role": "Centre-back",
        "sport_specific_exercises": ["Football"],
        "primary_demands": [
            "Aerial duels (jumping & heading)",
            "Short-burst speed & agility for covering space",
            "Physical strength for 1v1 duels (shoulder-to-shoulder)",
            "Eccentric strength for deceleration & change of direction",
            "Core stability & anti-rotation for tackling",
            "High concentration & decision-making",
        ],
        "priority_movements": [
            "Vertical jump (heading duels)",
            "Lateral shuffle & change of direction",
            "Backpedaling & re-acceleration",
            "Single-leg landing control (after jumps)",
            "Tackling mechanics (lunge & recover)",
        ],
        "priority_exercise_categories": [
            "Vertical jumps (drop jumps, depth jumps)",
            "Change-of-direction drills (COD)",
            "Single-leg strength (lunges, split squats)",
            "Eccentric hamstring work (Nordic curls)",
            "Core anti-rotation (Paloff, chops)",
            "Sprint repeats (10-20m bursts)",
            "COD Drill",
            "Repeated Sprint",
            "Single-Leg Landing",
            "Lateral Shuffle",
            "Nordic",
            "Rotational Med Ball",
        "Injury Prevention",
        ],
        "tests": [
            {"name": "YoYo IR1", "benchmarks": {"elite": "> 1800m", "academy": "1400-1700m"}, "description": "Aerobic capacity for sustained defensive coverage"},
            {"name": "CMJ", "benchmarks": {"elite": "> 48cm", "academy": "38-45cm"}, "description": "Lower body power for jumping & duels"},
            {"name": "10m Sprint", "benchmarks": {"elite": "< 1.75s", "academy": "1.75-1.90s"}, "description": "Acceleration for covering space"},
            {"name": "5-0-5 COD", "benchmarks": {"elite": "< 2.50s", "academy": "2.50-2.80s"}, "description": "Change of direction speed"},
            {"name": "Nordic Hamstring Curl (load)", "benchmarks": {"elite": "> 4.5 N/kg", "academy": "3.5-4.5 N/kg"}, "description": "Eccentric hamstring strength for injury prevention"},
        ],
        "forge_biases": [
            "Emphasize eccentric hamstring & single-leg strength",
            "Include vertical jumps & COD drills",
            "Prioritize core stability & anti-rotation",
            "Balance power & endurance in training",
            "Avoid high-volume jumping before match days",
        ],
        "injury_risk_factors": [
            "Hamstring (sprinting & deceleration)",
            "Groin (adductor strains from lateral movements)",
            "Knee (ACL stress from turning)",
            "Ankle (sprains from tackles)",
            "Lower back (lumbar strains from heading)",
        ],
    },
    {
        "sport": "Football",
        "role": "Full-back",
        "sport_specific_exercises": ["Football"],
        "primary_demands": [
            "High aerobic & anaerobic capacity for up-and-down the flank",
            "Repeated sprinting & deceleration for overlapping runs",
            "Agility & lateral movement for 1v1 defending",
            "Eccentric strength for change of direction & tackling",
            "Crossing accuracy & power",
            "Core stability for balance & tackling",
        ],
        "priority_movements": [
            "Linear & lateral sprinting (overlapping runs)",
            "Quick change of direction (COD)",
            "Single-leg landing control (after sprint stops)",
            "Tackling mechanics (lunge & recover)",
            "Crossing motion (hip & foot rotation)",
        ],
        "priority_exercise_categories": [
            "Sprint repeats (10-20m with deceleration)",
            "Change-of-direction drills (COD)",
            "Single-leg strength (lunges, split squats)",
            "Eccentric hamstring work (Nordic curls)",
            "Core stability & anti-rotation",
            "Aerobic conditioning (interval runs)",
            "COD Drill",
            "Repeated Sprint",
            "Single-Leg Landing",
            "Lateral Shuffle",
            "Nordic",
            "Rotational Med Ball",
        "Injury Prevention",
        ],
        "tests": [
            {"name": "YoYo IR1", "benchmarks": {"elite": "> 2000m", "academy": "1500-1800m"}, "description": "Aerobic capacity for repeated up-and-down runs"},
            {"name": "CMJ", "benchmarks": {"elite": "> 48cm", "academy": "38-45cm"}, "description": "Lower body power for sprints & jumps"},
            {"name": "10m Sprint", "benchmarks": {"elite": "< 1.70s", "academy": "1.70-1.85s"}, "description": "Acceleration for overlapping runs"},
            {"name": "5-0-5 COD", "benchmarks": {"elite": "< 2.40s", "academy": "2.40-2.70s"}, "description": "Change of direction speed"},
            {"name": "Bronco", "benchmarks": {"elite": "< 5:20", "academy": "5:20-5:50"}, "description": "Multi-directional endurance"},
        ],
        "forge_biases": [
            "Prioritize repeated sprint ability (RSA) & COD",
            "Include single-leg & eccentric hamstring work",
            "Balance aerobic & anaerobic conditioning",
            "Emphasize core stability for tackling",
            "Avoid high-volume sprinting 48h before matches",
        ],
        "injury_risk_factors": [
            "Hamstring (sprinting & deceleration)",
            "Groin (adductor strains from lateral movements)",
            "Ankle (sprains from tackles)",
            "Knee (meniscus from turning)",
            "Hip (flexor strains from kicking & sprinting)",
        ],
    },
    {
        "sport": "Football",
        "role": "Midfielder",
        "sport_specific_exercises": ["Football"],
        "primary_demands": [
            "Very high aerobic capacity (cover the most distance)",
            "Repeated high-intensity running & deceleration",
            "Agility & quick turns in congested areas",
            "Core stability & balance for shielding the ball",
            "Passing & shooting accuracy (foot-eye coordination)",
            "Eccentric strength for change of direction",
        ],
        "priority_movements": [
            "Multi-directional running (forward, backward, lateral)",
            "Quick turns & pivots (180° & 90° turns)",
            "Single-leg landing control (after sprints)",
            "Shooting & passing motion (kinetic chain)",
            "Core stability for balance under pressure",
        ],
        "priority_exercise_categories": [
            "Interval runs (HIIT mimicking match demands)",
            "Change-of-direction drills (COD)",
            "Single-leg strength (lunges, split squats)",
            "Eccentric hamstring work (Nordic curls)",
            "Core stability & anti-rotation",
            "Agility ladder & cone drills",
            "COD Drill",
            "Repeated Sprint",
            "Single-Leg Landing",
            "Lateral Shuffle",
            "Nordic",
            "Rotational Med Ball",
        "Injury Prevention",
        ],
        "tests": [
            {"name": "YoYo IR1", "benchmarks": {"elite": "> 2200m", "academy": "1600-2000m"}, "description": "High aerobic capacity for covering the most distance"},
            {"name": "Bronco", "benchmarks": {"elite": "< 5:00", "academy": "5:00-5:30"}, "description": "Multi-directional endurance"},
            {"name": "CMJ", "benchmarks": {"elite": "> 48cm", "academy": "38-45cm"}, "description": "Lower body power for sprints & jumps"},
            {"name": "5-0-5 COD", "benchmarks": {"elite": "< 2.40s", "academy": "2.40-2.70s"}, "description": "Change of direction speed"},
            {"name": "10m Sprint", "benchmarks": {"elite": "< 1.70s", "academy": "1.70-1.85s"}, "description": "Acceleration for covering space"},
        ],
        "forge_biases": [
            "Prioritize aerobic capacity & repeat sprint ability",
            "Include COD drills & agility work",
            "Emphasize core stability & balance",
            "Balance power & endurance in training",
            "Avoid high-volume intensity 48h before matches",
        ],
        "injury_risk_factors": [
            "Hamstring (sprinting & deceleration)",
            "Groin (adductor strains from lateral movements)",
            "Ankle (sprains from tackles)",
            "Knee (patellar tendinopathy from running)",
            "Lower back (lumbar strains from rotational movements)",
        ],
    },
    {
        "sport": "Football",
        "role": "Winger",
        "sport_specific_exercises": ["Football"],
        "primary_demands": [
            "Explosive acceleration & top speed for beating defenders",
            "Repeated sprinting (up & down the flank)",
            "Agility & change of direction for dribbling",
            "Single-leg strength & balance for crossing & shooting",
            "Core stability for balance under pressure",
            "Anaerobic power for short, intense efforts",
        ],
        "priority_movements": [
            "Linear sprinting (acceleration & max velocity)",
            "Lateral & diagonal running (dribbling)",
            "Quick changes of direction & 180° turns",
            "Single-leg landing control (after sprints)",
            "Crossing & shooting motion (kinetic chain)",
        ],
        "priority_exercise_categories": [
            "Sprint training (acceleration & max velocity)",
            "Change-of-direction drills (COD)",
            "Single-leg strength (lunges, split squats)",
            "Plyometrics (drop jumps, bounding)",
            "Core stability & anti-rotation",
            "Agility drills (ladders, cones)",
            "COD Drill",
            "Repeated Sprint",
            "Single-Leg Landing",
            "Lateral Shuffle",
            "Nordic",
            "Rotational Med Ball",
        "Injury Prevention",
        ],
        "tests": [
            {"name": "YoYo IR1", "benchmarks": {"elite": "> 1800m", "academy": "1400-1700m"}, "description": "Aerobic capacity for repeated sprints"},
            {"name": "10m Sprint", "benchmarks": {"elite": "< 1.60s", "academy": "1.60-1.75s"}, "description": "Acceleration for beating defenders"},
            {"name": "30m Sprint", "benchmarks": {"elite": "< 3.80s", "academy": "3.80-4.10s"}, "description": "Max velocity for flank runs"},
            {"name": "CMJ", "benchmarks": {"elite": "> 48cm", "academy": "38-45cm"}, "description": "Lower body power for explosive movements"},
            {"name": "5-0-5 COD", "benchmarks": {"elite": "< 2.30s", "academy": "2.30-2.60s"}, "description": "Change of direction for dribbling"},
        ],
        "forge_biases": [
            "Prioritize acceleration & max velocity training",
            "Include COD drills & agility work",
            "Emphasize single-leg strength & balance",
            "Balance explosive & aerobic sessions",
            "Avoid high-intensity sprinting 48h before matches",
        ],
        "injury_risk_factors": [
            "Hamstring (sprinting & deceleration)",
            "Groin (adductor strains from lateral movements)",
            "Ankle (sprains from tackles)",
            "Knee (patellar tendinopathy from running)",
            "Hip (flexor strains from kicking & sprinting)",
        ],
    },
    {
        "sport": "Football",
        "role": "Striker",
        "sport_specific_exercises": ["Football"],
        "primary_demands": [
            "Explosive acceleration for beating defenders",
            "Agility & change of direction for dribbling & turns",
            "Single-leg strength & balance for shooting",
            "Jumping & heading (aerial duels)",
            "Core stability for balance under pressure",
            "Anaerobic power for short, intense efforts",
        ],
        "priority_movements": [
            "Linear sprinting (acceleration & max velocity)",
            "Quick turns & pivots (180° turns)",
            "Single-leg landing control (after jumps)",
            "Shooting motion (kinetic chain)",
            "Vertical jumps (heading)",
        ],
        "priority_exercise_categories": [
            "Sprint training (acceleration & max velocity)",
            "Change-of-direction drills (COD)",
            "Single-leg strength (lunges, split squats)",
            "Plyometrics (drop jumps, bounding for heading)",
            "Core stability & anti-rotation",
            "Shooting & power drills (med ball throws)",
            "COD Drill",
            "Repeated Sprint",
            "Single-Leg Landing",
            "Lateral Shuffle",
            "Nordic",
            "Rotational Med Ball",
        "Injury Prevention",
        ],
        "tests": [
            {"name": "YoYo IR1", "benchmarks": {"elite": "> 1800m", "academy": "1400-1700m"}, "description": "Aerobic capacity for repeated sprints & pressure"},
            {"name": "10m Sprint", "benchmarks": {"elite": "< 1.65s", "academy": "1.65-1.80s"}, "description": "Acceleration for beating defenders"},
            {"name": "CMJ", "benchmarks": {"elite": "> 50cm", "academy": "40-48cm"}, "description": "Lower body power for jumps & sprints"},
            {"name": "5-0-5 COD", "benchmarks": {"elite": "< 2.40s", "academy": "2.40-2.70s"}, "description": "Change of direction for dribbling & turns"},
            {"name": "Overhead MB Throw (3kg)", "benchmarks": {"elite": "> 9m", "academy": "6-8m"}, "description": "Shooting & heading power"},
        ],
        "forge_biases": [
            "Prioritize acceleration & explosive power",
            "Include COD drills & agility work",
            "Emphasize single-leg strength & balance",
            "Include vertical jumps & power exercises",
            "Avoid high-intensity sprinting 48h before matches",
        ],
        "injury_risk_factors": [
            "Hamstring (sprinting & deceleration)",
            "Groin (adductor strains from lateral movements)",
            "Ankle (sprains from tackles)",
            "Knee (patellar tendinopathy from running)",
            "Hip (flexor strains from shooting & sprinting)",
        ],
    },
    {
        "sport": "Rugby Union",
        "role": "Prop",
        "sport_specific_exercises": ["Rugby Union"],
        "primary_demands": [
            "High maximal strength for scrummaging & mauls",
            "Power for explosive engagements & tackling",
            "Eccentric strength for deceleration & collisions",
            "Neck & trunk stability for scrummaging",
            "Anaerobic power for repeated high-intensity efforts",
            "Body mass & composition management",
        ],
        "priority_movements": [
            "Scrum engagement (isometric & explosive drive)",
            "Tackling & rucking (low body position & drive)",
            "Lifting in lineouts (explosive extension)",
            "Carrying (short-distance power)",
            "Single-leg stability for pushing",
        ],
        "priority_exercise_categories": [
            "Maximal strength (squat, deadlift, bench press)",
            "Isometric holds (scrum-specific)",
            "Neck strengthening (isometric & dynamic)",
            "Plyometrics (jump squats, med ball slams)",
            "Core stability (anti-rotation, bracing)",
            "Eccentric hamstring (Nordic curls)",
        "Injury Prevention",
        ],
        "tests": [
            {"name": "YoYo IR1", "benchmarks": {"elite": "> 1600m", "academy": "1200-1500m"}, "description": "Aerobic capacity for repeated efforts"},
            {"name": "CMJ", "benchmarks": {"elite": "> 40cm", "academy": "30-38cm"}, "description": "Lower body power (lower due to mass)"},
            {"name": "1RM Squat (relative)", "benchmarks": {"elite": "> 2.0x BW", "academy": "1.7-2.0x BW"}, "description": "Max strength for scrummaging"},
            {"name": "1RM Bench Press (relative)", "benchmarks": {"elite": "> 1.5x BW", "academy": "1.2-1.5x BW"}, "description": "Upper body pressing strength"},
            {"name": "Isometric Neck Strength", "benchmarks": {"elite": "> 400N", "academy": "300-400N"}, "description": "Neck stability for scrum & collisions"},
        ],
        "forge_biases": [
            "Prioritize maximal strength & power",
            "Include isometric & eccentric work for collisions",
            "Emphasize neck & core stability",
            "Avoid high-volume running (manage load)",
            "Use relative strength benchmarks to monitor progress",
        ],
        "injury_risk_factors": [
            "Neck (cervical spine strains from scrummaging)",
            "Shoulder (AC joint, rotator cuff from tackling)",
            "Knee (MCL, ACL from twisting)",
            "Lower back (lumbar strains from lifting)",
            "Hamstring (sprinting & deceleration)",
        ],
    },
    {
        "sport": "Rugby Union",
        "role": "Hooker",
        "sport_specific_exercises": ["Rugby Union"],
        "primary_demands": [
            "Maximal strength for scrummaging & lineout throwing",
            "Explosive power for lifting in lineouts",
            "Agility & mobility for hooking the ball in scrums",
            "Core stability for throwing & rucking",
            "Anaerobic power for repeated high-intensity efforts",
            "Aerobic capacity for cover defense",
        ],
        "priority_movements": [
            "Lineout throwing (overhead & rotational)",
            "Scrum engagement & hooking (isometric & dynamic)",
            "Lifting (explosive extension)",
            "Tackling & rucking (low position & drive)",
            "Single-leg stability for hooking",
        ],
        "priority_exercise_categories": [
            "Maximal strength (squat, deadlift, press)",
            "Overhead stability (YTWL, rotator cuff)",
            "Isometric core holds",
            "Plyometrics (jump squats)",
            "Agility drills (ladder, cone)",
            "Eccentric hamstring (Nordic curls)",
        "Injury Prevention",
        ],
        "tests": [
            {"name": "YoYo IR1", "benchmarks": {"elite": "> 1700m", "academy": "1300-1600m"}, "description": "Aerobic capacity for repeated efforts"},
            {"name": "CMJ", "benchmarks": {"elite": "> 42cm", "academy": "32-40cm"}, "description": "Lower body power for lifting"},
            {"name": "1RM Squat (relative)", "benchmarks": {"elite": "> 1.8x BW", "academy": "1.5-1.8x BW"}, "description": "Max strength for scrummaging"},
            {"name": "Overhead Med Ball Throw (3kg)", "benchmarks": {"elite": "> 8m", "academy": "6-8m"}, "description": "Lineout throwing power"},
            {"name": "Isometric Neck Strength", "benchmarks": {"elite": "> 380N", "academy": "280-380N"}, "description": "Neck stability for scrum & collisions"},
        ],
        "forge_biases": [
            "Prioritize maximal strength & overhead stability",
            "Include isometric & eccentric work",
            "Emphasize agility & mobility",
            "Balance power & aerobic conditioning",
            "Avoid heavy overhead work before throwing sessions",
        ],
        "injury_risk_factors": [
            "Neck (cervical spine strains)",
            "Shoulder (rotator cuff, impingement from throwing)",
            "Knee (MCL, ACL from twisting)",
            "Lower back (lumbar strains from lifting)",
            "Hamstring (sprinting & deceleration)",
        ],
    },
    {
        "sport": "Rugby Union",
        "role": "Lock",
        "sport_specific_exercises": ["Rugby Union"],
        "primary_demands": [
            "Maximal strength & power for lineout jumping & lifting",
            "Eccentric strength for deceleration & collisions",
            "Aerobic capacity for repeated efforts & cover defense",
            "Core stability for lineout lifting & scrummaging",
            "Explosive jumping ability for lineouts",
            "Agility & handling for open play",
        ],
        "priority_movements": [
            "Lineout jumping (explosive extension & landing)",
            "Lifting in lineouts (driving & holding)",
            "Scrum engagement & driving",
            "Tackling & rucking (low position & drive)",
            "Single-leg landing control (after jumps)",
        ],
        "priority_exercise_categories": [
            "Maximal strength (squat, deadlift, press)",
            "Vertical jumps (drop jumps, depth jumps)",
            "Eccentric hamstring (Nordic curls)",
            "Core stability (anti-rotation, bracing)",
            "Agility drills (COD)",
            "Aerobic conditioning (interval runs)",
        "Injury Prevention",
        ],
        "tests": [
            {"name": "YoYo IR1", "benchmarks": {"elite": "> 1800m", "academy": "1400-1700m"}, "description": "Aerobic capacity for repeated efforts"},
            {"name": "CMJ", "benchmarks": {"elite": "> 45cm", "academy": "35-42cm"}, "description": "Lower body power for jumping & lifting"},
            {"name": "1RM Squat (relative)", "benchmarks": {"elite": "> 1.9x BW", "academy": "1.6-1.9x BW"}, "description": "Max strength for scrummaging & lifting"},
            {"name": "1RM Deadlift (relative)", "benchmarks": {"elite": "> 2.0x BW", "academy": "1.7-2.0x BW"}, "description": "Lower body pulling strength"},
            {"name": "5-0-5 COD", "benchmarks": {"elite": "< 2.60s", "academy": "2.60-2.90s"}, "description": "Change of direction for open play"},
        ],
        "forge_biases": [
            "Prioritize maximal strength & vertical jumping",
            "Include eccentric hamstring & core stability",
            "Balance power & aerobic conditioning",
            "Emphasize landing mechanics for injury prevention",
            "Avoid high-volume jumping before match days",
        ],
        "injury_risk_factors": [
            "Knee (patellar tendinopathy, ACL from jumping)",
            "Ankle (sprains from landing)",
            "Lower back (lumbar strains from lifting & scrum)",
            "Shoulder (AC joint from lifting)",
            "Hamstring (sprinting & deceleration)",
        ],
    },
    {
        "sport": "Rugby Union",
        "role": "Back Row",
        "sport_specific_exercises": ["Rugby Union"],
        "primary_demands": [
            "High aerobic & anaerobic capacity for cover defense",
            "Power & speed for carrying & tackling",
            "Agility & handling for open play",
            "Eccentric strength for deceleration & collisions",
            "Core stability for rucking & tackling",
            "Maximal strength for scrummaging & lineouts",
        ],
        "priority_movements": [
            "Multi-directional running (forward, lateral, backward)",
            "Tackling & rucking (low position & drive)",
            "Carrying (explosive drive)",
            "Single-leg landing control (after jumps)",
            "Agility & COD for open play",
        ],
        "priority_exercise_categories": [
            "Strength & power (squat, deadlift, clean)",
            "Eccentric hamstring (Nordic curls)",
            "Agility drills (COD, ladder)",
            "Plyometrics (drop jumps, bounding)",
            "Core stability (anti-rotation, bracing)",
            "Aerobic conditioning (interval runs)",
        "Injury Prevention",
        ],
        "tests": [
            {"name": "YoYo IR1", "benchmarks": {"elite": "> 2000m", "academy": "1500-1800m"}, "description": "High aerobic capacity for cover defense"},
            {"name": "Bronco", "benchmarks": {"elite": "< 5:10", "academy": "5:10-5:40"}, "description": "Multi-directional endurance"},
            {"name": "CMJ", "benchmarks": {"elite": "> 48cm", "academy": "38-45cm"}, "description": "Lower body power for explosive movements"},
            {"name": "10m Sprint", "benchmarks": {"elite": "< 1.75s", "academy": "1.75-1.90s"}, "description": "Acceleration for open play"},
            {"name": "5-0-5 COD", "benchmarks": {"elite": "< 2.45s", "academy": "2.45-2.75s"}, "description": "Change of direction for tackling & carrying"},
        ],
        "forge_biases": [
            "Prioritize aerobic & anaerobic capacity",
            "Include power & speed work",
            "Emphasize eccentric hamstring & core stability",
            "Balance strength & conditioning",
            "Avoid high-volume intensity 48h before matches",
        ],
        "injury_risk_factors": [
            "Hamstring (sprinting & deceleration)",
            "Shoulder (AC joint, rotator cuff from tackling)",
            "Knee (MCL, ACL from twisting)",
            "Ankle (sprains from tackles)",
            "Concussion (head impacts in tackles)",
        ],
    },
    {
        "sport": "Rugby Union",
        "role": "Scrum-half",
        "sport_specific_exercises": ["Rugby Union"],
        "primary_demands": [
            "High agility & acceleration for quick breaks",
            "Excellent handling & passing accuracy",
            "Aerobic capacity for repeated involvement",
            "Core stability for balance & passing",
            "Eccentric strength for deceleration & change of direction",
            "Vision & decision-making under pressure",
        ],
        "priority_movements": [
            "Multi-directional running (forward, lateral, backward)",
            "Quick starts & stops (COD)",
            "Passing motion (kinetic chain)",
            "Single-leg landing control (after breaks)",
            "Agility & evasion (dummy passes, sidesteps)",
        ],
        "priority_exercise_categories": [
            "Agility drills (COD, ladder, cone)",
            "Sprint training (acceleration & deceleration)",
            "Core stability & balance",
            "Hand-eye coordination drills",
            "Aerobic conditioning (interval runs)",
            "Single-leg strength (lunges, split squats)",
        "Injury Prevention",
        ],
        "tests": [
            {"name": "YoYo IR1", "benchmarks": {"elite": "> 2000m", "academy": "1500-1800m"}, "description": "Aerobic capacity for repeated involvement"},
            {"name": "10m Sprint", "benchmarks": {"elite": "< 1.65s", "academy": "1.65-1.80s"}, "description": "Acceleration for quick breaks"},
            {"name": "CMJ", "benchmarks": {"elite": "> 48cm", "academy": "38-45cm"}, "description": "Lower body power for explosive movements"},
            {"name": "5-0-5 COD", "benchmarks": {"elite": "< 2.40s", "academy": "2.40-2.70s"}, "description": "Change of direction for evasion"},
            {"name": "Seated Med Ball Throw (3kg)", "benchmarks": {"elite": "> 6m", "academy": "4-6m"}, "description": "Upper body power for passing"},
        ],
        "forge_biases": [
            "Prioritize agility & acceleration",
            "Include core stability & balance work",
            "Emphasize handling & passing drills",
            "Balance power & endurance",
            "Avoid high-intensity sprinting 48h before matches",
        ],
        "injury_risk_factors": [
            "Hamstring (sprinting & deceleration)",
            "Ankle (sprains from sidesteps)",
            "Shoulder (rotator cuff from tackling)",
            "Knee (patellar tendinopathy from running)",
            "Concussion (head impacts in tackles)",
        ],
    },
    {
        "sport": "Rugby Union",
        "role": "Fly-half",
        "sport_specific_exercises": ["Rugby Union"],
        "primary_demands": [
            "High agility & acceleration for breaks & kicking",
            "Excellent handling & kicking accuracy",
            "Aerobic capacity for repeated involvement",
            "Core stability for balance & kicking",
            "Eccentric strength for deceleration & change of direction",
            "Vision & decision-making under pressure",
        ],
        "priority_movements": [
            "Multi-directional running (forward, lateral, backward)",
            "Quick starts & stops (COD)",
            "Kicking motion (kinetic chain)",
            "Single-leg landing control (after kicks)",
            "Agility & evasion (sidesteps, dummy passes)",
        ],
        "priority_exercise_categories": [
            "Agility drills (COD, ladder, cone)",
            "Sprint training (acceleration & deceleration)",
            "Core stability & balance",
            "Kicking & passing drills",
            "Aerobic conditioning (interval runs)",
            "Single-leg strength (lunges, split squats)",
        "Injury Prevention",
        ],
        "tests": [
            {"name": "YoYo IR1", "benchmarks": {"elite": "> 2000m", "academy": "1500-1800m"}, "description": "Aerobic capacity for repeated involvement"},
            {"name": "10m Sprint", "benchmarks": {"elite": "< 1.65s", "academy": "1.65-1.80s"}, "description": "Acceleration for breaks"},
            {"name": "CMJ", "benchmarks": {"elite": "> 48cm", "academy": "38-45cm"}, "description": "Lower body power for explosive movements"},
            {"name": "5-0-5 COD", "benchmarks": {"elite": "< 2.40s", "academy": "2.40-2.70s"}, "description": "Change of direction for evasion"},
            {"name": "Kicking Power (distance)", "benchmarks": {"elite": "> 60m", "academy": "45-60m"}, "description": "Kicking accuracy & distance"},
        ],
        "forge_biases": [
            "Prioritize agility & acceleration",
            "Include core stability & balance work",
            "Emphasize kicking & passing drills",
            "Balance power & endurance",
            "Avoid high-intensity sprinting 48h before matches",
        ],
        "injury_risk_factors": [
            "Hamstring (sprinting & deceleration)",
            "Ankle (sprains from sidesteps)",
            "Shoulder (rotator cuff from tackling)",
            "Knee (patellar tendinopathy from running)",
            "Concussion (head impacts in tackles)",
        ],
    },
    {
        "sport": "Rugby Union",
        "role": "Centre",
        "sport_specific_exercises": ["Rugby Union"],
        "primary_demands": [
            "High speed & power for line breaks & tackles",
            "Agility & handling for open play",
            "Aerobic capacity for repeated involvement",
            "Eccentric strength for deceleration & collisions",
            "Core stability for balance & tackling",
            "Tackling & defensive organization",
        ],
        "priority_movements": [
            "Linear & lateral sprinting (breaks & cover)",
            "Tackling (low position & drive)",
            "Carrying (explosive drive)",
            "Single-leg landing control (after sprints)",
            "Agility & evasion (sidesteps)",
        ],
        "priority_exercise_categories": [
            "Sprint training (acceleration & max velocity)",
            "Agility drills (COD, ladder)",
            "Strength & power (squat, clean)",
            "Eccentric hamstring (Nordic curls)",
            "Core stability & balance",
            "Aerobic conditioning (interval runs)",
        "Injury Prevention",
        ],
        "tests": [
            {"name": "YoYo IR1", "benchmarks": {"elite": "> 2000m", "academy": "1500-1800m"}, "description": "Aerobic capacity for repeated involvement"},
            {"name": "10m Sprint", "benchmarks": {"elite": "< 1.60s", "academy": "1.60-1.75s"}, "description": "Acceleration for breaks"},
            {"name": "30m Sprint", "benchmarks": {"elite": "< 3.90s", "academy": "3.90-4.20s"}, "description": "Max velocity for open play"},
            {"name": "CMJ", "benchmarks": {"elite": "> 50cm", "academy": "40-48cm"}, "description": "Lower body power for explosive movements"},
            {"name": "5-0-5 COD", "benchmarks": {"elite": "< 2.40s", "academy": "2.40-2.70s"}, "description": "Change of direction for evasion & tackling"},
        ],
        "forge_biases": [
            "Prioritize speed & power",
            "Include COD drills & agility work",
            "Emphasize eccentric hamstring & core stability",
            "Balance power & endurance",
            "Avoid high-intensity sprinting 48h before matches",
        ],
        "injury_risk_factors": [
            "Hamstring (sprinting & deceleration)",
            "Shoulder (AC joint, rotator cuff from tackling)",
            "Ankle (sprains from tackles)",
            "Knee (MCL, ACL from twisting)",
            "Concussion (head impacts in tackles)",
        ],
    },
    {
        "sport": "Rugby Union",
        "role": "Wing",
        "sport_specific_exercises": ["Rugby Union"],
        "primary_demands": [
            "Maximum speed & acceleration for breaks & cover",
            "Agility & handling for open play",
            "Aerobic capacity for repeated involvement",
            "Eccentric strength for deceleration & collisions",
            "Core stability for balance & tackling",
            "Tackling & defensive organization",
        ],
        "priority_movements": [
            "Linear sprinting (acceleration & max velocity)",
            "Lateral & diagonal running (attacking lines)",
            "Tackling (low position & drive)",
            "Single-leg landing control (after sprints)",
            "Agility & evasion (sidesteps)",
        ],
        "priority_exercise_categories": [
            "Sprint training (acceleration & max velocity)",
            "Agility drills (COD, ladder)",
            "Strength & power (squat, clean)",
            "Eccentric hamstring (Nordic curls)",
            "Core stability & balance",
            "Aerobic conditioning (interval runs)",
        "Injury Prevention",
        ],
        "tests": [
            {"name": "YoYo IR1", "benchmarks": {"elite": "> 1800m", "academy": "1400-1700m"}, "description": "Aerobic capacity for repeated involvement"},
            {"name": "10m Sprint", "benchmarks": {"elite": "< 1.55s", "academy": "1.55-1.70s"}, "description": "Acceleration for breaks"},
            {"name": "30m Sprint", "benchmarks": {"elite": "< 3.80s", "academy": "3.80-4.10s"}, "description": "Max velocity for open play"},
            {"name": "CMJ", "benchmarks": {"elite": "> 50cm", "academy": "40-48cm"}, "description": "Lower body power for explosive movements"},
            {"name": "5-0-5 COD", "benchmarks": {"elite": "< 2.30s", "academy": "2.30-2.60s"}, "description": "Change of direction for evasion"},
        ],
        "forge_biases": [
            "Prioritize speed & acceleration",
            "Include COD drills & agility work",
            "Emphasize eccentric hamstring & core stability",
            "Balance power & endurance",
            "Avoid high-intensity sprinting 48h before matches",
        ],
        "injury_risk_factors": [
            "Hamstring (sprinting & deceleration)",
            "Ankle (sprains from tackles)",
            "Shoulder (AC joint from tackling)",
            "Knee (patellar tendinopathy from running)",
            "Concussion (head impacts in tackles)",
        ],
    },
    {
        "sport": "Rugby Union",
        "role": "Fullback",
        "sport_specific_exercises": ["Rugby Union"],
        "primary_demands": [
            "High agility & acceleration for counter-attacks",
            "Excellent handling & kicking accuracy",
            "Aerobic capacity for cover defense",
            "Eccentric strength for deceleration & collisions",
            "Core stability for balance & kicking",
            "Tackling & defensive organization (last line)",
        ],
        "priority_movements": [
            "Multi-directional running (forward, lateral, backward)",
            "Quick starts & stops (COD)",
            "Kicking motion (kinetic chain)",
            "Single-leg landing control (after kicks)",
            "Tackling (low position & drive)",
        ],
        "priority_exercise_categories": [
            "Agility drills (COD, ladder, cone)",
            "Sprint training (acceleration & deceleration)",
            "Core stability & balance",
            "Kicking & passing drills",
            "Aerobic conditioning (interval runs)",
            "Single-leg strength (lunges, split squats)",
        "Injury Prevention",
        ],
        "tests": [
            {"name": "YoYo IR1", "benchmarks": {"elite": "> 2000m", "academy": "1500-1800m"}, "description": "Aerobic capacity for cover defense"},
            {"name": "Bronco", "benchmarks": {"elite": "< 5:00", "academy": "5:00-5:30"}, "description": "Multi-directional endurance for cover"},
            {"name": "10m Sprint", "benchmarks": {"elite": "< 1.65s", "academy": "1.65-1.80s"}, "description": "Acceleration for counter-attacks"},
            {"name": "CMJ", "benchmarks": {"elite": "> 48cm", "academy": "38-45cm"}, "description": "Lower body power for explosive movements"},
            {"name": "5-0-5 COD", "benchmarks": {"elite": "< 2.40s", "academy": "2.40-2.70s"}, "description": "Change of direction for evasion & tackling"},
        ],
        "forge_biases": [
            "Prioritize agility & acceleration",
            "Include core stability & balance work",
            "Emphasize kicking & handling drills",
            "Balance power & endurance",
            "Avoid high-intensity sprinting 48h before matches",
        ],
        "injury_risk_factors": [
            "Hamstring (sprinting & deceleration)",
            "Ankle (sprains from sidesteps)",
            "Shoulder (rotator cuff from tackling)",
            "Knee (patellar tendinopathy from running)",
            "Concussion (head impacts in tackles)",
        ],
    },
    {
        "sport": "Volleyball",
        "role": "Setter",
        "sport_specific_exercises": ["Volleyball"],
        "primary_demands": [
            "High agility & footwork for getting to the ball quickly",
            "Upper body strength & endurance for setting (repeated overhead)",
            "Core stability & balance for consistent setting",
            "Quick decision-making & court vision",
            "Flexibility & mobility (hips, shoulders)",
            "Aerobic capacity for sustained play (long rallies)",
        ],
        "priority_movements": [
            "Quick starts & stops (COD) to the ball",
            "Overhead setting motion (shoulder & wrist control)",
            "Single-leg landing & balance (after setting)",
            "Lateral shuffles for court coverage",
            "Blocking (vertical jumps)",
        ],
        "priority_exercise_categories": [
            "Agility drills (ladder, cone, COD)",
            "Shoulder & wrist strength/endurance (band work, light DB)",
            "Core stability (anti-rotation, anti-extension)",
            "Plyometrics (drop jumps, depth jumps for blocking)",
            "Aerobic conditioning (interval runs)",
            "Block Jump",
            "Approach Jump",
            "Defensive Shuffle",
        "Injury Prevention",
        ],
        "tests": [
            {"name": "YoYo IR1", "benchmarks": {"elite": "> 1800m", "academy": "1400-1700m"}, "description": "Aerobic capacity for sustained play"},
            {"name": "CMJ", "benchmarks": {"elite": "> 45cm", "academy": "35-42cm"}, "description": "Lower body power for blocking & jumping"},
            {"name": "5-0-5 COD", "benchmarks": {"elite": "< 2.50s", "academy": "2.50-2.80s"}, "description": "Change of direction for court coverage"},
            {"name": "Seated Med Ball Throw (3kg)", "benchmarks": {"elite": "> 6m", "academy": "4-6m"}, "description": "Upper body power for setting"},
            {"name": "Single-Leg Balance (eyes closed)", "benchmarks": {"elite": "> 30s", "academy": "20-25s"}, "description": "Stability & proprioception"},
        ],
        "forge_biases": [
            "Prioritize agility & footwork",
            "Include shoulder & wrist endurance work",
            "Emphasize core stability for balance",
            "Add jumping/blocking sessions (lower volume)",
            "Avoid heavy upper body pressing before setting practice",
        ],
        "injury_risk_factors": [
            "Shoulder (rotator cuff, impingement from repetitive setting)",
            "Wrist (tendinitis from setting)",
            "Knee (patellar tendinopathy from jumping)",
            "Ankle (sprains from quick movements)",
            "Lower back (lumbar strains from arching on sets)",
        ],
    },
    {
        "sport": "Volleyball",
        "role": "Outside Hitter",
        "sport_specific_exercises": ["Volleyball"],
        "primary_demands": [
            "Explosive power for attacking (spiking) from left/front",
            "Vertical jumping ability for hitting & blocking",
            "Eccentric strength for landing control",
            "Agility & speed for court coverage",
            "Shoulder strength & endurance for repeated spikes",
            "Core stability & rotation for power generation",
        ],
        "priority_movements": [
            "Approach jumps (3-step or 4-step)",
            "Spiking motion (kinetic chain from legs to arm)",
            "Single-leg landing control (after jumps)",
            "Lateral shuffles & backpedaling (defense)",
            "Blocking at the net (vertical jumps)",
        ],
        "priority_exercise_categories": [
            "Vertical jumps (drop jumps, depth jumps, box jumps)",
            "Plyometric drills (bounding, hurdle jumps)",
            "Shoulder power (med ball throws, overhead slams)",
            "Eccentric hamstring & quad work (Nordic, landing drills)",
            "Core anti-rotation & rotation (cable chops, Russian twists)",
            "Agility drills (COD, ladder)",
            "Block Jump",
            "Approach Jump",
            "Defensive Shuffle",
            "Depth Drop",
        "Injury Prevention",
        ],
        "tests": [
            {"name": "YoYo IR1", "benchmarks": {"elite": "> 1800m", "academy": "1400-1700m"}, "description": "Aerobic capacity for sustained play"},
            {"name": "CMJ", "benchmarks": {"elite": "> 55cm", "academy": "45-52cm"}, "description": "Lower body explosive power for spiking"},
            {"name": "Approach Jump Reach", "benchmarks": {"elite": "> 350cm", "academy": "320-345cm"}, "description": "Vertical reach for spiking & blocking"},
            {"name": "Overhead MB Throw (3kg)", "benchmarks": {"elite": "> 10m", "academy": "7-9m"}, "description": "Shoulder & core power for spiking"},
            {"name": "5-0-5 COD", "benchmarks": {"elite": "< 2.40s", "academy": "2.40-2.70s"}, "description": "Change of direction for court coverage"},
        ],
        "forge_biases": [
            "Prioritize vertical jumping & plyometrics",
            "Include shoulder power & stability work",
            "Emphasize eccentric hamstring & landing mechanics",
            "Add core rotation & anti-rotation exercises",
            "Avoid high-volume jumping 48h before matches",
        ],
        "injury_risk_factors": [
            "Knee (patellar tendinopathy, ACL from landing)",
            "Shoulder (rotator cuff, impingement from spiking)",
            "Ankle (sprains from landing on opponents)",
            "Lower back (lumbar strains from arching on spikes)",
            "Hamstring (sprinting & deceleration)",
        ],
    },
    {
        "sport": "Volleyball",
        "role": "Middle Blocker",
        "sport_specific_exercises": ["Volleyball"],
        "primary_demands": [
            "Maximal vertical jumping for blocking & quick attacks",
            "Explosive power for quick sets (middle attacks)",
            "Agility & lateral speed for blocking movement",
            "Eccentric strength for landing control",
            "Core stability for blocking & attacking",
            "Aerobic capacity for sustained play",
        ],
        "priority_movements": [
            "Vertical jumps (blocking & attacking)",
            "Lateral shuffles & slides for blocking",
            "Quick approach jumps (1-step or 2-step)",
            "Single-leg landing control (after jumps)",
            "Blocking arm press (shoulder & core)",
        ],
        "priority_exercise_categories": [
            "Vertical jumps (drop jumps, depth jumps, box jumps)",
            "Lateral agility drills (shuffle, slide)",
            "Plyometrics (hurdle jumps, bounding)",
            "Shoulder & core stability (anti-rotation, overhead)",
            "Eccentric hamstring & quad work (landing drills)",
            "Aerobic conditioning (interval runs)",
            "Block Jump",
            "Approach Jump",
            "Defensive Shuffle",
            "Depth Drop",
        "Injury Prevention",
        ],
        "tests": [
            {"name": "YoYo IR1", "benchmarks": {"elite": "> 1700m", "academy": "1300-1600m"}, "description": "Aerobic capacity for sustained play"},
            {"name": "CMJ", "benchmarks": {"elite": "> 50cm", "academy": "40-48cm"}, "description": "Lower body explosive power for blocking"},
            {"name": "Approach Jump Reach", "benchmarks": {"elite": "> 340cm", "academy": "310-335cm"}, "description": "Vertical reach for blocking & attacking"},
            {"name": "5-0-5 COD", "benchmarks": {"elite": "< 2.50s", "academy": "2.50-2.80s"}, "description": "Lateral agility for blocking"},
            {"name": "Overhead MB Throw (3kg)", "benchmarks": {"elite": "> 9m", "academy": "6-8m"}, "description": "Shoulder power for blocking & attacking"},
        ],
        "forge_biases": [
            "Prioritize vertical jumping & lateral agility",
            "Include eccentric hamstring & landing drills",
            "Emphasize core & shoulder stability",
            "Balance power & conditioning",
            "Avoid high-volume jumping 48h before matches",
        ],
        "injury_risk_factors": [
            "Knee (patellar tendinopathy, ACL from landing)",
            "Ankle (sprains from landing on opponents)",
            "Shoulder (rotator cuff, impingement from blocking)",
            "Lower back (lumbar strains from arching on attacks)",
            "Finger (sprains from blocking)",
        ],
    },
    {
        "sport": "Volleyball",
        "role": "Opposite",
        "sport_specific_exercises": ["Volleyball"],
        "primary_demands": [
            "Explosive power for attacking from right side",
            "Vertical jumping ability for hitting & blocking",
            "Shoulder strength & endurance for spikes",
            "Agility & speed for court coverage",
            "Eccentric strength for landing control",
            "Core stability & rotation for power generation",
            "Often backs up setter duties",
        ],
        "priority_movements": [
            "Approach jumps from right side (3-step or 4-step)",
            "Spiking motion (kinetic chain)",
            "Single-leg landing control (after jumps)",
            "Lateral shuffles & backpedaling (defense)",
            "Blocking at the net (vertical jumps)",
        ],
        "priority_exercise_categories": [
            "Vertical jumps (drop jumps, depth jumps, box jumps)",
            "Plyometric drills (bounding, hurdle jumps)",
            "Shoulder power (med ball throws, overhead slams)",
            "Eccentric hamstring & quad work (Nordic, landing drills)",
            "Core anti-rotation & rotation (cable chops, Russian twists)",
            "Agility drills (COD, ladder)",
            "Block Jump",
            "Approach Jump",
            "Defensive Shuffle",
            "Depth Drop",
        "Injury Prevention",
        ],
        "tests": [
            {"name": "YoYo IR1", "benchmarks": {"elite": "> 1800m", "academy": "1400-1700m"}, "description": "Aerobic capacity for sustained play"},
            {"name": "CMJ", "benchmarks": {"elite": "> 55cm", "academy": "45-52cm"}, "description": "Lower body explosive power for attacking"},
            {"name": "Approach Jump Reach", "benchmarks": {"elite": "> 345cm", "academy": "315-340cm"}, "description": "Vertical reach for attacking & blocking"},
            {"name": "Overhead MB Throw (3kg)", "benchmarks": {"elite": "> 10m", "academy": "7-9m"}, "description": "Shoulder & core power for spiking"},
            {"name": "5-0-5 COD", "benchmarks": {"elite": "< 2.40s", "academy": "2.40-2.70s"}, "description": "Change of direction for court coverage"},
        ],
        "forge_biases": [
            "Prioritize vertical jumping & plyometrics",
            "Include shoulder power & stability work",
            "Emphasize eccentric hamstring & landing mechanics",
            "Add core rotation & anti-rotation exercises",
            "Avoid high-volume jumping 48h before matches",
        ],
        "injury_risk_factors": [
            "Knee (patellar tendinopathy, ACL from landing)",
            "Shoulder (rotator cuff, impingement from spiking)",
            "Ankle (sprains from landing on opponents)",
            "Lower back (lumbar strains from arching on spikes)",
            "Hamstring (sprinting & deceleration)",
        ],
    },
    {
        "sport": "Volleyball",
        "role": "Libero",
        "sport_specific_exercises": ["Volleyball"],
        "primary_demands": [
            "High agility & speed for defensive coverage",
            "Excellent passing & digging skills (forearm & overhead)",
            "Eccentric strength for diving & landing control",
            "Aerobic capacity for sustained rally play",
            "Core stability for low body position & balance",
            "Reactive ability & reading of the game",
        ],
        "priority_movements": [
            "Quick starts & stops (COD) to the ball",
            "Diving & rolling (low-body control)",
            "Forearm passing (platform)",
            "Single-leg landing control (after diving)",
            "Lateral shuffles & backpedaling (defense)",
        ],
        "priority_exercise_categories": [
            "Agility drills (ladder, cone, COD)",
            "Diving & rolling mechanics (low-body)",
            "Core stability & balance (anti-rotation, anti-extension)",
            "Passing & digging drills (hand-eye coordination)",
            "Aerobic conditioning (interval runs)",
            "Shoulder & forearm endurance (band work, light DB)",
            "Defensive Shuffle",
        "Injury Prevention",
        ],
        "tests": [
            {"name": "YoYo IR1", "benchmarks": {"elite": "> 1900m", "academy": "1500-1800m"}, "description": "Aerobic capacity for sustained defensive play"},
            {"name": "Bronco", "benchmarks": {"elite": "< 5:10", "academy": "5:10-5:40"}, "description": "Multi-directional endurance for defense"},
            {"name": "5-0-5 COD", "benchmarks": {"elite": "< 2.40s", "academy": "2.40-2.70s"}, "description": "Change of direction for defensive coverage"},
            {"name": "CMJ", "benchmarks": {"elite": "> 40cm", "academy": "30-38cm"}, "description": "Lower body power (lower priority for libero)"},
            {"name": "Single-Leg Balance (eyes closed)", "benchmarks": {"elite": "> 35s", "academy": "25-30s"}, "description": "Stability & proprioception for diving & passing"},
        ],
        "forge_biases": [
            "Prioritize agility & quickness",
            "Include core stability & balance work",
            "Emphasize reactive drills & decision-making",
            "Add defensive-specific conditioning (short bursts)",
            "Avoid heavy lower body loading before match days",
        ],
        "injury_risk_factors": [
            "Knee (patellar tendinopathy, meniscus from diving)",
            "Ankle (sprains from quick movements)",
            "Shoulder (rotator cuff, impingement from passing)",
            "Lower back (lumbar strains from low position)",
            "Wrist (sprains from passing)",
        ],
    },
    {
        "sport": "*",
        "role": "*",
        "sport_specific_exercises": ["*"],
        "primary_demands": [
            "Sport-specific movement preparation",
            "General athletic power & conditioning",
            "Injury resilience through balanced strength",
            "Aerobic & alactic energy system development",
        ],
        "priority_movements": [
            "Fundamental squat / hinge / push / pull / carry patterns",
            "Linear & lateral athleticism (accel, decel, COD)",
            "Core stiffness & anti-rotation",
            "Single-leg strength & stability",
        ],
        "priority_exercise_categories": [
            "Athletic strength foundation",
            "Linear speed & agility",
            "Lateral movement",
            "Core stability",
            "Conditioning base",
        "Injury Prevention",
        ],
        "tests": [
            {"name": "YoYo IR1", "benchmarks": {"elite": "> 18.0", "developmental": "14.0–18.0"}, "description": "General aerobic capacity"},
            {"name": "CMJ (relative)", "benchmarks": {"elite": "> 48 W/kg", "developmental": "38–48 W/kg"}, "description": "Lower body power baseline"},
            {"name": "10m Sprint", "benchmarks": {"elite": "< 1.80s", "developmental": "1.80–2.00s"}, "description": "Acceleration capacity"},
            {"name": "Countermovement Jump (RSI)", "benchmarks": {"elite": "> 2.5", "developmental": "2.0–2.5"}, "description": "Reactive strength / stretch-shortening cycle efficiency"},
        ],
        "forge_biases": [
            "Default to balanced athletic development blueprint",
            "Prefer compound movements over isolation",
            "Use volume as primary progression lever",
            "Monitor readiness via CMJ or subjective wellness",
        ],
        "injury_risk_factors": [
            "Hamstring (high-speed running)",
            "Ankle (contact / uneven surfaces)",
            "Lower back (general rotation / flexion loading)",
        ],
    },
]


def get_role_profile(sport: str, role: str) -> dict:
    for p in ROLE_PROFILES:
        if p["sport"] == sport and p["role"] == role:
            return p
    return {}
